#!/usr/bin/env bash
# Preview deploy provenance — component-aware /health/version metadata for Helm + BFF.
set -euo pipefail

PREVIEW_CERTIFIED_COMMIT_FILE="${PREVIEW_CERTIFIED_COMMIT_FILE:-reports/full-boot/full-estate-certified-commit.txt}"
PREVIEW_PROVENANCE_VALUES="${PREVIEW_PROVENANCE_VALUES:-deploy/helm/impilo-vnext/values-preview-provenance.generated.yaml}"

preview_read_deployment_env() {
  local deploy="$1"
  local env_name="$2"
  local ns="${FULL_BOOT_NAMESPACE:-impilo-full-preview}"
  kubectl get deploy "$deploy" -n "$ns" -o json 2>/dev/null \
    | python3 -c "
import json, sys
name = sys.argv[1]
data = json.load(sys.stdin)
for c in data.get('spec', {}).get('template', {}).get('spec', {}).get('containers', []):
    for e in c.get('env', []):
        if e.get('name') == name:
            print(e.get('value', ''))
            sys.exit(0)
print('')
" "$env_name" 2>/dev/null || true
}

preview_read_bff_commit_from_cluster() {
  local v
  v="$(preview_read_deployment_env experience-bff IMPILO_BFF_GIT_COMMIT)"
  [[ -n "$v" ]] && { echo "$v"; return; }
  v="$(preview_read_deployment_env experience-bff IMPILO_GIT_COMMIT)"
  [[ -n "$v" ]] && { echo "$v"; return; }
  echo ""
}

preview_read_shell_commit_from_cluster() {
  local v
  v="$(preview_read_deployment_env one-ui-shell NEXT_PUBLIC_GIT_COMMIT)"
  [[ -n "$v" ]] && { echo "$v"; return; }
  echo ""
}

preview_read_full_estate_commit_from_cluster() {
  local v
  v="$(preview_read_deployment_env experience-bff IMPILO_FULL_ESTATE_COMMIT)"
  [[ -n "$v" ]] && { echo "$v"; return; }
  preview_read_bff_commit_from_cluster
}

preview_read_certified_commit() {
  if [[ -f "$PREVIEW_CERTIFIED_COMMIT_FILE" ]]; then
    tr -d '[:space:]' <"$PREVIEW_CERTIFIED_COMMIT_FILE"
    return
  fi
  echo ""
}

preview_record_certified_commit() {
  local commit="${1:-}"
  [[ -n "$commit" ]] || return 0
  mkdir -p "$(dirname "$PREVIEW_CERTIFIED_COMMIT_FILE")"
  printf '%s\n' "$commit" >"$PREVIEW_CERTIFIED_COMMIT_FILE"
}

preview_digest_json_for_images() {
  local images_csv="${1:-}"
  local digests_file="${2:-deploy/helm/impilo-vnext/values-full-preview-digests.generated.yaml}"
  [[ -n "$images_csv" ]] || { echo '{}'; return; }
  python3 - "$images_csv" "$digests_file" <<'PY'
import json, re, sys
from pathlib import Path

images = [x.strip() for x in sys.argv[1].split(",") if x.strip()]
path = Path(sys.argv[2])
text = path.read_text() if path.is_file() else ""
aliases = {
    "one-ui-shell": ["one-ui-shell", "oneUiShell"],
    "experience-bff": ["experience-bff", "experienceBff"],
}
out = {}
for sid in images:
    keys = aliases.get(sid, [sid])
    digest = ""
    for key in keys:
        m = re.search(
            rf"^\s+{re.escape(key)}:\s*\n(?:\s+image:\s*\n)?\s+digest:\s*(sha256:[a-f0-9]+)",
            text,
            re.M,
        )
        if m:
            digest = m.group(1)
            break
    if digest:
        out[sid] = digest
print(json.dumps(out))
PY
}

preview_write_provenance_values() {
  local mode="$1"            # full-boot | targeted
  local shell_commit="$2"
  local bff_commit="$3"
  local estate_commit="$4"
  local certified_commit="$5"
  local helm_revision="${6:-}"
  local image_digests_json="${7:-{}}"
  local generated_at
  generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  mkdir -p "$(dirname "$PREVIEW_PROVENANCE_VALUES")"
  local digests_file="${PREVIEW_DIGESTS_JSON_FILE:-}"
  local cleanup_digests=0
  if [[ -z "$digests_file" || ! -f "$digests_file" ]]; then
    digests_file="$(mktemp "${TMPDIR:-/tmp}/impilo-preview-digests.XXXXXX")"
    printf '%s' "$image_digests_json" >"$digests_file"
    cleanup_digests=1
  fi
  IMPILO_PREVIEW_DIGESTS_FILE="$digests_file" python3 - "$PREVIEW_PROVENANCE_VALUES" "$mode" "$shell_commit" "$bff_commit" \
    "$estate_commit" "$certified_commit" "${FULL_BOOT_RELEASE:-impilo-full-preview}" \
    "$helm_revision" "$generated_at" <<'PY'
import json, os, sys, pathlib
out_path, mode, shell, bff, estate, certified, release, revision, generated = sys.argv[1:10]
digests_path = os.environ.get("IMPILO_PREVIEW_DIGESTS_FILE", "")
digests = json.loads(pathlib.Path(digests_path).read_text() if digests_path else "{}")
lines = [
    "# Generated by scripts/preview/_preview-deploy-provenance.sh — do not hand-edit.",
    "global:",
    f"  deploymentMode: {json.dumps(mode)}",
    f"  shellGitCommit: {json.dumps(shell)}",
    f"  bffGitCommit: {json.dumps(bff)}",
    f"  fullEstateCommit: {json.dumps(estate)}",
    f"  fullEstateCertifiedCommit: {json.dumps(certified)}",
    f"  helmRelease: {json.dumps(release)}",
    f"  helmRevision: {json.dumps(revision)}",
    f"  versionGeneratedAt: {json.dumps(generated)}",
    f"  imageDigestsJson: {json.dumps(json.dumps(digests))}",
]
pathlib.Path(out_path).write_text("\n".join(lines) + "\n")
PY
  [[ "$cleanup_digests" == "1" ]] && rm -f "$digests_file"
  echo "OK: wrote $PREVIEW_PROVENANCE_VALUES (mode=$mode)"
}

preview_helm_provenance_args() {
  # Emits nothing — provenance is in values file. Kept for callers that expect an array name.
  :
}

preview_resolve_targeted_provenance() {
  local head_commit="$1"
  local images_csv="$2"
  local bff_rebuilt=0
  local shell_rebuilt=0
  [[ "$images_csv" == *"experience-bff"* ]] && bff_rebuilt=1
  [[ "$images_csv" == *"one-ui-shell"* ]] && shell_rebuilt=1

  local shell_commit bff_commit estate_commit certified
  certified="$(preview_read_certified_commit)"
  estate_commit="$(preview_read_full_estate_commit_from_cluster)"
  bff_commit="$(preview_read_bff_commit_from_cluster)"
  shell_commit="$(preview_read_shell_commit_from_cluster)"

  [[ -n "$estate_commit" ]] || estate_commit="${certified:-$bff_commit}"
  [[ -n "$bff_commit" ]] || bff_commit="$estate_commit"
  [[ -n "$shell_commit" ]] || shell_commit="$estate_commit"

  [[ "$shell_rebuilt" == "1" ]] && shell_commit="$head_commit"
  [[ "$bff_rebuilt" == "1" ]] && bff_commit="$head_commit"

  if [[ "$bff_rebuilt" == "1" && "$shell_rebuilt" == "1" ]]; then
    estate_commit="$head_commit"
  elif [[ -z "$estate_commit" ]]; then
    estate_commit="$bff_commit"
  fi

  PREVIEW_PROV_SHELL_COMMIT="$shell_commit"
  PREVIEW_PROV_BFF_COMMIT="$bff_commit"
  PREVIEW_PROV_ESTATE_COMMIT="$estate_commit"
  PREVIEW_PROV_CERTIFIED_COMMIT="$certified"
  export PREVIEW_PROV_SHELL_COMMIT PREVIEW_PROV_BFF_COMMIT PREVIEW_PROV_ESTATE_COMMIT PREVIEW_PROV_CERTIFIED_COMMIT
}

preview_resolve_full_boot_provenance() {
  local head_commit="$1"
  PREVIEW_PROV_SHELL_COMMIT="$head_commit"
  PREVIEW_PROV_BFF_COMMIT="$head_commit"
  PREVIEW_PROV_ESTATE_COMMIT="$head_commit"
  PREVIEW_PROV_CERTIFIED_COMMIT="$head_commit"
  export PREVIEW_PROV_SHELL_COMMIT PREVIEW_PROV_BFF_COMMIT PREVIEW_PROV_ESTATE_COMMIT PREVIEW_PROV_CERTIFIED_COMMIT
}

preview_helm_current_revision() {
  helm history "${FULL_BOOT_RELEASE:-impilo-full-preview}" -n "${FULL_BOOT_NAMESPACE:-impilo-full-preview}" --max 1 -o json 2>/dev/null \
    | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d[0]["revision"] if d else "0")' 2>/dev/null || echo "0"
}
