/**
 * Auto-generated Administration & Governance route registry.
 * Regenerate: node scripts/scaffold-admin-governance-pages.mjs
 */

export const ADMINISTRATION_GOVERNANCE_ROUTES = [
  { path: "/work/administration-governance", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Administration & Governance", navLabel: "Administration & Governance", navZone: "work" },
  { path: "/work/administration-governance/access-requests", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Access Requests", navLabel: "Access Requests", navZone: "work" },
  { path: "/work/administration-governance/access-review", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Access Review", navLabel: "Access Review", navZone: "work" },
  { path: "/work/administration-governance/access-review/[subjectId]", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Access Review", navLabel: "Access Review", navZone: "work" },
  { path: "/work/administration-governance/audit", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Audit", navLabel: "Audit", navZone: "work" },
  { path: "/work/administration-governance/gdhcn-readiness", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "GDHCN Readiness", navLabel: "GDHCN Readiness", navZone: "work" },
  { path: "/work/administration-governance/municipal", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Municipal", navLabel: "Municipal", navZone: "work" },
  { path: "/work/administration-governance/onboard", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard New Actor", navLabel: "Onboard New Actor", navZone: "work" },
  { path: "/work/administration-governance/onboard/citizen", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Citizen", navLabel: "Onboard Citizen", navZone: "work" },
  { path: "/work/administration-governance/onboard/external-partner-user", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard External Partner User", navLabel: "Onboard External Partner User", navZone: "work" },
  { path: "/work/administration-governance/onboard/hsc-user", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Hsc User", navLabel: "Onboard Hsc User", navZone: "work" },
  { path: "/work/administration-governance/onboard/madi-user", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Madi User", navLabel: "Onboard Madi User", navZone: "work" },
  { path: "/work/administration-governance/onboard/marketplace-user", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Marketplace User", navLabel: "Onboard Marketplace User", navZone: "work" },
  { path: "/work/administration-governance/onboard/municipal-user", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Municipal User", navLabel: "Onboard Municipal User", navZone: "work" },
  { path: "/work/administration-governance/onboard/payer-user", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Payer User", navLabel: "Onboard Payer User", navZone: "work" },
  { path: "/work/administration-governance/onboard/private-facility-user", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Private Facility User", navLabel: "Onboard Private Facility User", navZone: "work" },
  { path: "/work/administration-governance/onboard/provider-worker", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Provider Worker", navLabel: "Onboard Provider Worker", navZone: "work" },
  { path: "/work/administration-governance/onboard/public-sector-worker", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Public Sector Worker", navLabel: "Onboard Public Sector Worker", navZone: "work" },
  { path: "/work/administration-governance/onboard/regulator-user", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Regulator User", navLabel: "Onboard Regulator User", navZone: "work" },
  { path: "/work/administration-governance/onboard/system-admin", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard System Admin", navLabel: "Onboard System Admin", navZone: "work" },
  { path: "/work/administration-governance/onboard/training-user", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Onboard Training User", navLabel: "Onboard Training User", navZone: "work" },
  { path: "/work/administration-governance/organisations", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Organisations", navLabel: "Organisations", navZone: "work" },
  { path: "/work/administration-governance/organisations/new", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "New", navLabel: "New", navZone: "work" },
  { path: "/work/administration-governance/organisations/[orgId]", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Organisations", navLabel: "Organisations", navZone: "work" },
  { path: "/work/administration-governance/organisations/[orgId]/api-access", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Api Access", navLabel: "Api Access", navZone: "work" },
  { path: "/work/administration-governance/organisations/[orgId]/audit", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Audit", navLabel: "Audit", navZone: "work" },
  { path: "/work/administration-governance/organisations/[orgId]/contracts", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Contracts", navLabel: "Contracts", navZone: "work" },
  { path: "/work/administration-governance/organisations/[orgId]/data-sharing", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Data Sharing", navLabel: "Data Sharing", navZone: "work" },
  { path: "/work/administration-governance/organisations/[orgId]/data-uploads", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Data Uploads", navLabel: "Data Uploads", navZone: "work" },
  { path: "/work/administration-governance/organisations/[orgId]/users", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Users", navLabel: "Users", navZone: "work" },
  { path: "/work/administration-governance/organisations/[orgId]/verification", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Verification", navLabel: "Verification", navZone: "work" },
  { path: "/work/administration-governance/private-facility", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Private Facility", navLabel: "Private Facility", navZone: "work" },
  { path: "/work/facility/[facilityId]/audit/access", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Access", navLabel: "Access", navZone: "work" },
  { path: "/work/facility/[facilityId]/departments/[departmentId]/staff", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Staff", navLabel: "Staff", navZone: "work" },
  { path: "/work/facility/[facilityId]/staff-access", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Staff Access", navLabel: "Staff Access", navZone: "work" },
  { path: "/work/facility/[facilityId]/staff-access/add", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Add", navLabel: "Add", navZone: "work" },
  { path: "/work/facility/[facilityId]/staff-access/[assignmentId]", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Staff Access", navLabel: "Staff Access", navZone: "work" },
  { path: "/work/facility/staff-access", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Staff Access", navLabel: "Staff Access", navZone: "work" },
  { path: "/work/fundo/admin/accreditation", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Accreditation", navLabel: "Accreditation", navZone: "work" },
  { path: "/work/fundo/admin/courses", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Courses", navLabel: "Courses", navZone: "work" },
  { path: "/work/fundo/admin/partners", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Partners", navLabel: "Partners", navZone: "work" },
  { path: "/work/fundo/admin/partners/[orgId]/users", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Users", navLabel: "Users", navZone: "work" },
  { path: "/work/hsc", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Hsc", navLabel: "Hsc", navZone: "work" },
  { path: "/work/hsc/appointments", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Appointments", navLabel: "Appointments", navZone: "work" },
  { path: "/work/hsc/audit", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Audit", navLabel: "Audit", navZone: "work" },
  { path: "/work/hsc/discipline", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Discipline", navLabel: "Discipline", navZone: "work" },
  { path: "/work/hsc/establishment", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Establishment", navLabel: "Establishment", navZone: "work" },
  { path: "/work/hsc/postings", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Postings", navLabel: "Postings", navZone: "work" },
  { path: "/work/hsc/posts", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Posts", navLabel: "Posts", navZone: "work" },
  { path: "/work/hsc/scope", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Scope", navLabel: "Scope", navZone: "work" },
  { path: "/work/hsc/transfers", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Transfers", navLabel: "Transfers", navZone: "work" },
  { path: "/work/hsc/users", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Users", navLabel: "Users", navZone: "work" },
  { path: "/work/madi/admin", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Admin", navLabel: "Admin", navZone: "work" },
  { path: "/work/madi/assignments", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Assignments", navLabel: "Assignments", navZone: "work" },
  { path: "/work/madi/audit", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Audit", navLabel: "Audit", navZone: "work" },
  { path: "/work/madi/blood-banks", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Blood Banks", navLabel: "Blood Banks", navZone: "work" },
  { path: "/work/madi/users", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Users", navLabel: "Users", navZone: "work" },
  { path: "/work/marketplace/organisations", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Organisations", navLabel: "Organisations", navZone: "work" },
  { path: "/work/marketplace/organisations/[orgId]/api-access", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Api Access", navLabel: "Api Access", navZone: "work" },
  { path: "/work/marketplace/organisations/[orgId]/audit", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Audit", navLabel: "Audit", navZone: "work" },
  { path: "/work/marketplace/organisations/[orgId]/compliance", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Compliance", navLabel: "Compliance", navZone: "work" },
  { path: "/work/marketplace/organisations/[orgId]/products", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Products", navLabel: "Products", navZone: "work" },
  { path: "/work/marketplace/organisations/[orgId]/users", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Users", navLabel: "Users", navZone: "work" },
  { path: "/work/partners", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Partners", navLabel: "Partners", navZone: "work" },
  { path: "/work/partners/[orgId]/audit", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Audit", navLabel: "Audit", navZone: "work" },
  { path: "/work/partners/[orgId]/data-access", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Data Access", navLabel: "Data Access", navZone: "work" },
  { path: "/work/partners/[orgId]/projects", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Projects", navLabel: "Projects", navZone: "work" },
  { path: "/work/partners/[orgId]/users", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Users", navLabel: "Users", navZone: "work" },
  { path: "/work/payers", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Payers", navLabel: "Payers", navZone: "work" },
  { path: "/work/payers/[orgId]/api-access", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Api Access", navLabel: "Api Access", navZone: "work" },
  { path: "/work/payers/[orgId]/claims-access", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Claims Access", navLabel: "Claims Access", navZone: "work" },
  { path: "/work/payers/[orgId]/compliance", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Compliance", navLabel: "Compliance", navZone: "work" },
  { path: "/work/payers/[orgId]/users", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Users", navLabel: "Users", navZone: "work" },
  { path: "/work/regulators", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Regulators", navLabel: "Regulators", navZone: "work" },
  { path: "/work/regulators/[regulatorId]", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Regulators", navLabel: "Regulators", navZone: "work" },
  { path: "/work/regulators/[regulatorId]/audit", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Audit", navLabel: "Audit", navZone: "work" },
  { path: "/work/regulators/[regulatorId]/cases", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Cases", navLabel: "Cases", navZone: "work" },
  { path: "/work/regulators/[regulatorId]/cpd-review", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Cpd Review", navLabel: "Cpd Review", navZone: "work" },
  { path: "/work/regulators/[regulatorId]/disciplinary", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Disciplinary", navLabel: "Disciplinary", navZone: "work" },
  { path: "/work/regulators/[regulatorId]/licence-review", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Licence Review", navLabel: "Licence Review", navZone: "work" },
  { path: "/work/regulators/[regulatorId]/registration-review", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Registration Review", navLabel: "Registration Review", navZone: "work" },
  { path: "/work/regulators/[regulatorId]/restrictions", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Restrictions", navLabel: "Restrictions", navZone: "work" },
  { path: "/work/regulators/[regulatorId]/users", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Users", navLabel: "Users", navZone: "work" },
  { path: "/work/system-admin", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "System Admin", navLabel: "System Admin", navZone: "work" },
  { path: "/work/system-admin/audit", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Audit", navLabel: "Audit", navZone: "work" },
  { path: "/work/system-admin/break-glass", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Break Glass", navLabel: "Break Glass", navZone: "work" },
  { path: "/work/system-admin/integrations", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Integrations", navLabel: "Integrations", navZone: "work" },
  { path: "/work/system-admin/keycloak", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Keycloak", navLabel: "Keycloak", navZone: "work" },
  { path: "/work/system-admin/opa", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Opa", navLabel: "Opa", navZone: "work" },
  { path: "/work/system-admin/scopes", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Scopes", navLabel: "Scopes", navZone: "work" },
  { path: "/work/system-admin/tshepo", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Tshepo", navLabel: "Tshepo", navZone: "work" },
  { path: "/work/system-admin/users", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Users", navLabel: "Users", navZone: "work" },
  { path: "/work/vashandi", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Vashandi Workforce", navLabel: "Vashandi", navZone: "work" },
  { path: "/work/vashandi/workforce", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Workforce Registry", navLabel: "Workforce", navZone: "work" },
  { path: "/work/vashandi/workforce/[id]", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Workforce Profile", navLabel: "Workforce", navZone: "work" },
  { path: "/work/vashandi/assignments", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Assignments", navLabel: "Assignments", navZone: "work" },
  { path: "/work/vashandi/rosters", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Rosters", navLabel: "Rosters", navZone: "work" },
  { path: "/work/vashandi/attendance", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Attendance", navLabel: "Attendance", navZone: "work" },
  { path: "/work/vashandi/leave-availability", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Leave Availability", navLabel: "Leave", navZone: "work" },
  { path: "/work/vashandi/imports", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Imports", navLabel: "Imports", navZone: "work" },
  { path: "/work/vashandi/access-review", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Access Review", navLabel: "Access Review", navZone: "work" },
  { path: "/work/vashandi/analytics", zone: "operations", layout: "app", sidebar: "admin", guard: "auth", pageTitle: "Analytics", navLabel: "Analytics", navZone: "work" },
] as const;

export const ADMINISTRATION_GOVERNANCE_ROUTE_COUNT = 100;
