-- ============================================================================
-- V008: Listing price columns + ZW starter indicative marketplace catalogue.
--
--   1. msika_listings gains vendor-set price columns (price_amount /
--      price_currency). Price is LISTING-level truth (the vendor's offer);
--      the catalogue seed below deliberately carries NO prices.
--   2. Seeds one PUBLISHED platform catalogue ('ZW Starter Marketplace
--      Catalogue', tenant NULL = NATIONAL) with an EDLIZ-indicative essential
--      medicines subset and equipment/consumables aligned to the V007
--      sourcing categories, so a fresh estate has a sellable starter range.
--
--   HONESTY: every item is provenance INDICATIVE — a curated starter set,
--   NOT the authoritative EDLIZ/NatPharm master. Governed catalogue imports
--   replace/extend it; ON CONFLICT DO NOTHING keeps re-runs and later
--   authoritative loads safe. Deterministic literal item ids (STARTER…,
--   26 chars) keep the seed idempotent across environments.
-- ============================================================================

ALTER TABLE msika_listings ADD COLUMN IF NOT EXISTS price_amount NUMERIC(12,2);
ALTER TABLE msika_listings ADD COLUMN IF NOT EXISTS price_currency VARCHAR(3) DEFAULT 'ZWG';

-- ----------------------------------------------------------------------------
-- Starter platform catalogue container (tenant NULL = NATIONAL scope).
-- ----------------------------------------------------------------------------
INSERT INTO msika_catalogs
    (catalog_id, tenant_id, scope, name, description, status, version,
     created_by, approved_by, published_by, published_at)
VALUES
    ('STARTERCATALOGUE0000000001', NULL, 'NATIONAL', 'ZW Starter Marketplace Catalogue',
     'Indicative starter catalogue: EDLIZ-indicative essential medicines subset and facility equipment/consumables aligned to HPA sourcing categories. Provenance INDICATIVE — not the authoritative EDLIZ/NatPharm master.',
     'PUBLISHED', '1.0.0', 'SYSTEM_SEED', 'SYSTEM_SEED', 'SYSTEM_SEED', now())
ON CONFLICT DO NOTHING;

-- ----------------------------------------------------------------------------
-- Starter catalogue items (115 rows). No prices by design: price is set per
-- vendor listing (msika_listings.price_amount), never in the shared catalogue.
-- ----------------------------------------------------------------------------
INSERT INTO msika_catalog_items
    (item_id, catalog_id, kind, canonical_code, display_name, description,
     tags, restrictions, risk_classification, sourcing_category_code,
     metadata, active, created_by)
VALUES
    ('STARTER0000000000000000001', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-001',
     'Paracetamol 500mg tablets (blister 10x10)',
     'Analgesic/antipyretic tablets, EDLIZ-indicative essential medicine.',
     '{"analgesic","paracetamol","pain","fever"}', '{}', 'LOW_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000002', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-002',
     'Paracetamol 120mg/5ml syrup 100ml',
     'Paediatric analgesic/antipyretic suspension.',
     '{"analgesic","paediatric","syrup","paracetamol"}', '{}', 'LOW_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000003', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-003',
     'Ibuprofen 200mg tablets (blister 10x10)',
     'Non-steroidal anti-inflammatory analgesic tablets.',
     '{"analgesic","nsaid","ibuprofen","pain"}', '{}', 'LOW_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000004', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-004',
     'Acetylsalicylic acid (aspirin) 300mg tablets',
     'Analgesic/antiplatelet tablets.',
     '{"analgesic","aspirin","antiplatelet"}', '{}', 'LOW_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000005', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-005',
     'Oral rehydration salts sachet (WHO formula, 1L)',
     'Low-osmolarity ORS for dehydration management.',
     '{"ors","rehydration","diarrhoea"}', '{}', 'LOW_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000006', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-006',
     'Zinc sulphate 20mg dispersible tablets',
     'Adjunct to ORS in paediatric diarrhoea.',
     '{"zinc","paediatric","diarrhoea"}', '{}', 'LOW_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000007', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-010',
     'Amoxicillin 500mg capsules (blister 10x10)',
     'Broad-spectrum penicillin antibiotic capsules.',
     '{"antibiotic","amoxicillin","penicillin"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000008', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-011',
     'Amoxicillin 125mg/5ml suspension 100ml',
     'Paediatric penicillin antibiotic suspension.',
     '{"antibiotic","paediatric","suspension"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000009', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-012',
     'Benzathine benzylpenicillin 2.4MU injection',
     'Long-acting penicillin for injection.',
     '{"antibiotic","penicillin","injection"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000010', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-013',
     'Benzylpenicillin 5MU powder for injection',
     'Penicillin G powder for reconstitution and injection.',
     '{"antibiotic","penicillin","injection"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000011', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-014',
     'Ceftriaxone 1g powder for injection',
     'Third-generation cephalosporin for injection.',
     '{"antibiotic","cephalosporin","injection"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000012', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-015',
     'Ciprofloxacin 500mg tablets (blister 10x10)',
     'Fluoroquinolone antibiotic tablets.',
     '{"antibiotic","ciprofloxacin","fluoroquinolone"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000013', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-016',
     'Doxycycline 100mg capsules (blister 10x10)',
     'Tetracycline-class antibiotic capsules.',
     '{"antibiotic","doxycycline"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000014', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-017',
     'Metronidazole 400mg tablets (blister 10x10)',
     'Antiprotozoal/antibacterial tablets.',
     '{"antibiotic","metronidazole","antiprotozoal"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000015', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-018',
     'Metronidazole 500mg/100ml IV infusion',
     'Intravenous metronidazole infusion bottle.',
     '{"antibiotic","iv","infusion","metronidazole"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000016', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-019',
     'Cotrimoxazole 480mg tablets (blister 10x10)',
     'Sulfamethoxazole/trimethoprim combination tablets.',
     '{"antibiotic","cotrimoxazole"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000017', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-020',
     'Erythromycin 250mg tablets (blister 10x10)',
     'Macrolide antibiotic tablets.',
     '{"antibiotic","macrolide","erythromycin"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000018', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-021',
     'Gentamicin 80mg/2ml injection (amp x10)',
     'Aminoglycoside antibiotic ampoules.',
     '{"antibiotic","gentamicin","injection"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000019', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-022',
     'Azithromycin 500mg tablets (blister 1x3)',
     'Macrolide antibiotic tablets.',
     '{"antibiotic","azithromycin","macrolide"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000020', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-030',
     'Sodium chloride 0.9% IV infusion 1000ml',
     'Normal saline intravenous infusion bag.',
     '{"iv fluid","saline","infusion"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000021', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-031',
     'Compound sodium lactate (Ringer''s lactate) 1000ml',
     'Balanced crystalloid intravenous infusion bag.',
     '{"iv fluid","ringers lactate","infusion"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000022', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-032',
     'Dextrose 5% IV infusion 1000ml',
     'Isotonic glucose intravenous infusion bag.',
     '{"iv fluid","dextrose","infusion"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000023', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-033',
     'Dextrose 50% injection 50ml',
     'Hypertonic glucose for emergency hypoglycaemia management.',
     '{"iv fluid","dextrose","emergency","hypoglycaemia"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000024', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-034',
     'Water for injection 10ml (amp x50)',
     'Sterile diluent ampoules for reconstitution.',
     '{"diluent","injection","water for injection"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000025', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-040',
     'Adrenaline (epinephrine) 1mg/1ml injection (amp x10)',
     'Emergency-tray drug for anaphylaxis and cardiac arrest.',
     '{"emergency","adrenaline","anaphylaxis","resuscitation"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000026', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-041',
     'Hydrocortisone 100mg powder for injection (vial x10)',
     'Emergency-tray corticosteroid for injection.',
     '{"emergency","hydrocortisone","corticosteroid"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000027', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-042',
     'Atropine sulphate 1mg/1ml injection (amp x10)',
     'Emergency-tray anticholinergic ampoules.',
     '{"emergency","atropine","bradycardia"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000028', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-043',
     'Furosemide 20mg/2ml injection (amp x10)',
     'Loop diuretic ampoules for acute pulmonary oedema.',
     '{"emergency","furosemide","diuretic"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000029', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-044',
     'Aminophylline 250mg/10ml injection (amp x10)',
     'Bronchodilator ampoules for severe bronchospasm.',
     '{"emergency","aminophylline","bronchodilator"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000030', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-045',
     'Magnesium sulphate 50% 2ml injection (amp x10)',
     'Emergency ampoules for eclampsia and severe pre-eclampsia.',
     '{"emergency","magnesium sulphate","eclampsia","obstetric"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000031', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-046',
     'Naloxone 0.4mg/1ml injection (amp x10)',
     'Opioid antagonist ampoules for overdose reversal.',
     '{"emergency","naloxone","opioid reversal"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000032', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-047',
     'Oxytocin 10IU/1ml injection (amp x10)',
     'Uterotonic ampoules; cold chain required.',
     '{"emergency","oxytocin","obstetric","cold chain"}', '{"prescription_required": {"enabled": true}, "cold_chain_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000033', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-048',
     'Salbutamol 100mcg metered-dose inhaler',
     'Short-acting bronchodilator inhaler.',
     '{"salbutamol","asthma","inhaler","bronchodilator"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000034', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-049',
     'Salbutamol 5mg/2.5ml nebuliser solution (amp x20)',
     'Bronchodilator nebules for acute asthma.',
     '{"salbutamol","nebuliser","asthma"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000035', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-050',
     'Tranexamic acid 500mg/5ml injection (amp x10)',
     'Antifibrinolytic ampoules for haemorrhage control.',
     '{"emergency","tranexamic acid","haemorrhage"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000036', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-051',
     'Insulin soluble (human) 100IU/ml 10ml vial',
     'Short-acting insulin vial; cold chain required.',
     '{"insulin","diabetes","cold chain"}', '{"prescription_required": {"enabled": true}, "cold_chain_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000037', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-052',
     'Lidocaine 1% injection 20ml vial (x10)',
     'Local anaesthetic vials for minor procedures.',
     '{"local anaesthetic","lidocaine","procedure"}', '{"prescription_required": {"enabled": true}}', 'MODERATE_RISK', 'MEDICINES_GENERAL',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000038', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-060',
     'Morphine sulphate 10mg/1ml injection (amp x10)',
     'Controlled opioid analgesic ampoules (DDA schedule).',
     '{"controlled","opioid","morphine","analgesic","dda"}', '{"prescription_required": {"enabled": true}, "controlled_item": {"enabled": true}}', 'REGULATED', 'CONTROLLED_MEDICINES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000039', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-061',
     'Pethidine 50mg/1ml injection (amp x10)',
     'Controlled opioid analgesic ampoules (DDA schedule).',
     '{"controlled","opioid","pethidine","dda"}', '{"prescription_required": {"enabled": true}, "controlled_item": {"enabled": true}}', 'REGULATED', 'CONTROLLED_MEDICINES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000040', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-062',
     'Midazolam 5mg/5ml injection (amp x10)',
     'Controlled benzodiazepine ampoules for sedation.',
     '{"controlled","benzodiazepine","midazolam","sedation"}', '{"prescription_required": {"enabled": true}, "controlled_item": {"enabled": true}}', 'REGULATED', 'CONTROLLED_MEDICINES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000041', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-063',
     'Diazepam 10mg/2ml injection (amp x10)',
     'Controlled benzodiazepine ampoules; emergency-tray anticonvulsant.',
     '{"controlled","benzodiazepine","diazepam","emergency","seizure"}', '{"prescription_required": {"enabled": true}, "controlled_item": {"enabled": true}}', 'REGULATED', 'CONTROLLED_MEDICINES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000042', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-064',
     'Phenobarbitone 200mg/1ml injection (amp x10)',
     'Controlled barbiturate ampoules for status epilepticus.',
     '{"controlled","barbiturate","phenobarbitone","seizure"}', '{"prescription_required": {"enabled": true}, "controlled_item": {"enabled": true}}', 'REGULATED', 'CONTROLLED_MEDICINES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000043', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-MED-065',
     'Ketamine 50mg/ml 10ml vial',
     'Controlled dissociative anaesthetic vial.',
     '{"controlled","ketamine","anaesthetic"}', '{"prescription_required": {"enabled": true}, "controlled_item": {"enabled": true}}', 'REGULATED', 'CONTROLLED_MEDICINES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000044', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-001',
     'Automated external defibrillator (AED) with adult pads',
     'Semi-automatic external defibrillator for emergency resuscitation.',
     '{"defibrillator","aed","resuscitation","emergency"}', '{"facility_only": {"enabled": true}}', 'MODERATE_RISK', 'EMERGENCY_RESUSCITATION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000045', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-002',
     'Manual resuscitator (bag-valve-mask), adult',
     'Self-inflating adult resuscitation bag with mask and reservoir.',
     '{"ambu bag","resuscitator","bvm","airway"}', '{}', 'LOW_RISK', 'EMERGENCY_RESUSCITATION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000046', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-003',
     'Manual resuscitator (bag-valve-mask), paediatric',
     'Self-inflating paediatric resuscitation bag with masks.',
     '{"ambu bag","paediatric","resuscitator","airway"}', '{}', 'LOW_RISK', 'EMERGENCY_RESUSCITATION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000047', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-004',
     'Laryngoscope set with adult and paediatric blades',
     'Reusable laryngoscope handle with Macintosh blade set.',
     '{"laryngoscope","intubation","airway"}', '{}', 'LOW_RISK', 'EMERGENCY_RESUSCITATION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000048', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-005',
     'Oropharyngeal airway set (sizes 0-4)',
     'Guedel airway set, assorted sizes.',
     '{"airway","guedel","oropharyngeal"}', '{}', 'LOW_RISK', 'EMERGENCY_RESUSCITATION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000049', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-006',
     'Emergency trolley with drug tray and defibrillator shelf',
     'Stainless emergency/crash trolley with lockable drug tray.',
     '{"emergency trolley","crash cart","resuscitation"}', '{}', 'UNRESTRICTED', 'EMERGENCY_RESUSCITATION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000050', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-010',
     'Oxygen cylinder 10L (J-size) with regulator and flowmeter',
     'Refillable medical oxygen cylinder with pressure regulator.',
     '{"oxygen cylinder","oxygen","medical gas"}', '{}', 'LOW_RISK', 'SUCTION_OXYGEN_DELIVERY',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000051', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-011',
     'Oxygen concentrator 5L/min',
     'Mains-powered medical oxygen concentrator.',
     '{"oxygen concentrator","oxygen therapy"}', '{"facility_only": {"enabled": true}}', 'MODERATE_RISK', 'SUCTION_OXYGEN_DELIVERY',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000052', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-012',
     'Portable electric suction machine',
     'Portable suction apparatus with collection jar and tubing.',
     '{"suction machine","aspirator","airway"}', '{"facility_only": {"enabled": true}}', 'MODERATE_RISK', 'SUCTION_OXYGEN_DELIVERY',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000053', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-013',
     'Nasal oxygen cannula, adult (pack of 50)',
     'Single-use adult nasal cannulae.',
     '{"nasal cannula","oxygen","consumable"}', '{}', 'LOW_RISK', 'SUCTION_OXYGEN_DELIVERY',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000054', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-014',
     'Oxygen face mask with tubing, adult (pack of 50)',
     'Single-use medium-concentration oxygen masks.',
     '{"oxygen mask","oxygen","consumable"}', '{}', 'LOW_RISK', 'SUCTION_OXYGEN_DELIVERY',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000055', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-015',
     'Compressor nebuliser machine',
     'Tabletop compressor nebuliser with adult/paediatric kits.',
     '{"nebulizer","nebuliser","respiratory"}', '{}', 'LOW_RISK', 'SUCTION_OXYGEN_DELIVERY',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000056', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-020',
     'Multiparameter patient monitor (ECG/NIBP/SpO2/Temp)',
     'Bedside vital-signs monitor with adult and paediatric accessories.',
     '{"patient monitor","vital signs","ecg","spo2"}', '{"facility_only": {"enabled": true}}', 'MODERATE_RISK', 'PATIENT_MONITORING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000057', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-021',
     'Fingertip pulse oximeter',
     'Portable SpO2 and pulse-rate fingertip oximeter.',
     '{"pulse oximeter","spo2","vital signs"}', '{}', 'LOW_RISK', 'PATIENT_MONITORING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000058', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-022',
     'Digital blood pressure machine, upper arm',
     'Automatic digital sphygmomanometer with adult cuffs.',
     '{"blood pressure","bp machine","vital signs"}', '{}', 'LOW_RISK', 'PATIENT_MONITORING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000059', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-023',
     'Aneroid sphygmomanometer with adult cuff',
     'Manual aneroid blood pressure set.',
     '{"sphygmomanometer","blood pressure","manual"}', '{}', 'LOW_RISK', 'PATIENT_MONITORING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000060', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-024',
     'Digital clinical thermometer (box of 10)',
     'Digital axillary/oral clinical thermometers.',
     '{"thermometer","temperature","vital signs"}', '{}', 'LOW_RISK', 'PATIENT_MONITORING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000061', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-025',
     'Handheld fetal doppler',
     'Portable fetal heart-rate doppler with gel.',
     '{"fetal doppler","obstetric","antenatal"}', '{}', 'LOW_RISK', 'PATIENT_MONITORING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000062', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-030',
     'Dual-head stethoscope',
     'Adult dual-head acoustic stethoscope.',
     '{"stethoscope","diagnostic","examination"}', '{}', 'LOW_RISK', 'DIAGNOSTIC_INSTRUMENTS',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000063', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-031',
     'Diagnostic set (otoscope and ophthalmoscope)',
     'Combined oto/ophthalmoscope diagnostic set with specula.',
     '{"otoscope","ophthalmoscope","diagnostic set"}', '{}', 'LOW_RISK', 'DIAGNOSTIC_INSTRUMENTS',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000064', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-032',
     'Examination penlight torch',
     'Clinical examination torch with pupil gauge.',
     '{"torch","penlight","examination"}', '{}', 'UNRESTRICTED', 'DIAGNOSTIC_INSTRUMENTS',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000065', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-033',
     'Wooden tongue depressors (box of 100)',
     'Single-use wooden tongue depressors.',
     '{"tongue depressor","examination","consumable"}', '{}', 'UNRESTRICTED', 'DIAGNOSTIC_INSTRUMENTS',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000066', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-034',
     'Neurological reflex hammer',
     'Taylor-pattern percussion/reflex hammer.',
     '{"reflex hammer","neurological","examination"}', '{}', 'UNRESTRICTED', 'DIAGNOSTIC_INSTRUMENTS',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000067', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-040',
     'Blood glucose meter kit with lancing device',
     'Point-of-care glucometer starter kit.',
     '{"glucometer","glucose","point of care","diabetes"}', '{}', 'LOW_RISK', 'POINT_OF_CARE_TESTING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000068', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-041',
     'Blood glucose test strips (vial of 50)',
     'Compatible glucometer test strips.',
     '{"glucose strips","point of care","consumable"}', '{}', 'LOW_RISK', 'POINT_OF_CARE_TESTING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000069', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-042',
     'Portable haemoglobin meter kit',
     'Point-of-care haemoglobinometer with microcuvettes.',
     '{"haemoglobin meter","anaemia","point of care"}', '{}', 'LOW_RISK', 'POINT_OF_CARE_TESTING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000070', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-043',
     'Urine test strips, 10-parameter (vial of 100)',
     'Urinalysis reagent strips.',
     '{"urine test","urinalysis","point of care"}', '{}', 'LOW_RISK', 'POINT_OF_CARE_TESTING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000071', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-050',
     'Disposable syringes 5ml Luer slip (box of 100)',
     'Single-use sterile syringes.',
     '{"syringe","injection","consumable"}', '{}', 'LOW_RISK', 'INFUSION_INJECTION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000072', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-051',
     'Hypodermic needles 21G (box of 100)',
     'Single-use sterile hypodermic needles.',
     '{"needles","injection","consumable"}', '{}', 'LOW_RISK', 'INFUSION_INJECTION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000073', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-052',
     'IV cannula 18G with injection port (box of 50)',
     'Sterile peripheral intravenous cannulae.',
     '{"iv cannula","infusion","consumable"}', '{}', 'LOW_RISK', 'INFUSION_INJECTION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000074', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-053',
     'IV administration (giving) sets (box of 50)',
     'Sterile gravity infusion giving sets.',
     '{"giving set","infusion","consumable"}', '{}', 'LOW_RISK', 'INFUSION_INJECTION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000075', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-054',
     'Stainless drip stand, 4-hook mobile',
     'Height-adjustable mobile infusion stand.',
     '{"drip stand","infusion","furniture"}', '{}', 'UNRESTRICTED', 'INFUSION_INJECTION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000076', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-055',
     'Volumetric infusion pump',
     'Programmable volumetric infusion pump with IV set compatibility.',
     '{"infusion pump","volumetric","infusion"}', '{"facility_only": {"enabled": true}}', 'MODERATE_RISK', 'INFUSION_INJECTION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000077', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-060',
     'Sterile gauze swabs 10x10cm (pack of 100)',
     'Absorbent sterile gauze swabs.',
     '{"gauze","dressing","wound care"}', '{}', 'LOW_RISK', 'WOUND_CARE_CONSUMABLES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000078', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-061',
     'Crepe bandage 10cm x 4.5m (pack of 12)',
     'Elasticated crepe bandages.',
     '{"bandage","crepe","wound care"}', '{}', 'UNRESTRICTED', 'WOUND_CARE_CONSUMABLES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000079', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-062',
     'Surgical adhesive tape 2.5cm (pack of 12)',
     'Hypoallergenic surgical tape rolls.',
     '{"tape","dressing","wound care"}', '{}', 'UNRESTRICTED', 'WOUND_CARE_CONSUMABLES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000080', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-063',
     'Sterile suture pack with instruments',
     'Single-use suture pack: needle holder, forceps, scissors, drape.',
     '{"suture","procedure pack","wound care"}', '{}', 'LOW_RISK', 'WOUND_CARE_CONSUMABLES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000081', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-070',
     'Foley catheter 16FR 2-way (box of 10)',
     'Sterile latex Foley urinary catheters.',
     '{"catheter","foley","urology","consumable"}', '{}', 'LOW_RISK', 'CLINICAL_CONSUMABLES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000082', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-071',
     'Urine drainage bags 2000ml (box of 10)',
     'Sterile urine collection bags with non-return valve.',
     '{"urine bag","drainage","consumable"}', '{}', 'LOW_RISK', 'CLINICAL_CONSUMABLES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000083', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-072',
     'Sterile lubricating jelly 42g tube (box of 12)',
     'Water-soluble sterile lubricant.',
     '{"lubricant","jelly","consumable"}', '{}', 'UNRESTRICTED', 'CLINICAL_CONSUMABLES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000084', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-080',
     'Nitrile examination gloves, medium (box of 100)',
     'Powder-free single-use nitrile examination gloves.',
     '{"gloves","ppe","nitrile","examination"}', '{}', 'UNRESTRICTED', 'PPE_PROTECTIVE_WEAR',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000085', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-081',
     'Sterile surgical gloves size 7.5 (box of 50 pairs)',
     'Sterile powder-free latex surgical gloves.',
     '{"surgical gloves","ppe","sterile"}', '{}', 'LOW_RISK', 'PPE_PROTECTIVE_WEAR',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000086', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-082',
     'Disposable plastic aprons (roll of 200)',
     'Single-use polyethylene aprons.',
     '{"apron","ppe","disposable"}', '{}', 'UNRESTRICTED', 'PPE_PROTECTIVE_WEAR',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000087', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-083',
     'N95/FFP2 particulate respirators (box of 20)',
     'Filtering facepiece respirators.',
     '{"respirator","n95","ppe","mask"}', '{}', 'UNRESTRICTED', 'PPE_PROTECTIVE_WEAR',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000088', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-084',
     'Reusable face shields (pack of 10)',
     'Full-face anti-splash visors.',
     '{"face shield","ppe","visor"}', '{}', 'UNRESTRICTED', 'PPE_PROTECTIVE_WEAR',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000089', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-090',
     'Benchtop autoclave 23L class B',
     'Steam sterilizer for instrument reprocessing.',
     '{"autoclave","sterilizer","sterilisation"}', '{"facility_only": {"enabled": true}}', 'MODERATE_RISK', 'STERILISATION_DISINFECTION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000090', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-091',
     'Chlorine-based disinfectant concentrate 5L',
     'Surface and equipment disinfectant concentrate.',
     '{"disinfectant","chlorine","cleaning"}', '{}', 'UNRESTRICTED', 'STERILISATION_DISINFECTION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000091', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-092',
     'Antiseptic surgical scrub solution 500ml (chlorhexidine 4%)',
     'Antiseptic hand and skin scrub.',
     '{"antiseptic","scrub","chlorhexidine"}', '{}', 'UNRESTRICTED', 'STERILISATION_DISINFECTION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000092', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-093',
     'Self-seal sterilisation pouches 90x260mm (box of 200)',
     'Steam-indicator sterilisation pouches.',
     '{"sterilisation pouch","autoclave","consumable"}', '{}', 'UNRESTRICTED', 'STERILISATION_DISINFECTION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000093', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-100',
     'Liquid hand soap 5L refill',
     'Institutional liquid soap refill.',
     '{"liquid soap","hand hygiene"}', '{}', 'UNRESTRICTED', 'HAND_HYGIENE_SUPPLIES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000094', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-101',
     'Interfold paper hand towels (case of 20 packs)',
     'Single-use paper towels for hand drying.',
     '{"paper towels","hand hygiene"}', '{}', 'UNRESTRICTED', 'HAND_HYGIENE_SUPPLIES',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000095', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-110',
     'Foot-operated pedal bin 20L',
     'Stainless pedal-operated waste bin.',
     '{"pedal bin","waste","bin"}', '{}', 'UNRESTRICTED', 'WASTE_MANAGEMENT',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000096', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-111',
     'Colour-coded waste bin liners (red/yellow/black, roll of 100)',
     'Healthcare waste-segregation bin liners.',
     '{"bin liners","waste segregation"}', '{}', 'UNRESTRICTED', 'WASTE_MANAGEMENT',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000097', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-120',
     'Sharps containers 5L (box of 10)',
     'Puncture-resistant sharps disposal containers.',
     '{"sharps box","sharps container","clinical waste"}', '{}', 'UNRESTRICTED', 'SHARPS_CLINICAL_WASTE',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000098', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-121',
     'Biohazard autoclavable waste bags (roll of 100)',
     'Yellow biohazard-marked clinical waste bags.',
     '{"biohazard bags","clinical waste"}', '{}', 'UNRESTRICTED', 'SHARPS_CLINICAL_WASTE',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000099', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-130',
     'Examination couch, 2-section with paper-roll holder',
     'Padded clinical examination couch.',
     '{"examination couch","furniture","clinic"}', '{}', 'UNRESTRICTED', 'CLINICAL_FURNITURE',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000100', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-131',
     'Hospital bed, 2-crank manual with side rails',
     'Manual two-function hospital bed with mattress.',
     '{"hospital bed","furniture","ward"}', '{}', 'UNRESTRICTED', 'CLINICAL_FURNITURE',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000101', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-132',
     'Bedside locker, stainless top',
     'Patient bedside cabinet.',
     '{"bedside locker","furniture","ward"}', '{}', 'UNRESTRICTED', 'CLINICAL_FURNITURE',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000102', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-133',
     'Stainless dressing trolley, 2-shelf',
     'Mobile dressing/instrument trolley.',
     '{"dressing trolley","trolley","furniture"}', '{}', 'UNRESTRICTED', 'CLINICAL_FURNITURE',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000103', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-134',
     'Mobile privacy screen, 3-fold',
     'Folding ward privacy screen on castors.',
     '{"privacy screen","screen","furniture"}', '{}', 'UNRESTRICTED', 'CLINICAL_FURNITURE',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000104', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-140',
     'Lockable wall-mounted medicine cupboard',
     'Double-lock steel medicine storage cupboard (supplied unstocked).',
     '{"medicine cupboard","lockable","secure storage"}', '{}', 'UNRESTRICTED', 'SECURE_STORAGE',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000105', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-150',
     'Vaccine refrigerator 100L (ice-lined)',
     'Purpose-built vaccine/medicine refrigerator with temperature display.',
     '{"vaccine refrigerator","cold chain","fridge"}', '{"facility_only": {"enabled": true}}', 'MODERATE_RISK', 'REFRIGERATION_COLD_CHAIN',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000106', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-151',
     'Min-max fridge thermometer',
     'Refrigerator thermometer with min/max memory.',
     '{"fridge thermometer","cold chain","temperature"}', '{}', 'UNRESTRICTED', 'REFRIGERATION_COLD_CHAIN',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000107', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-152',
     'Vaccine cold box with ice packs (long-range)',
     'Insulated vaccine carrier with conditioning ice packs.',
     '{"cold box","cold chain","vaccine carrier"}', '{}', 'UNRESTRICTED', 'REFRIGERATION_COLD_CHAIN',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000108', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-160',
     'LED mobile examination lamp',
     'Height-adjustable LED examination light on castors.',
     '{"examination lamp","led","lighting"}', '{}', 'UNRESTRICTED', 'MEDICAL_LIGHTING',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000109', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-170',
     'Standard folding wheelchair, adult',
     'Self-propelled folding wheelchair.',
     '{"wheelchair","mobility","patient transport"}', '{}', 'UNRESTRICTED', 'PATIENT_TRANSPORT_MOBILITY',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000110', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-171',
     'Folding emergency stretcher',
     'Aluminium folding stretcher with carry handles.',
     '{"stretcher","patient transport","emergency"}', '{}', 'UNRESTRICTED', 'PATIENT_TRANSPORT_MOBILITY',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000111', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-172',
     'Spinal board with straps and head immobiliser',
     'Rigid long spinal board with immobilisation set.',
     '{"spinal board","trauma","immobilisation"}', '{}', 'LOW_RISK', 'PATIENT_TRANSPORT_MOBILITY',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000112', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-180',
     'Adult mechanical column scale with height rod',
     'Clinic scale with stadiometer.',
     '{"weighing scale","stadiometer","anthropometry"}', '{}', 'UNRESTRICTED', 'ANTHROPOMETRY_NUTRITION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000113', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-181',
     'Infant weighing scale, pan type',
     'Mechanical baby scale, 25g graduation.',
     '{"baby scale","infant","anthropometry"}', '{}', 'UNRESTRICTED', 'ANTHROPOMETRY_NUTRITION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000114', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-182',
     'MUAC tapes, adult and child (pack of 50)',
     'Mid-upper-arm-circumference screening tapes.',
     '{"muac","nutrition","screening"}', '{}', 'UNRESTRICTED', 'ANTHROPOMETRY_NUTRITION',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED'),
    ('STARTER0000000000000000115', 'STARTERCATALOGUE0000000001', 'PRODUCT', 'ZW-STARTER-EQP-190',
     'Dry chemical powder fire extinguisher 4.5kg',
     'ABC-rated serviced fire extinguisher with wall bracket.',
     '{"fire extinguisher","fire safety"}', '{}', 'UNRESTRICTED', 'FIRE_SAFETY_EQUIPMENT',
     '{"provenance": "INDICATIVE", "source": "ZW starter catalogue seed (V008)", "status": "STARTER_SEED_NOT_AUTHORITATIVE", "pricing": "VENDOR_LISTING_LEVEL"}', TRUE, 'SYSTEM_SEED')
ON CONFLICT DO NOTHING;
