{{- if .Values.previewSecrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-preview-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.previewSecrets.keycloakAdminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.previewSecrets.keycloakAdminPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-preview-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.previewSecrets.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.previewSecrets.minioRootPassword | quote }}
{{- end }}
