server:
  port: ${SERVER_PORT:8371}

spring:
  application:
    name: schema-registry-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:impilo_schema_registry}
    username: ${DB_USER:impilo}
    password: ${DB_PASS:impilo}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

impilo:
  companion:
    enabled: true
