-- ============================================================================
-- V023: Virtual service registry seed — GENERATED FILE, DO NOT EDIT BY HAND.
--
-- Generated by tools/generate-virtual-service-seed.mjs from the canonical
-- operating-model document contracts/telemedicine/virtual-hospitals.json.
-- Re-run the generator and check in the result when the document changes.
--
-- Entities: 21 (all seeded CONFIGURED — activation is a governed,
-- fail-closed runtime transition, never a seed default). Routing seams for the
-- entries already routable via existing teleconsult substrate seed active=TRUE.
-- Queue definitions seed WITHOUT SLA values (governed configuration only).
-- ============================================================================

-- ---- vh-national-telemedicine: National Telemedicine Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-national-telemedicine',
    '00000000-0000-0000-0000-000000000001',
    'National Telemedicine Hospital',
    'NATIONAL',
    'NETWORKED',
    'MoHCC (national)',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Countrywide telemedicine coordination, national specialist support, overflow support, quality monitoring, and national service continuity.',
    'National — all provinces, all levels of care',
    NULL,
    TRUE,
    '["PROVIDER_TO_PROVIDER_ADVICE_ONLY","MDT_ONLY","BLOCKED_PENDING_REGULATORY_APPROVAL"]'::jsonb,
    '["PUBLIC_SERVICE","PROGRAMME_FUNDED","EMERGENCY_DISASTER_FREE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice","emergency-advisory","mdt-case-review"]'::jsonb,
    '["Telemedicine triage providers","Medical officers","Nurses/midwives","Specialists","Diagnostics reviewers","Mental health providers","Supervisors","Helpdesk agents"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'General teleconsultation', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-national-telemedicine' AND l.name = 'General teleconsultation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-national-telemedicine' AND l.name = 'Facility support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Specialist escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-national-telemedicine' AND l.name = 'Specialist escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Emergency overflow', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-national-telemedicine' AND l.name = 'Emergency overflow');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Remote monitoring review', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-national-telemedicine' AND l.name = 'Remote monitoring review');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Quality & audit monitoring', 5 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-national-telemedicine' AND l.name = 'Quality & audit monitoring');
INSERT INTO tuso.virtual_service_routing_seam (virtual_service_id, routing_type, target_ref, note, active) SELECT id, 'SPECIALTY_POOL', 'GENERAL_TELEMEDICINE', 'Reachable today as a teleconsult SPECIALTY_POOL routing target (real BFF-validated path).', TRUE FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' ON CONFLICT (virtual_service_id, routing_type, target_ref) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'national-general-teleconsult', 'National General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-support', 'Facility Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'specialist-escalation', 'Specialist Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'emergency-overflow', 'Emergency Overflow Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'remote-monitoring-review', 'Remote Monitoring Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'missed-failed-session', 'Missed/Failed Session Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-national-telemedicine' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-specialist: Virtual Specialist Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-specialist',
    '00000000-0000-0000-0000-000000000001',
    'Virtual Specialist Hospital',
    'SPECIALIST',
    'NETWORKED',
    'MoHCC with central hospital specialist base',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Specialist-care virtual institution: provider-to-provider consultation, specialist teleconsults, MDT reviews, complex case review, procedure support, specialist follow-up.',
    'National, provincial spokes',
    NULL,
    TRUE,
    '["PROVIDER_TO_PROVIDER_ADVICE_ONLY","MDT_ONLY","TEACHING_SUPERVISION_ONLY","BLOCKED_PENDING_REGULATORY_APPROVAL"]'::jsonb,
    '["PUBLIC_SERVICE","MEDICAL_AID_REIMBURSED","PRIVATE_SELF_PAY"]'::jsonb,
    '["provider-to-provider-advice","mdt-case-review","case-presentation","diagnostics-review"]'::jsonb,
    '["Specialists","Medical officers","Supervisors"]'::jsonb,
    '["REQUESTER","REFERRAL_DESTINATION","HOST_FACILITY","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Internal medicine', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-specialist' AND l.name = 'Internal medicine');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Surgery', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-specialist' AND l.name = 'Surgery');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Paediatrics', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-specialist' AND l.name = 'Paediatrics');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Obstetrics & gynaecology', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-specialist' AND l.name = 'Obstetrics & gynaecology');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Anaesthesia', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-specialist' AND l.name = 'Anaesthesia');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Psychiatry', 5 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-specialist' AND l.name = 'Psychiatry');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Radiology/diagnostics', 6 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-specialist' AND l.name = 'Radiology/diagnostics');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Rehabilitation medicine', 7 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-specialist' AND l.name = 'Rehabilitation medicine');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Infectious diseases', 8 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-specialist' AND l.name = 'Infectious diseases');
INSERT INTO tuso.virtual_service_routing_seam (virtual_service_id, routing_type, target_ref, note, active) SELECT id, 'SPECIALTY_POOL', 'SPECIALIST_POOL', 'Reachable today as a teleconsult SPECIALTY_POOL routing target (real BFF-validated path).', TRUE FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' ON CONFLICT (virtual_service_id, routing_type, target_ref) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'specialist-request', 'General Specialist Request Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'p2p-advice', 'Provider-to-Provider Advice Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'mdt-review', 'MDT Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'procedure-support', 'Procedure/Theatre Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'urgent-escalation', 'Urgent Specialist Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-specialist' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-maternal-newborn: Virtual Maternal and Newborn Unit ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-maternal-newborn',
    '00000000-0000-0000-0000-000000000001',
    'Virtual Maternal and Newborn Unit',
    'PROGRAMME',
    'PROGRAMME_OWNED',
    'MoHCC maternal & newborn health programme',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Maternal, newborn, pregnancy, postnatal, midwifery, neonatal and high-risk follow-up services with danger-sign escalation.',
    'National programme, facility spokes',
    NULL,
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE","PROGRAMME_FUNDED","DONOR_PARTNER_SUPPORTED"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice","emergency-advisory"]'::jsonb,
    '["Midwives","Obstetricians","Neonatologists","Medical officers"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'ANC teleconsultation', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-maternal-newborn' AND l.name = 'ANC teleconsultation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'PNC follow-up', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-maternal-newborn' AND l.name = 'PNC follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'High-risk pregnancy monitoring', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-maternal-newborn' AND l.name = 'High-risk pregnancy monitoring');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Neonatal review', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-maternal-newborn' AND l.name = 'Neonatal review');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Midwife-to-doctor escalation', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-maternal-newborn' AND l.name = 'Midwife-to-doctor escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Emergency obstetric advisory', 5 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-maternal-newborn' AND l.name = 'Emergency obstetric advisory');
INSERT INTO tuso.virtual_service_routing_seam (virtual_service_id, routing_type, target_ref, note, active) SELECT id, 'SPECIALTY_POOL', 'MATERNAL_NEWBORN', 'Reachable today as a teleconsult SPECIALTY_POOL routing target (real BFF-validated path).', TRUE FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' ON CONFLICT (virtual_service_id, routing_type, target_ref) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'anc-teleconsult', 'ANC Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'pnc-followup', 'PNC Follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'high-risk-pregnancy', 'High-Risk Pregnancy Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'neonatal-review', 'Neonatal Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'emergency-obstetric', 'Emergency Obstetric/Newborn Advisory Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-maternal-newborn' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-mental-health: Virtual Mental Health Unit ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-mental-health',
    '00000000-0000-0000-0000-000000000001',
    'Virtual Mental Health Unit',
    'PROGRAMME',
    'PROGRAMME_OWNED',
    'MoHCC mental health programme',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Counselling, psychiatric review, follow-up, crisis routing, medication review, psychosocial support and continuity of care — with sensitive-case governance.',
    'National programme',
    NULL,
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE","PROGRAMME_FUNDED"]'::jsonb,
    '["direct-clinical-encounter","emergency-advisory","case-notes-review"]'::jsonb,
    '["Psychiatrists","Psychologists","Counsellors","Mental health nurses"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Counselling', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-mental-health' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-mental-health' AND l.name = 'Counselling');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Psychiatric review', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-mental-health' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-mental-health' AND l.name = 'Psychiatric review');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Crisis escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-mental-health' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-mental-health' AND l.name = 'Crisis escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Medication review', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-mental-health' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-mental-health' AND l.name = 'Medication review');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Follow-up/continuity', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-mental-health' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-mental-health' AND l.name = 'Follow-up/continuity');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'mh-teleconsult', 'General Mental Health Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-mental-health' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'counselling', 'Counselling Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-mental-health' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'psychiatric-review', 'Psychiatric Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-mental-health' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'crisis-escalation', 'Crisis/Urgent Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-mental-health' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'medication-review', 'Medication Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-mental-health' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-chronic-disease: Virtual Chronic Disease Clinic ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-chronic-disease',
    '00000000-0000-0000-0000-000000000001',
    'Virtual Chronic Disease Clinic',
    'PROGRAMME',
    'PROGRAMME_OWNED',
    'MoHCC NCD programme',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Long-term condition management: medication follow-up, adherence support, results review, monitoring and continuity of care.',
    'National programme',
    NULL,
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE","MEDICAL_AID_REIMBURSED","SUBSCRIPTION_CONTINUITY_CARE"]'::jsonb,
    '["direct-clinical-encounter","diagnostics-review"]'::jsonb,
    '["Medical officers","Nurses","Pharmacy advisers"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","DISPENSING_SITE"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Hypertension', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-chronic-disease' AND l.name = 'Hypertension');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Diabetes', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-chronic-disease' AND l.name = 'Diabetes');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Asthma/COPD', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-chronic-disease' AND l.name = 'Asthma/COPD');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Epilepsy', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-chronic-disease' AND l.name = 'Epilepsy');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Medication adherence', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-chronic-disease' AND l.name = 'Medication adherence');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Results review', 5 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-chronic-disease' AND l.name = 'Results review');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'ncd-followup', 'NCD Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'results-review', 'Results Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'medication-review', 'Medication Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'abnormal-observation', 'Abnormal Observation Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'missed-followup', 'Missed Follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-chronic-disease' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-radiology-diagnostics: Virtual Radiology/Diagnostics Review Centre ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-radiology-diagnostics',
    '00000000-0000-0000-0000-000000000001',
    'Virtual Radiology/Diagnostics Review Centre',
    'SPECIALIST',
    'NETWORKED',
    'MoHCC diagnostics network',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Remote interpretation, imaging/lab review, diagnostic escalation, PACS/DICOM-linked case review and specialist diagnostic recommendations.',
    'National, hub-and-spoke',
    NULL,
    TRUE,
    '["PROVIDER_TO_PROVIDER_ADVICE_ONLY","MDT_ONLY","BLOCKED_PENDING_REGULATORY_APPROVAL"]'::jsonb,
    '["PUBLIC_SERVICE","MEDICAL_AID_REIMBURSED"]'::jsonb,
    '["diagnostics-review","mdt-case-review","provider-to-provider-advice"]'::jsonb,
    '["Radiologists","Pathologists","Diagnostics reviewers"]'::jsonb,
    '["REQUESTER","DIAGNOSTICS_SITE","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Imaging review', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-radiology-diagnostics' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-radiology-diagnostics' AND l.name = 'Imaging review');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Radiology opinion', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-radiology-diagnostics' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-radiology-diagnostics' AND l.name = 'Radiology opinion');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Lab result interpretation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-radiology-diagnostics' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-radiology-diagnostics' AND l.name = 'Lab result interpretation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Diagnostic MDT', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-radiology-diagnostics' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-radiology-diagnostics' AND l.name = 'Diagnostic MDT');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility diagnostic support', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-radiology-diagnostics' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-radiology-diagnostics' AND l.name = 'Facility diagnostic support');
INSERT INTO tuso.virtual_service_routing_seam (virtual_service_id, routing_type, target_ref, note, active) SELECT id, 'SPECIALTY_POOL', 'RADIOLOGY_DIAGNOSTICS', 'Reachable today as a teleconsult SPECIALTY_POOL routing target (real BFF-validated path).', TRUE FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-radiology-diagnostics' ON CONFLICT (virtual_service_id, routing_type, target_ref) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'imaging-review', 'Imaging Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-radiology-diagnostics' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'urgent-imaging', 'Urgent Imaging Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-radiology-diagnostics' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'lab-interpretation', 'Lab Interpretation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-radiology-diagnostics' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'diagnostic-mdt', 'Diagnostic MDT Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-radiology-diagnostics' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-icu-support: Virtual ICU Support Desk ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-icu-support',
    '00000000-0000-0000-0000-000000000001',
    'Virtual ICU Support Desk',
    'SPECIALIST',
    'NETWORKED',
    'MoHCC critical care network',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'High-acuity remote support: ICU, HDU, ward deterioration, emergency stabilisation, post-operative critical support.',
    'National, facility spokes',
    NULL,
    TRUE,
    '["EMERGENCY_ADVISORY_ONLY","BLOCKED_PENDING_REGULATORY_APPROVAL"]'::jsonb,
    '["PUBLIC_SERVICE","EMERGENCY_DISASTER_FREE"]'::jsonb,
    '["emergency-advisory","hybrid-encounter-support","provider-to-provider-advice"]'::jsonb,
    '["Intensivists","Anaesthetists","Critical care nurses"]'::jsonb,
    '["REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Urgent ICU support', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-icu-support' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-icu-support' AND l.name = 'Urgent ICU support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Ward deterioration escalation', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-icu-support' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-icu-support' AND l.name = 'Ward deterioration escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Critical care advice', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-icu-support' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-icu-support' AND l.name = 'Critical care advice');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Post-op critical review', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-icu-support' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-icu-support' AND l.name = 'Post-op critical review');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'urgent-icu', 'Urgent ICU Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-icu-support' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'ward-deterioration', 'Ward Deterioration Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-icu-support' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'critical-advice', 'Critical Care Advice Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-icu-support' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-emergency-advisory: Virtual Emergency Advisory Unit ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-emergency-advisory',
    '00000000-0000-0000-0000-000000000001',
    'Virtual Emergency Advisory Unit',
    'EMERGENCY',
    'EMERGENCY_ACTIVATED',
    'MoHCC emergency care / Daidzai coordination',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Rapid-response telemedicine: urgent triage, emergency advice, referral routing, dispatch support, facility escalation with SLA timers.',
    'National, 24/7 when activated',
    NULL,
    TRUE,
    '["EMERGENCY_ADVISORY_ONLY","BLOCKED_PENDING_REGULATORY_APPROVAL"]'::jsonb,
    '["EMERGENCY_DISASTER_FREE","PUBLIC_SERVICE"]'::jsonb,
    '["emergency-advisory","hybrid-encounter-support"]'::jsonb,
    '["Emergency physicians","Medical officers","Triage nurses"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Emergency tele-triage', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-emergency-advisory' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-emergency-advisory' AND l.name = 'Emergency tele-triage');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility emergency advice', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-emergency-advisory' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-emergency-advisory' AND l.name = 'Facility emergency advice');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Transfer/referral escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-emergency-advisory' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-emergency-advisory' AND l.name = 'Transfer/referral escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Post-emergency follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-emergency-advisory' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-emergency-advisory' AND l.name = 'Post-emergency follow-up');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'emergency-tele-triage', 'Emergency Tele-triage Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-emergency-advisory' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-emergency-advice', 'Facility Emergency Advice Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-emergency-advisory' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'transfer-escalation', 'Transfer/Referral Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-emergency-advisory' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'unanswered-emergency', 'Unanswered Emergency Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-emergency-advisory' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-rehabilitation: Virtual Rehabilitation Clinic ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-rehabilitation',
    '00000000-0000-0000-0000-000000000001',
    'Virtual Rehabilitation Clinic',
    'PROGRAMME',
    'PROGRAMME_OWNED',
    'MoHCC rehabilitation programme',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Rehabilitation, physiotherapy, occupational therapy, speech therapy, assistive-device follow-up and functional recovery monitoring.',
    'National programme',
    NULL,
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE","MEDICAL_AID_REIMBURSED"]'::jsonb,
    '["direct-clinical-encounter"]'::jsonb,
    '["Physiotherapists","Occupational therapists","Speech therapists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Physiotherapy follow-up', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-rehabilitation' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-rehabilitation' AND l.name = 'Physiotherapy follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Occupational therapy', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-rehabilitation' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-rehabilitation' AND l.name = 'Occupational therapy');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Speech/swallow review', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-rehabilitation' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-rehabilitation' AND l.name = 'Speech/swallow review');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Post-stroke rehab', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-rehabilitation' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-rehabilitation' AND l.name = 'Post-stroke rehab');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Assistive device review', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-rehabilitation' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-rehabilitation' AND l.name = 'Assistive device review');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'physio-followup', 'Physiotherapy Follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-rehabilitation' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'ot', 'Occupational Therapy Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-rehabilitation' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'post-stroke', 'Post-Stroke Rehab Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-rehabilitation' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'assistive-device', 'Assistive Device Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-rehabilitation' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-community-followup: Virtual Community Follow-up Unit ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-community-followup',
    '00000000-0000-0000-0000-000000000001',
    'Virtual Community Follow-up Unit',
    'COMMUNITY',
    'PROGRAMME_OWNED',
    'MoHCC community health / CHW programme',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Community-based care: CHW-supported follow-up, home monitoring, defaulter tracing, outreach continuity, facility-community linkage.',
    'National, district/community spokes',
    NULL,
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE","PROGRAMME_FUNDED","DONOR_PARTNER_SUPPORTED"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["CHWs","Community nurses","Follow-up coordinators"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'CHW follow-up', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-community-followup' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-community-followup' AND l.name = 'CHW follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Home-based care monitoring', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-community-followup' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-community-followup' AND l.name = 'Home-based care monitoring');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Missed appointment tracing', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-community-followup' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-community-followup' AND l.name = 'Missed appointment tracing');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Community escalation', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-community-followup' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-community-followup' AND l.name = 'Community escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-community-followup' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-community-followup' AND l.name = 'Facility handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'chw-followup', 'CHW Follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-community-followup' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'home-monitoring', 'Home-Based Care Monitoring Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-community-followup' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'missed-appointment', 'Missed Appointment Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-community-followup' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-handover', 'Facility Handover Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-community-followup' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-learning-supervision: Virtual Learning and Supervision Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-learning-supervision',
    '00000000-0000-0000-0000-000000000001',
    'Virtual Learning and Supervision Hospital',
    'LEARNING',
    'NETWORKED',
    'MoHCC training directorate with Fundo',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Governed virtual teaching, mentorship, supervision, case review and CPD — never uncontrolled recording or casual observation of patients.',
    'National',
    NULL,
    TRUE,
    '["TEACHING_SUPERVISION_ONLY","BLOCKED_PENDING_REGULATORY_APPROVAL"]'::jsonb,
    '["TEACHING_SUPERVISION_FUNDED","PUBLIC_SERVICE"]'::jsonb,
    '["teaching-supervision","case-presentation","audit-mortality-review"]'::jsonb,
    '["Supervisors","Mentors","Learners (restricted roles)"]'::jsonb,
    '["REQUESTER","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Supervised clinical sessions', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-learning-supervision' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-learning-supervision' AND l.name = 'Supervised clinical sessions');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Case review', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-learning-supervision' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-learning-supervision' AND l.name = 'Case review');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'MDT teaching', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-learning-supervision' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-learning-supervision' AND l.name = 'MDT teaching');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Procedure observation', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-learning-supervision' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-learning-supervision' AND l.name = 'Procedure observation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Learning artefact governance', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-learning-supervision' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-learning-supervision' AND l.name = 'Learning artefact governance');
INSERT INTO tuso.virtual_service_routing_seam (virtual_service_id, routing_type, target_ref, note, active) SELECT id, 'SPECIALTY_POOL', 'LEARNING_SUPERVISION', 'LEARNING_LIVE session template exists (W0); supervision requests routable as teleconsults today.', TRUE FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-learning-supervision' ON CONFLICT (virtual_service_id, routing_type, target_ref) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'supervision-request', 'Supervision Request Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-learning-supervision' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'teaching-session', 'Teaching Session Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-learning-supervision' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'case-review', 'Case Review Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-learning-supervision' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'artefact-approval', 'Learning Artefact Approval Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-learning-supervision' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-provincial-zw-ha: Harare Provincial Virtual Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-provincial-zw-ha',
    '00000000-0000-0000-0000-000000000001',
    'Harare Provincial Virtual Hospital',
    'PROVINCIAL',
    'NETWORKED',
    'Harare provincial health authority',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Decentralised telemedicine operations: local facility support, provincial clinical routing, provincial virtual queues and management.',
    'Harare province — linked districts and facilities',
    'ZW-HA',
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["Medical officers","Nurses","Provincial specialists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial general teleconsult', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ha' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ha' AND l.name = 'Provincial general teleconsult');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility-to-province support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ha' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ha' AND l.name = 'Facility-to-province support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'District escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ha' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ha' AND l.name = 'District escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial tele-follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ha' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ha' AND l.name = 'Provincial tele-follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Referral handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ha' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ha' AND l.name = 'Referral handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-general', 'Provincial General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ha' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-to-province', 'Facility-to-Province Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ha' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'district-escalation', 'District Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ha' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-followup', 'Provincial Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ha' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-provincial-zw-bu: Bulawayo Provincial Virtual Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-provincial-zw-bu',
    '00000000-0000-0000-0000-000000000001',
    'Bulawayo Provincial Virtual Hospital',
    'PROVINCIAL',
    'NETWORKED',
    'Bulawayo provincial health authority',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Decentralised telemedicine operations: local facility support, provincial clinical routing, provincial virtual queues and management.',
    'Bulawayo province — linked districts and facilities',
    'ZW-BU',
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["Medical officers","Nurses","Provincial specialists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial general teleconsult', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-bu' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-bu' AND l.name = 'Provincial general teleconsult');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility-to-province support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-bu' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-bu' AND l.name = 'Facility-to-province support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'District escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-bu' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-bu' AND l.name = 'District escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial tele-follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-bu' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-bu' AND l.name = 'Provincial tele-follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Referral handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-bu' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-bu' AND l.name = 'Referral handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-general', 'Provincial General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-bu' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-to-province', 'Facility-to-Province Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-bu' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'district-escalation', 'District Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-bu' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-followup', 'Provincial Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-bu' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-provincial-zw-ma: Manicaland Provincial Virtual Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-provincial-zw-ma',
    '00000000-0000-0000-0000-000000000001',
    'Manicaland Provincial Virtual Hospital',
    'PROVINCIAL',
    'NETWORKED',
    'Manicaland provincial health authority',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Decentralised telemedicine operations: local facility support, provincial clinical routing, provincial virtual queues and management.',
    'Manicaland province — linked districts and facilities',
    'ZW-MA',
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["Medical officers","Nurses","Provincial specialists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial general teleconsult', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ma' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ma' AND l.name = 'Provincial general teleconsult');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility-to-province support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ma' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ma' AND l.name = 'Facility-to-province support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'District escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ma' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ma' AND l.name = 'District escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial tele-follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ma' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ma' AND l.name = 'Provincial tele-follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Referral handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ma' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ma' AND l.name = 'Referral handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-general', 'Provincial General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ma' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-to-province', 'Facility-to-Province Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ma' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'district-escalation', 'District Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ma' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-followup', 'Provincial Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ma' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-provincial-zw-mc: Mashonaland Central Provincial Virtual Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-provincial-zw-mc',
    '00000000-0000-0000-0000-000000000001',
    'Mashonaland Central Provincial Virtual Hospital',
    'PROVINCIAL',
    'NETWORKED',
    'Mashonaland Central provincial health authority',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Decentralised telemedicine operations: local facility support, provincial clinical routing, provincial virtual queues and management.',
    'Mashonaland Central province — linked districts and facilities',
    'ZW-MC',
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["Medical officers","Nurses","Provincial specialists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial general teleconsult', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mc' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mc' AND l.name = 'Provincial general teleconsult');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility-to-province support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mc' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mc' AND l.name = 'Facility-to-province support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'District escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mc' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mc' AND l.name = 'District escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial tele-follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mc' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mc' AND l.name = 'Provincial tele-follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Referral handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mc' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mc' AND l.name = 'Referral handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-general', 'Provincial General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mc' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-to-province', 'Facility-to-Province Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mc' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'district-escalation', 'District Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mc' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-followup', 'Provincial Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mc' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-provincial-zw-me: Mashonaland East Provincial Virtual Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-provincial-zw-me',
    '00000000-0000-0000-0000-000000000001',
    'Mashonaland East Provincial Virtual Hospital',
    'PROVINCIAL',
    'NETWORKED',
    'Mashonaland East provincial health authority',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Decentralised telemedicine operations: local facility support, provincial clinical routing, provincial virtual queues and management.',
    'Mashonaland East province — linked districts and facilities',
    'ZW-ME',
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["Medical officers","Nurses","Provincial specialists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial general teleconsult', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-me' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-me' AND l.name = 'Provincial general teleconsult');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility-to-province support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-me' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-me' AND l.name = 'Facility-to-province support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'District escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-me' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-me' AND l.name = 'District escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial tele-follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-me' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-me' AND l.name = 'Provincial tele-follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Referral handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-me' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-me' AND l.name = 'Referral handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-general', 'Provincial General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-me' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-to-province', 'Facility-to-Province Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-me' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'district-escalation', 'District Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-me' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-followup', 'Provincial Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-me' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-provincial-zw-mw: Mashonaland West Provincial Virtual Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-provincial-zw-mw',
    '00000000-0000-0000-0000-000000000001',
    'Mashonaland West Provincial Virtual Hospital',
    'PROVINCIAL',
    'NETWORKED',
    'Mashonaland West provincial health authority',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Decentralised telemedicine operations: local facility support, provincial clinical routing, provincial virtual queues and management.',
    'Mashonaland West province — linked districts and facilities',
    'ZW-MW',
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["Medical officers","Nurses","Provincial specialists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial general teleconsult', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mw' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mw' AND l.name = 'Provincial general teleconsult');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility-to-province support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mw' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mw' AND l.name = 'Facility-to-province support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'District escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mw' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mw' AND l.name = 'District escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial tele-follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mw' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mw' AND l.name = 'Provincial tele-follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Referral handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mw' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mw' AND l.name = 'Referral handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-general', 'Provincial General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mw' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-to-province', 'Facility-to-Province Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mw' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'district-escalation', 'District Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mw' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-followup', 'Provincial Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mw' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-provincial-zw-mv: Masvingo Provincial Virtual Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-provincial-zw-mv',
    '00000000-0000-0000-0000-000000000001',
    'Masvingo Provincial Virtual Hospital',
    'PROVINCIAL',
    'NETWORKED',
    'Masvingo provincial health authority',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Decentralised telemedicine operations: local facility support, provincial clinical routing, provincial virtual queues and management.',
    'Masvingo province — linked districts and facilities',
    'ZW-MV',
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["Medical officers","Nurses","Provincial specialists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial general teleconsult', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mv' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mv' AND l.name = 'Provincial general teleconsult');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility-to-province support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mv' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mv' AND l.name = 'Facility-to-province support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'District escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mv' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mv' AND l.name = 'District escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial tele-follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mv' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mv' AND l.name = 'Provincial tele-follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Referral handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mv' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mv' AND l.name = 'Referral handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-general', 'Provincial General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mv' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-to-province', 'Facility-to-Province Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mv' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'district-escalation', 'District Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mv' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-followup', 'Provincial Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mv' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-provincial-zw-mn: Matabeleland North Provincial Virtual Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-provincial-zw-mn',
    '00000000-0000-0000-0000-000000000001',
    'Matabeleland North Provincial Virtual Hospital',
    'PROVINCIAL',
    'NETWORKED',
    'Matabeleland North provincial health authority',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Decentralised telemedicine operations: local facility support, provincial clinical routing, provincial virtual queues and management.',
    'Matabeleland North province — linked districts and facilities',
    'ZW-MN',
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["Medical officers","Nurses","Provincial specialists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial general teleconsult', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mn' AND l.name = 'Provincial general teleconsult');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility-to-province support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mn' AND l.name = 'Facility-to-province support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'District escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mn' AND l.name = 'District escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial tele-follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mn' AND l.name = 'Provincial tele-follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Referral handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mn' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mn' AND l.name = 'Referral handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-general', 'Provincial General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mn' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-to-province', 'Facility-to-Province Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mn' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'district-escalation', 'District Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mn' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-followup', 'Provincial Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mn' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-provincial-zw-ms: Matabeleland South Provincial Virtual Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-provincial-zw-ms',
    '00000000-0000-0000-0000-000000000001',
    'Matabeleland South Provincial Virtual Hospital',
    'PROVINCIAL',
    'NETWORKED',
    'Matabeleland South provincial health authority',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Decentralised telemedicine operations: local facility support, provincial clinical routing, provincial virtual queues and management.',
    'Matabeleland South province — linked districts and facilities',
    'ZW-MS',
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["Medical officers","Nurses","Provincial specialists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial general teleconsult', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ms' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ms' AND l.name = 'Provincial general teleconsult');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility-to-province support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ms' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ms' AND l.name = 'Facility-to-province support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'District escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ms' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ms' AND l.name = 'District escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial tele-follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ms' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ms' AND l.name = 'Provincial tele-follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Referral handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ms' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-ms' AND l.name = 'Referral handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-general', 'Provincial General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ms' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-to-province', 'Facility-to-Province Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ms' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'district-escalation', 'District Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ms' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-followup', 'Provincial Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-ms' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- ---- vh-provincial-zw-mi: Midlands Provincial Virtual Hospital ----
INSERT INTO tuso.virtual_service_entity (vs_uid, tenant_id, name, level, operating_model, operating_authority, regulatory_status, purpose, catchment, province_code, cross_border_participation, allowed_cross_border_privileges, billing_models, session_mode_ids, provider_pool_cadres, linked_facility_roles, lifecycle_status) VALUES (
    'vh-provincial-zw-mi',
    '00000000-0000-0000-0000-000000000001',
    'Midlands Provincial Virtual Hospital',
    'PROVINCIAL',
    'NETWORKED',
    'Midlands provincial health authority',
    'POLICY_CONFIGURABLE_PENDING_DETERMINATION',
    'Decentralised telemedicine operations: local facility support, provincial clinical routing, provincial virtual queues and management.',
    'Midlands province — linked districts and facilities',
    'ZW-MI',
    FALSE,
    '[]'::jsonb,
    '["PUBLIC_SERVICE"]'::jsonb,
    '["direct-clinical-encounter","provider-to-provider-advice"]'::jsonb,
    '["Medical officers","Nurses","Provincial specialists"]'::jsonb,
    '["ACCESS_POINT","REQUESTER","REFERRAL_DESTINATION","STAFF_CONTRIBUTING"]'::jsonb,
    'CONFIGURED'
) ON CONFLICT (vs_uid) DO NOTHING;

INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial general teleconsult', 0 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mi' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mi' AND l.name = 'Provincial general teleconsult');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Facility-to-province support', 1 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mi' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mi' AND l.name = 'Facility-to-province support');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'District escalation', 2 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mi' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mi' AND l.name = 'District escalation');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Provincial tele-follow-up', 3 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mi' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mi' AND l.name = 'Provincial tele-follow-up');
INSERT INTO tuso.virtual_service_line (virtual_service_id, name, position) SELECT id, 'Referral handover', 4 FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mi' AND NOT EXISTS (SELECT 1 FROM tuso.virtual_service_line l JOIN tuso.virtual_service_entity e ON l.virtual_service_id = e.id WHERE e.vs_uid = 'vh-provincial-zw-mi' AND l.name = 'Referral handover');
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-general', 'Provincial General Teleconsult Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mi' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'facility-to-province', 'Facility-to-Province Support Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mi' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'district-escalation', 'District Escalation Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mi' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;
INSERT INTO tuso.virtual_service_queue_def (virtual_service_id, queue_key, name, default_sla_minutes, rules) SELECT id, 'provincial-followup', 'Provincial Tele-follow-up Queue', NULL, '{}'::jsonb FROM tuso.virtual_service_entity WHERE vs_uid = 'vh-provincial-zw-mi' ON CONFLICT (virtual_service_id, queue_key) DO NOTHING;

-- Totals: 21 entities, 5 routing seams (5 active), 89 queue definitions.
