global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'impilo-infrastructure'
    static_configs:
      - targets:
        - 'keycloak:8080'
        - 'hapi-fhir:8080'
        - 'vault:8200'
