server_address=http://localhost:8092/fhir
server_name=BUTANO FHIR Gateway
server_version=R4

allow_multiple_delete=false
allow_external_references=false
allow_placeholder_references=false

default_page_size=20
max_page_size=100
max_binary_size=104857600

reuse_cached_search_results_millis=-1

bulk_export_enabled=false

fhir.cpid.system=https://impilo.gov.zw/cpid
fhir.pii.enforce=true

fhir.patient.allowed_fields=id,meta,identifier,active,gender,birthDate
fhir.patient.rejected_fields=name,telecom,address,photo,contact,link,communication,generalPractitioner,managingOrganization
