syntax = "proto3";

package envoy.service.auth.v3;

option java_multiple_files = true;
option java_package = "io.envoyproxy.envoy.service.auth.v3";
option java_outer_classname = "ExternalAuthProto";

import "envoy/service/auth/v3/attribute_context.proto";
import "google/rpc/status.proto";

// The Authorization service — Envoy calls Check() on every request.
service Authorization {
  // Performs authorization check based on the attributes associated with the
  // incoming request, and returns status OK or not OK.
  rpc Check(CheckRequest) returns (CheckResponse) {}
}

message CheckRequest {
  // The request attributes.
  AttributeContext attributes = 1;
}

message CheckResponse {
  // Status OK allows the request. Any other status denies the request.
  google.rpc.Status status = 1;

  oneof http_response {
    // Supplies http attributes for a denied response.
    DeniedHttpResponse denied_response = 2;
    // Supplies http attributes for an ok response.
    OkHttpResponse ok_response = 3;
  }
}

message DeniedHttpResponse {
  // HTTP status code to use for the denied response.
  envoy.service.auth.v3.HttpStatus status = 1;
  // HTTP headers to set in the denied response.
  repeated HeaderValueOption headers = 2;
  // Body to return with denied response.
  string body = 3;
}

message OkHttpResponse {
  // HTTP headers to inject into the original request (forwarded to upstream).
  repeated HeaderValueOption headers = 1;
  // HTTP headers to add to the response back to downstream.
  repeated HeaderValueOption response_headers_to_add = 3;
}

message HeaderValueOption {
  HeaderValue header = 1;
  bool append = 2;
}

message HeaderValue {
  string key = 1;
  string value = 2;
}

message HttpStatus {
  StatusCode code = 1;

  enum StatusCode {
    Empty = 0;
    Continue = 100;
    OK = 200;
    Created = 201;
    Accepted = 202;
    BadRequest = 400;
    Unauthorized = 401;
    Forbidden = 403;
    NotFound = 404;
    InternalServerError = 500;
    ServiceUnavailable = 503;
  }
}
