/**
 * Curated shell app catalog — routes and role gates match Experience `routes.ts` / sidebar.
 */

import { matchesRequiredRole } from "@/lib/auth/role-groups";
import type { AppDefinition, ShellCommand } from "./types";

/** Reserved bottom canvas space: floating dock height + inset + safe buffer */
export const SHELL_DOCK_HEIGHT_PX = 48;
export const SHELL_DOCK_BOTTOM_INSET_PX = 12;
export const SHELL_TASKBAR_HEIGHT_PX = SHELL_DOCK_HEIGHT_PX + SHELL_DOCK_BOTTOM_INSET_PX + 8;

export const SHELL_APPS: AppDefinition[] = [
  {
    id: "app-home",
    appCode: "home",
    name: "Home",
    description: "Role-aware dashboard and workplace hub",
    icon: "LayoutDashboard",
    category: "citizen",
    href: "/home",
    activeFlag: true,
    systemAppFlag: false,
    weight: 0,
  },
  {
    id: "app-command-centre",
    appCode: "command_centre",
    name: "Production Command Centre",
    description: "Discover and navigate the full Health OS with status and demo paths",
    icon: "LayoutGrid",
    category: "system",
    href: "/production-command-centre",
    activeFlag: true,
    systemAppFlag: true,
    weight: 1,
    requiredRole: "ADMIN",
  },
  {
    id: "app-learning",
    appCode: "learning",
    name: "Impilo Fundo",
    description: "Fundo courses, SOPs, and role-aware training",
    icon: "GraduationCap",
    category: "citizen",
    href: "/learning",
    activeFlag: true,
    systemAppFlag: false,
    weight: 3,
    serviceSlug: "fundo",
  },
  {
    // Coverage was fully routed and backed by a real, seeded service but had no
    // launcher/nav presence — reachable only by typing the URL ("can't see it
    // anywhere"). Citizen-facing landing is /coverage/member (auth-only); the
    // ADMIN /coverage operations console stays gated by its route guard.
    id: "app-coverage",
    appCode: "coverage",
    // Ruvimbo is the sovereign brand for the Coverage / health-financing capability.
    name: "Ruvimbo",
    description: "Health coverage, benefits, enrolment, subsidies and claims",
    icon: "ShieldCheck",
    category: "citizen",
    // Role-aware entry resolver (/ruvimbo) routes citizen → member, provider → provider,
    // payer → payer, admin → administration; /coverage/member stays alive via redirect.
    href: "/ruvimbo",
    activeFlag: true,
    systemAppFlag: false,
    weight: 4,
    maturity: "live",
    serviceSlug: "ruvimbo",
  },
  {
    id: "app-clinical",
    appCode: "clinical",
    name: "Clinical Hub",
    description: "Clinical care modules",
    icon: "Stethoscope",
    category: "clinical",
    href: "/clinical",
    activeFlag: true,
    requiredRole: "CLINICAL",
    systemAppFlag: false,
    weight: 10,
  },
  {
    id: "app-queue",
    appCode: "queue",
    name: "Queue",
    description: "Queues, triage, and ward flow",
    icon: "Users",
    category: "clinical",
    href: "/queue",
    activeFlag: true,
    requiredRole: "QUEUE",
    systemAppFlag: false,
    weight: 20,
  },
  {
    id: "app-ehr-queue",
    appCode: "ehr_search",
    name: "Find patient",
    description: "Open a chart from queue search",
    icon: "Search",
    category: "clinical",
    href: "/queue/search",
    activeFlag: true,
    requiredRole: "QUEUE",
    systemAppFlag: false,
    weight: 25,
  },
  {
    id: "app-pharmacy",
    appCode: "pharmacy",
    name: "Pharmacy",
    description: "Prescriptions and dispensing",
    icon: "Pill",
    category: "clinical",
    href: "/pharmacy",
    activeFlag: true,
    requiredRole: "DISPENSER",
    systemAppFlag: false,
    weight: 30,
  },
  {
    id: "app-lab",
    appCode: "lab",
    name: "Laboratory",
    description: "LIMS / lab worklist (OROS)",
    icon: "FlaskConical",
    category: "clinical",
    href: "/lab",
    activeFlag: true,
    requiredRole: "CLINICAL",
    systemAppFlag: false,
    weight: 40,
  },
  {
    id: "app-finance",
    appCode: "finance",
    name: "Finance",
    description: "Billing, claims, MusheX",
    icon: "Wallet",
    category: "finance",
    href: "/finance",
    activeFlag: true,
    requiredRole: "FINANCE",
    systemAppFlag: false,
    weight: 10,
  },
  {
    id: "app-erp",
    appCode: "institutional_erp",
    name: "Institutional ERP",
    description: "General ledger, HR, procurement, and asset workflows",
    icon: "Wallet",
    category: "finance",
    href: "/erp",
    activeFlag: true,
    requiredRole: "FINANCE",
    systemAppFlag: false,
    weight: 11,
  },
  {
    id: "app-registry",
    appCode: "registry",
    name: "Registry",
    description: "Clients, providers, facilities (VITO / VARAPI / TUSO)",
    icon: "Database",
    category: "registry",
    href: "/registry",
    activeFlag: true,
    requiredRole: "CLINICAL",
    systemAppFlag: false,
    weight: 10,
  },
  {
    id: "app-operations-vito",
    appCode: "ops_vito",
    name: "Identity ops",
    description: "VITO operational tooling",
    icon: "Shield",
    category: "operations",
    href: "/operations/vito",
    activeFlag: true,
    requiredRole: "ADMIN",
    systemAppFlag: false,
    weight: 20,
    serviceSlug: "vito",
  },
  {
    id: "app-public-health",
    appCode: "public_health",
    name: "Public Health",
    description: "Surveillance, campaigns, and site registry operations",
    icon: "Shield",
    category: "operations",
    href: "/public-health",
    activeFlag: true,
    requiredRole: "PUBLIC_HEALTH",
    systemAppFlag: false,
    weight: 23,
  },
  {
    id: "app-facility-operations",
    appCode: "facility_operations",
    name: "Facility operations",
    description: "District view, patient flow, and resource operations",
    icon: "Building2",
    category: "operations",
    href: "/operations/facility-operations",
    activeFlag: true,
    requiredRole: "ADMIN",
    systemAppFlag: false,
    weight: 21,
  },
  {
    id: "app-marketplace",
    appCode: "marketplace",
    name: "Marketplace",
    description: "Msika / commerce flows",
    icon: "BriefcaseBusiness",
    category: "operations",
    href: "/marketplace",
    activeFlag: true,
    requiredRole: "MARKETPLACE_ACCESS",
    systemAppFlag: false,
    weight: 30,
    serviceSlug: "msika",
  },
  {
    id: "app-citizen",
    appCode: "citizen",
    name: "Citizen services",
    description: "Health ID and citizen self-service",
    icon: "IdCard",
    category: "citizen",
    href: "/citizen",
    activeFlag: true,
    systemAppFlag: false,
    weight: 40,
  },
  {
    id: "app-documents",
    appCode: "my_documents",
    name: "My documents",
    description: "Personal document vault",
    icon: "FileText",
    category: "citizen",
    href: "/home/documents",
    activeFlag: true,
    systemAppFlag: false,
    weight: 50,
  },
  {
    id: "app-search",
    appCode: "knowledge_search",
    name: "Knowledge search",
    description: "Indexed health and service knowledge",
    icon: "BookOpen",
    category: "intelligence",
    href: "/search",
    activeFlag: true,
    systemAppFlag: false,
    weight: 10,
  },
  {
    id: "app-intelligence-hub",
    appCode: "intelligence_hub",
    name: "Health Intelligence",
    description: "Intelligence hub, Ask, and fused retrieval (shell-suggest plane)",
    icon: "Sparkles",
    category: "intelligence",
    href: "/intelligence",
    activeFlag: true,
    systemAppFlag: false,
    weight: 5,
  },
  {
    id: "app-ask",
    appCode: "ask_impilo",
    name: "Ask",
    description: "Grounded Q&A across governed sources",
    icon: "MessageCircle",
    category: "intelligence",
    href: "/ask",
    activeFlag: true,
    systemAppFlag: false,
    weight: 8,
    serviceSlug: "nompilo",
  },
  {
    id: "app-guidance",
    appCode: "guidance",
    name: "Guidance",
    description: "Reminders, education, and governed prompts",
    icon: "Compass",
    category: "intelligence",
    href: "/guidance",
    activeFlag: true,
    systemAppFlag: false,
    weight: 12,
  },
  {
    id: "app-inventory",
    appCode: "inventory",
    name: "Inventory",
    description: "Stock, movements, and requisitions (facility-scoped)",
    icon: "Package",
    category: "operations",
    href: "/inventory",
    activeFlag: true,
    systemAppFlag: false,
    weight: 22,
    requiredRole: "OPERATIONS_AGGREGATE",
  },
  {
    id: "app-enterprise",
    appCode: "enterprise",
    name: "Enterprise resources",
    description: "ERP plane — dashboard, procurement, finance, logistics, and asset handoffs",
    icon: "Boxes",
    category: "operations",
    href: "/enterprise",
    activeFlag: true,
    systemAppFlag: false,
    weight: 21,
    requiredRole: "FINANCE",
  },
  {
    id: "app-nhume",
    appCode: "nhume",
    name: "Nhume logistics",
    description: "Last-mile deliveries, fleet, and dispatch zones",
    icon: "Truck",
    category: "operations",
    href: "/nhume",
    activeFlag: true,
    maturity: "partial",
    plane: "Enterprise",
    systemAppFlag: false,
    weight: 22,
    serviceSlug: "nhume",
    requiredRole: "DISPATCH_OPERATIONS",
  },
  {
    id: "app-madi",
    appCode: "madi",
    name: "Madi blood services",
    description: "Donation drives, transfusion, blood bank and haemovigilance",
    icon: "Droplet",
    category: "operations",
    href: "/madi",
    activeFlag: true,
    maturity: "partial",
    plane: "Clinical",
    systemAppFlag: false,
    weight: 22,
    serviceSlug: "madi",
    requiredRole: "OPERATIONS_AGGREGATE",
  },
  {
    id: "app-madi-donor",
    appCode: "madi_donor",
    name: "Blood donation",
    description: "Voluntary donor hub — register, drives, history",
    icon: "Droplet",
    category: "citizen",
    href: "/madi/donor",
    activeFlag: true,
    maturity: "partial",
    plane: "Experience",
    systemAppFlag: false,
    weight: 18,
    serviceSlug: "madi",
  },
  {
    id: "app-ndila",
    appCode: "ndila",
    name: "Ndila maps",
    description: "Geospatial intelligence and unified logistics overlay",
    icon: "Map",
    category: "operations",
    href: "/ndila",
    activeFlag: true,
    maturity: "partial",
    plane: "Data",
    systemAppFlag: false,
    weight: 23,
    serviceSlug: "ndila",
    requiredRole: "OPERATIONS_AGGREGATE",
  },
  {
    id: "app-dispatch",
    appCode: "dispatch_ops",
    name: "Dispatch operations",
    description: "Task console with shared Nhume map panel",
    icon: "Radio",
    category: "operations",
    href: "/operations/dispatch",
    activeFlag: true,
    // Gated on the dispatch chain (DISPATCH_COORDINATOR/COURIER are seeded realm roles).
    requiredRole: "DISPATCH_OPERATIONS",
    maturity: "partial",
    plane: "Enterprise",
    systemAppFlag: false,
    weight: 24,
  },
  {
    id: "app-telemedicine",
    appCode: "telemedicine",
    name: "Telemedicine",
    description: "Impilo Live consults — schedule, waiting room, and sessions",
    icon: "Video",
    category: "clinical",
    href: "/telemedicine",
    activeFlag: true,
    requiredRole: "CLINICAL",
    systemAppFlag: false,
    weight: 15,
  },
  {
    id: "app-khuluma",
    appCode: "khuluma",
    name: "Khuluma",
    // The communication front door: role-aware hub at /khuluma (citizen 'life' + provider
    // 'work'). Messaging is one workspace; calls/meetings link the sovereign Impilo Live stage.
    description: "Messages, calls, meetings, updates and escalation — your communication hub",
    icon: "MessageSquare",
    category: "citizen",
    href: "/khuluma",
    activeFlag: true,
    systemAppFlag: false,
    weight: 25,
    serviceSlug: "khuluma",
  },
  {
    id: "app-rito",
    appCode: "rito",
    name: "Rito quality & safety",
    description: "Cases, audits, surveys, and quality signals",
    icon: "ShieldCheck",
    category: "operations",
    href: "/rito",
    activeFlag: true,
    requiredRole: "OPERATIONS_AGGREGATE",
    systemAppFlag: false,
    weight: 26,
    serviceSlug: "rito",
  },
  {
    id: "app-dura",
    appCode: "dura",
    name: "Dura stores",
    description: "Facility stores, stock health, and replenishment (Dura)",
    icon: "Warehouse",
    category: "operations",
    href: "/work/dura",
    activeFlag: true,
    requiredRole: "OPERATIONS_AGGREGATE",
    systemAppFlag: false,
    weight: 27,
    serviceSlug: "dura",
  },
  {
    id: "app-daidzai",
    appCode: "daidzai",
    name: "Daidzai emergency",
    description: "Emergency missions, disasters, and dispatch",
    icon: "Siren",
    category: "operations",
    href: "/work/daidzai",
    activeFlag: true,
    requiredRole: "OPERATIONS_AGGREGATE",
    systemAppFlag: false,
    weight: 28,
    serviceSlug: "daidzai",
  },
  {
    id: "app-vashandi",
    appCode: "vashandi",
    name: "Vashandi workforce",
    description: "Workforce profiles, rosters, attendance, and intake",
    icon: "UsersRound",
    category: "operations",
    href: "/work/vashandi",
    activeFlag: true,
    requiredRole: "WORKFORCE_ADMIN",
    systemAppFlag: false,
    weight: 29,
    serviceSlug: "vashandi",
  },
  {
    id: "app-simba",
    appCode: "simba",
    name: "Simba wellness",
    description: "Diet, sleep, fitness, clubs, and coaching",
    icon: "HeartPulse",
    category: "citizen",
    href: "/wellness",
    activeFlag: true,
    systemAppFlag: false,
    weight: 45,
    serviceSlug: "simba",
  },
  {
    id: "app-ubomi",
    appCode: "ubomi",
    name: "Ubomi life events",
    description: "Birth and death registration, CRVS journeys",
    icon: "BookUser",
    category: "citizen",
    href: "/ubomi",
    activeFlag: true,
    systemAppFlag: false,
    weight: 46,
    serviceSlug: "ubomi",
  },
  {
    id: "app-settings",
    appCode: "settings",
    name: "Settings",
    description: "Account and experience preferences",
    icon: "Settings2",
    category: "system",
    href: "/settings",
    activeFlag: true,
    systemAppFlag: true,
    weight: 100,
  },
  {
    id: "app-shell-file-manager",
    appCode: "shell_file_manager",
    name: "File manager",
    description: "vNext document and resource explorer",
    icon: "FolderOpen",
    category: "system",
    href: "/shell/file-manager",
    activeFlag: true,
    systemAppFlag: true,
    weight: 5,
  },
  {
    id: "app-shell-task-manager",
    appCode: "shell_task_manager",
    name: "Task manager",
    description: "Open apps and workspaces",
    icon: "Layers",
    category: "system",
    href: "/shell/task-manager",
    activeFlag: true,
    systemAppFlag: true,
    weight: 4,
  },
];

export const SHELL_COMMANDS: ShellCommand[] = [
  {
    id: "cmd-open-start",
    label: "Open Start menu",
    description: "Launcher",
    keywords: ["start", "launcher", "menu", "apps"],
    action: { type: "open-start" },
  },
  {
    id: "cmd-open-search",
    label: "Open search",
    keywords: ["search", "find", "go"],
    action: { type: "open-search" },
  },
  {
    id: "cmd-home",
    label: "Go to Home",
    keywords: ["home", "dashboard"],
    action: { type: "navigate", href: "/home" },
  },
  {
    id: "cmd-learning",
    label: "Open Learning hub",
    keywords: ["learning", "training", "fundo", "cpd", "courses", "sop"],
    action: { type: "navigate", href: "/learning" },
  },
  {
    id: "cmd-intelligence",
    label: "Open Intelligence hub",
    keywords: ["intelligence", "insights", "ai", "fusion", "health intelligence"],
    action: { type: "navigate", href: "/intelligence" },
  },
  {
    id: "cmd-ask",
    label: "Ask Nompilo",
    description: "AI guidance, search, and workflow companion",
    keywords: ["nompilo", "ask nompilo", "ask", "question", "chat", "assistant", "guidance", "ai"],
    action: { type: "navigate", href: "/ask" },
  },
  {
    id: "cmd-inventory",
    label: "Open Inventory",
    keywords: ["inventory", "stock", "warehouse", "requisition"],
    action: { type: "navigate", href: "/inventory" },
    requiredRole: "OPERATIONS_AGGREGATE",
  },
  {
    id: "cmd-enterprise",
    label: "Open Enterprise resources",
    keywords: ["enterprise", "erp", "procurement", "commodities", "supply", "resource plane"],
    action: { type: "navigate", href: "/enterprise" },
    requiredRole: "FINANCE",
  },
  {
    id: "cmd-erp",
    label: "Open Institutional ERP",
    keywords: ["erp", "general ledger", "hr", "procurement", "assets"],
    action: { type: "navigate", href: "/erp" },
    requiredRole: "FINANCE",
  },
  {
    id: "cmd-file-manager",
    label: "Open File manager",
    keywords: ["files", "documents", "explorer", "vault"],
    action: { type: "open-file-manager" },
  },
  {
    id: "cmd-task-manager",
    label: "Open Task manager",
    keywords: ["tasks", "windows", "workspaces", "running"],
    action: { type: "open-task-manager" },
  },
  {
    id: "cmd-queue",
    label: "Open Queue",
    keywords: ["queue", "triage"],
    action: { type: "navigate", href: "/queue" },
    requiredRole: "QUEUE",
  },
  {
    id: "cmd-pacs-workflow",
    label: "Open PACS workflow",
    keywords: ["pacs", "dicom", "imaging", "radiology", "orthanc"],
    action: { type: "navigate", href: "/queue/search?workflow=pacs" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-clinical",
    label: "Open Clinical hub",
    keywords: ["clinical", "care", "clinical hub", "patient care"],
    action: { type: "navigate", href: "/clinical" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-nav-drawer",
    label: "Open full navigation map",
    description: "Work, Professional, and Life zones",
    keywords: ["navigation", "sidebar", "zones", "menu", "map", "all apps"],
    action: { type: "open-nav-drawer" },
  },
  {
    id: "cmd-clinical-tools",
    label: "Clinical references",
    keywords: ["references", "clinical tools", "books", "guidelines"],
    action: { type: "navigate", href: "/clinical-tools" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-ed",
    label: "ED / Casualty",
    keywords: ["ed", "casualty", "emergency", "er", "aec"],
    action: { type: "navigate", href: "/clinical/emergency" },
    requiredRole: "QUEUE",
  },
  {
    id: "cmd-scheduling",
    label: "Scheduling",
    keywords: ["schedule", "appointments", "booking", "calendar", "roster"],
    action: { type: "navigate", href: "/scheduling" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-book-service",
    label: "Book a service",
    keywords: ["book", "booking", "request visit", "self book", "citizen booking"],
    action: { type: "navigate", href: "/home/bookings/new" },
  },
  {
    id: "cmd-my-bookings",
    label: "My Bookings",
    keywords: ["bookings", "pending booking", "booking status", "mvumo"],
    action: { type: "navigate", href: "/home/bookings" },
  },
  {
    id: "cmd-my-appointments",
    label: "My Appointments",
    keywords: ["appointments", "confirmed visit", "scheduled visit", "check in"],
    action: { type: "navigate", href: "/home/appointments" },
  },
  {
    id: "cmd-booking-requests",
    label: "Booking requests inbox",
    keywords: ["booking requests", "triage", "approve booking", "convert booking"],
    action: { type: "navigate", href: "/scheduling/booking-requests" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-today-appointments",
    label: "Today's appointments",
    keywords: ["today", "appointments today", "daily schedule"],
    action: { type: "navigate", href: "/scheduling/today" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-pharmacy",
    label: "Pharmacy",
    keywords: ["pharmacy", "dispensing", "prescriptions", "rx"],
    action: { type: "navigate", href: "/pharmacy" },
    requiredRole: "DISPENSER",
  },
  {
    id: "cmd-marketplace",
    label: "Marketplace",
    keywords: ["marketplace", "msika", "commerce", "suppliers"],
    action: { type: "navigate", href: "/marketplace" },
    requiredRole: "MARKETPLACE_ACCESS",
  },
  {
    id: "cmd-marketplace-ops",
    label: "Marketplace operations",
    keywords: ["marketplace ops", "vendor governance", "moderation", "substitutions", "msika ops"],
    action: { type: "navigate", href: "/marketplace/ops" },
    requiredRole: "MARKETPLACE_OPS",
  },
  {
    id: "cmd-marketplace-seller",
    label: "Seller centre",
    keywords: ["seller", "sell", "list product", "my listings", "msika seller"],
    action: { type: "navigate", href: "/marketplace/seller" },
    requiredRole: "MARKETPLACE_SELL",
  },
  {
    id: "cmd-vendor-fulfilment",
    label: "Vendor fulfilment",
    keywords: ["vendor", "fulfilment", "vendor orders", "dispatch orders", "msika vendor"],
    action: { type: "navigate", href: "/marketplace/vendor" },
    requiredRole: "VENDOR_FULFILMENT",
  },
  {
    id: "cmd-professional",
    label: "Professional profile",
    keywords: ["professional", "provider profile", "hcp"],
    action: { type: "navigate", href: "/professional" },
  },
  {
    id: "cmd-credentials",
    label: "Credentials & CPD",
    keywords: ["credentials", "cpd", "license", "registration"],
    action: { type: "navigate", href: "/home/credentials" },
  },
  {
    id: "cmd-registry-plane",
    label: "Registry governance plane",
    keywords: ["registry admin", "registry plane", "hie", "governance", "tshepo", "trust"],
    action: { type: "navigate", href: "/registry-admin" },
    requiredRole: "REGISTRY_ADMIN",
  },
  {
    id: "cmd-mvumo-consent",
    label: "Mvumo — digital consent",
    keywords: ["mvumo", "consent", "adaptive consent", "authorisation", "permission", "e-sign", "telemedicine consent"],
    action: { type: "navigate", href: "/registry/mvumo" },
    requiredRole: "REGISTRY_ADMIN",
  },
  {
    id: "cmd-organization-admin",
    label: "Organization administration",
    keywords: ["org admin", "organization", "facility admin", "enterprise admin"],
    action: { type: "navigate", href: "/organization-admin" },
    requiredRole: "ORGANIZATION_ADMIN",
  },
  {
    id: "cmd-reports",
    label: "Reports",
    keywords: ["reports", "reporting", "exports"],
    action: { type: "navigate", href: "/reports" },
    requiredRole: "OPERATIONS_AGGREGATE",
  },
  {
    id: "cmd-admin",
    label: "Administration",
    keywords: ["admin", "users", "roles", "governance"],
    action: { type: "navigate", href: "/admin" },
    requiredRole: "ADMIN",
  },
  {
    id: "cmd-public-health",
    label: "Public Health",
    keywords: ["public health", "campaigns", "surveillance", "site registry"],
    action: { type: "navigate", href: "/public-health" },
    requiredRole: "PUBLIC_HEALTH",
  },
  {
    id: "cmd-dags",
    label: "Data Access Governance",
    keywords: ["dags", "data access governance", "policy"],
    action: { type: "navigate", href: "/dags" },
    requiredRole: "ADMIN",
  },
  {
    id: "cmd-operations",
    label: "Operations console",
    keywords: ["operations", "ops", "vito", "butano", "assets"],
    action: { type: "navigate", href: "/operations" },
    requiredRole: "ADMIN",
  },
  {
    id: "cmd-developer",
    label: "Developer portal",
    keywords: ["developer", "api", "sandbox", "clients"],
    action: { type: "navigate", href: "/developer" },
    requiredRole: "ADMIN",
  },
  {
    id: "cmd-clinical-curation",
    label: "Knowledge curation",
    keywords: ["curation", "knowledge", "content governance"],
    action: { type: "navigate", href: "/admin/clinical-curation" },
    requiredRole: "ADMIN",
  },
  {
    id: "cmd-sidecar-ledger",
    label: "Sidecar retirement ledger",
    keywords: ["sidecar", "ledger", "migration"],
    action: { type: "navigate", href: "/admin/sidecar-retirement" },
    requiredRole: "ADMIN",
  },
  {
    id: "cmd-telemedicine",
    label: "Telemedicine",
    keywords: ["telemedicine", "teleconsult", "video consult", "remote consult"],
    action: { type: "navigate", href: "/telemedicine" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-control-tower",
    label: "Facility control tower",
    keywords: ["control tower", "facility dashboard", "operations", "patient flow", "facility status"],
    action: { type: "navigate", href: "/clinical/control-tower" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-guidance",
    label: "Guidance",
    keywords: ["guidance", "reminders", "education", "help prompts"],
    action: { type: "navigate", href: "/guidance" },
  },
  {
    id: "cmd-citizen",
    label: "Citizen services",
    keywords: ["citizen", "health id", "self service"],
    action: { type: "navigate", href: "/citizen" },
  },
  {
    id: "cmd-wallet",
    label: "My Wallet",
    keywords: ["wallet", "mushe", "payments", "digital wallet"],
    action: { type: "navigate", href: "/wallet" },
  },
  {
    id: "cmd-wellness",
    label: "Wellness",
    keywords: ["wellness", "prevention", "fitness"],
    action: { type: "navigate", href: "/wellness" },
  },
  {
    id: "cmd-caregiving",
    label: "Caregiving",
    keywords: ["caregiving", "dependants", "family care"],
    action: { type: "navigate", href: "/caregiving" },
  },
  {
    id: "cmd-monitoring",
    label: "Remote monitoring",
    keywords: ["monitoring", "devices", "readings", "chronic"],
    action: { type: "navigate", href: "/monitoring" },
  },
  {
    id: "cmd-discover",
    label: "Discover services",
    keywords: ["discover", "find provider", "find facility"],
    action: { type: "navigate", href: "/discover" },
  },
  {
    id: "cmd-claim-shared",
    label: "Claim shared documents",
    keywords: ["claim", "shared docs", "share slip"],
    action: { type: "navigate", href: "/share/claim" },
  },
  {
    id: "cmd-comms",
    label: "Khuluma — Comms hub",
    keywords: ["comms", "messages", "secure messaging", "communication", "khuluma"],
    action: { type: "navigate", href: "/khuluma" },
  },
  {
    id: "cmd-support",
    label: "System support",
    keywords: ["support", "ticket", "helpdesk", "bug", "downtime"],
    action: { type: "navigate", href: "/support" },
  },
  {
    id: "cmd-sos",
    label: "SOS escalation",
    keywords: ["sos", "emergency", "escalation", "incident"],
    action: { type: "open-sos" },
  },
  {
    id: "cmd-finance-billing",
    label: "Billing",
    keywords: ["billing", "bill", "invoice", "receipt"],
    action: { type: "navigate", href: "/finance/billing" },
    requiredRole: "FINANCE",
  },
  {
    id: "cmd-finance-payments",
    label: "Payments",
    keywords: ["payments", "claims", "mushex"],
    action: { type: "navigate", href: "/finance/payments" },
    requiredRole: "FINANCE",
  },
  {
    id: "cmd-finance-tariff-library",
    label: "Tariff library",
    keywords: [
      "tariff",
      "tariff library",
      "costing",
      "costa",
      "price list",
      "schedule",
      "billing tariff",
      "reference tariff",
    ],
    action: { type: "navigate", href: "/finance/tariffs" },
    requiredRole: "FINANCE",
  },
  {
    id: "cmd-finance-costa",
    label: "COSTA & MusheX tools",
    keywords: ["costa", "cost estimate", "charge sheet", "settlement", "mushex handoff", "tariff intel"],
    action: { type: "navigate", href: "/finance/costa" },
    requiredRole: "FINANCE",
  },
  {
    id: "cmd-finance-settlements",
    label: "MusheX settlements",
    keywords: ["settlements", "mushex", "payment handoff", "receivables"],
    action: { type: "navigate", href: "/finance/settlements" },
    requiredRole: "FINANCE",
  },
  {
    id: "cmd-finance-mushex-platform",
    label: "MusheX platform admin",
    keywords: [
      "mushex",
      "mushex platform",
      "platform admin",
      "custodial wallet",
      "remittance transfer",
      "card profile",
      "reversal",
      "gateway",
    ],
    action: { type: "navigate", href: "/finance/mushex-platform" },
    requiredRole: "FINANCE",
  },
  {
    id: "cmd-registry-intake",
    label: "Registry intake",
    keywords: ["vito", "client registry", "intake", "registry intake"],
    action: { type: "navigate", href: "/registry/intake" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-registry-providers",
    label: "Provider registry (Varapi)",
    keywords: ["varapi", "provider registry", "providers"],
    action: { type: "navigate", href: "/registry/providers" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-registry-facilities",
    label: "Facility registry (Tuso)",
    keywords: ["tuso", "facility registry", "facilities registry", "indawo", "places"],
    action: { type: "navigate", href: "/registry/facilities" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-registry-terminology",
    label: "Terminology (Zibo)",
    keywords: ["zibo", "terminology", "codes", "snomed", "loinc"],
    action: { type: "navigate", href: "/registry/terminology" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-registry-products",
    label: "Product registry (Msika)",
    keywords: ["msika", "product registry", "products", "catalog"],
    action: { type: "navigate", href: "/registry/products" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-new-course",
    label: "New course",
    description: "Create a Fundo course in Course Studio",
    keywords: ["new course", "create course", "course", "author", "fundo", "studio"],
    action: { type: "navigate", href: "/learning/studio/courses/new" },
    requiredRole: "LEARNING_AUTHOR",
  },
  {
    id: "cmd-course-studio",
    label: "Course Studio",
    keywords: ["course studio", "authoring", "fundo studio", "curriculum", "publish course"],
    action: { type: "navigate", href: "/learning/studio" },
    requiredRole: "LEARNING_AUTHOR",
  },
  {
    id: "cmd-my-courses",
    label: "My courses",
    keywords: ["my courses", "my learning", "enrolments", "resume course", "cpd courses"],
    action: { type: "navigate", href: "/learning/my-learning" },
  },
  {
    id: "cmd-start-teleconsult",
    label: "Start teleconsult",
    description: "Create a new telemedicine session",
    keywords: ["start teleconsult", "new consult", "tele", "video consult", "telemedicine session"],
    action: { type: "navigate", href: "/telemedicine/new" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-register-patient",
    label: "Register patient",
    description: "Walk-in registration and queue entry",
    keywords: ["register patient", "new patient", "walk-in", "walk in", "patient registration"],
    action: { type: "navigate", href: "/queue/walk-in" },
    requiredRole: "QUEUE",
  },
  {
    id: "cmd-add-to-queue",
    label: "Add patient to queue",
    keywords: ["add to queue", "queue patient", "facility queue", "queue entry"],
    action: { type: "navigate", href: "/queue/walk-in" },
    requiredRole: "QUEUE",
  },
  {
    id: "cmd-request-provider-access",
    label: "Request provider access",
    keywords: ["provider access", "request access", "become provider", "practise", "professional access"],
    action: { type: "navigate", href: "/professional/request-access" },
  },
  {
    id: "cmd-claim-facility",
    label: "Claim facility administration",
    keywords: ["claim facility", "facility claim", "facility admin claim", "administer facility"],
    action: { type: "navigate", href: "/facility/claim" },
  },
  {
    id: "cmd-issue-provider-id",
    label: "Issue Provider ID",
    description: "Create a provider record in Varapi",
    keywords: ["issue provider id", "new provider", "create provider", "provider id", "varapi issue"],
    action: { type: "navigate", href: "/registry/providers/new" },
    requiredRole: "ADMIN_OR_HIE",
  },
  {
    id: "cmd-workforce-intake",
    label: "Workforce intake",
    description: "Staged staff onboarding — upload, match, issue, invite",
    keywords: ["workforce intake", "staff onboarding", "staff upload", "bulk staff", "intake"],
    action: { type: "navigate", href: "/admin/workforce-intake" },
    requiredRole: "ADMIN",
  },
  {
    id: "cmd-diagnostics-orders",
    label: "Diagnostic orders",
    keywords: ["diagnostics", "order test", "imaging order", "lab order", "oros orders"],
    action: { type: "navigate", href: "/diagnostics/orders" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-diagnostics-worklist",
    label: "Imaging worklist",
    keywords: ["worklist", "radiology worklist", "imaging worklist", "perform study"],
    action: { type: "navigate", href: "/diagnostics/worklist" },
    requiredRole: "CLINICAL",
  },
  {
    id: "cmd-khuluma",
    label: "Khuluma comms hub",
    keywords: ["khuluma", "comms hub", "conversations", "calls", "meetings", "escalation"],
    action: { type: "navigate", href: "/khuluma" },
  },
  {
    id: "cmd-rito",
    label: "Rito quality & safety",
    keywords: ["rito", "quality", "safety cases", "audits", "surveys", "improvement"],
    action: { type: "navigate", href: "/rito" },
    requiredRole: "OPERATIONS_AGGREGATE",
  },
  {
    id: "cmd-dura",
    label: "Dura stores",
    keywords: ["dura", "stores", "stock", "replenishment"],
    action: { type: "navigate", href: "/work/dura" },
    requiredRole: "OPERATIONS_AGGREGATE",
  },
  {
    id: "cmd-daidzai",
    label: "Daidzai emergency",
    keywords: ["daidzai", "emergency missions", "disaster", "dispatch emergency"],
    action: { type: "navigate", href: "/work/daidzai" },
    requiredRole: "OPERATIONS_AGGREGATE",
  },
  {
    id: "cmd-vashandi",
    label: "Vashandi workforce",
    keywords: ["vashandi", "workforce", "rosters", "attendance", "assignments"],
    action: { type: "navigate", href: "/work/vashandi" },
    requiredRole: "WORKFORCE_ADMIN",
  },
  {
    id: "cmd-ubomi",
    label: "Ubomi life events",
    keywords: ["ubomi", "birth registration", "death registration", "crvs", "life events"],
    action: { type: "navigate", href: "/ubomi" },
  },
  {
    id: "cmd-iatg-console",
    label: "IATG Trust Console",
    description: "Pending access requests, facility claims, assurance upgrades",
    keywords: ["iatg", "trust console", "access requests", "approvals", "facility claims", "governance queue"],
    action: { type: "navigate", href: "/registry-admin/trust-console" },
    requiredRole: "REGISTRY_ADMIN",
  },
];

export function appVisibleForUser(
  app: AppDefinition,
  hasRole: (role: string) => boolean,
): boolean {
  if (!app.activeFlag) return false;
  if (!app.requiredRole) return true;
  return matchesRequiredRole(hasRole, app.requiredRole);
}

export function listVisibleShellApps(hasRole: (role: string) => boolean): AppDefinition[] {
  return SHELL_APPS.filter((a) => appVisibleForUser(a, hasRole)).sort((a, b) => {
    const wa = a.weight ?? 50;
    const wb = b.weight ?? 50;
    if (wa !== wb) return wa - wb;
    return a.name.localeCompare(b.name);
  });
}

export function findShellAppByCode(code: string): AppDefinition | undefined {
  return SHELL_APPS.find((a) => a.appCode === code);
}

export function visibleShellCommands(
  hasRole: (role: string) => boolean,
): ShellCommand[] {
  return SHELL_COMMANDS.filter((c) => !c.requiredRole || matchesRequiredRole(hasRole, c.requiredRole));
}

/**
 * Deep actions surfaced as "Quick actions" in the Start menu — ordered by
 * journey importance, role-filtered. Every id must reference a SHELL_COMMANDS
 * entry with a navigate action (enforced by the app-registry test).
 */
export const QUICK_ACTION_IDS: string[] = [
  "cmd-register-patient",
  "cmd-add-to-queue",
  "cmd-start-teleconsult",
  "cmd-new-course",
  "cmd-my-courses",
  "cmd-diagnostics-orders",
  "cmd-diagnostics-worklist",
  "cmd-issue-provider-id",
  "cmd-claim-facility",
  "cmd-request-provider-access",
  "cmd-workforce-intake",
  "cmd-vashandi",
  "cmd-book-service",
];

export function listQuickActions(
  hasRole: (role: string) => boolean,
  limit = 8,
): ShellCommand[] {
  const visible = visibleShellCommands(hasRole);
  const byId = new Map(visible.map((c) => [c.id, c]));
  const actions: ShellCommand[] = [];
  for (const id of QUICK_ACTION_IDS) {
    const cmd = byId.get(id);
    if (cmd && cmd.action.type === "navigate") actions.push(cmd);
    if (actions.length >= limit) break;
  }
  return actions;
}
