"use client";

import React, { useCallback, useEffect, useState } from "react";
import { vitoApi, type DedupCase } from "@/lib/vitoApi";

type DedupStatus = "PENDING" | "MERGED" | "REJECTED" | "DEFERRED";

/**
 * Dedup Case Review — operators review and resolve duplicate identity cases.
 * Cases are generated by the probabilistic matching engine when near-duplicate
 * records are detected in the registry.
 */
export default function DedupCaseReviewPage() {
  const [activeStatus, setActiveStatus] = useState<DedupStatus>("PENDING");
  const [cases, setCases] = useState<DedupCase[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedCase, setSelectedCase] = useState<DedupCase | null>(null);
  const [scoreResult, setScoreResult] = useState<{
    score: number;
    fieldScores: string;
    disposition: string;
  } | null>(null);
  const [scoreLoading, setScoreLoading] = useState(false);
  const [actionLoading, setActionLoading] = useState(false);

  const loadCases = useCallback(async () => {
    setLoading(true);
    try {
      const data = await vitoApi.getDedupCases(activeStatus, 0, 50);
      setCases(data.items ?? []);
    } catch {
      setCases([]);
    } finally {
      setLoading(false);
    }
  }, [activeStatus]);

  useEffect(() => {
    loadCases();
  }, [loadCases]);

  const openReview = async (dedupCase: DedupCase) => {
    setSelectedCase(dedupCase);
    setScoreResult(null);
    setScoreLoading(true);
    try {
      const result = await vitoApi.scoreDedupPair(dedupCase.candidateA, dedupCase.candidateB);
      setScoreResult(result);
    } catch {
      // Score unavailable
    } finally {
      setScoreLoading(false);
    }
  };

  const handleMerge = async () => {
    if (!selectedCase) return;
    setActionLoading(true);
    try {
      await vitoApi.executeMerge(
        selectedCase.id,
        selectedCase.candidateA,
        selectedCase.candidateB,
        "MANUAL"
      );
      setSelectedCase(null);
      setScoreResult(null);
      await loadCases();
    } catch {
      // Error handling via toast in production
    } finally {
      setActionLoading(false);
    }
  };

  const handleReject = async () => {
    if (!selectedCase) return;
    setActionLoading(true);
    try {
      // Reject by merging with REJECT strategy (no actual merge)
      await vitoApi.executeMerge(
        selectedCase.id,
        selectedCase.candidateA,
        selectedCase.candidateB,
        "REJECT"
      );
      setSelectedCase(null);
      setScoreResult(null);
      await loadCases();
    } catch {
      // Error handling via toast in production
    } finally {
      setActionLoading(false);
    }
  };

  const riskBadge = (risk?: string) => {
    const styles: Record<string, string> = {
      HIGH: "bg-danger/10 text-danger",
      MEDIUM: "bg-warning/10 text-warning",
      LOW: "bg-success/10 text-success",
    };
    return styles[risk ?? ""] ?? "bg-neutral-100 text-neutral-500";
  };

  const statusTabs: { key: DedupStatus; label: string }[] = [
    { key: "PENDING", label: "Pending" },
    { key: "MERGED", label: "Merged" },
    { key: "REJECTED", label: "Rejected" },
    { key: "DEFERRED", label: "Deferred" },
  ];

  return (
    <div className="max-w-7xl mx-auto px-6 py-8">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-neutral-900">
          Dedup Case Review
        </h1>
        <p className="text-sm text-neutral-500 mt-1">
          Review and resolve potential duplicate identity records from the matching engine
        </p>
      </div>

      {/* Tab bar */}
      <div className="flex gap-1 mb-4 bg-neutral-100 p-1 rounded-[12px] w-fit">
        {statusTabs.map((tab) => (
          <button
            key={tab.key}
            onClick={() => { setActiveStatus(tab.key); setSelectedCase(null); }}
            className={`px-4 py-2 text-sm font-medium rounded-[8px] transition-colors ${
              activeStatus === tab.key
                ? "bg-card text-neutral-900 shadow-subtle"
                : "text-neutral-500 hover:text-neutral-900"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Detail view */}
      {selectedCase && (
        <div className="bg-card rounded-[12px] shadow-subtle border border-neutral-100 p-6 mb-4">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-semibold text-neutral-900">
              Case #{selectedCase.id} — Score Breakdown
            </h2>
            <button
              onClick={() => { setSelectedCase(null); setScoreResult(null); }}
              className="text-sm text-neutral-500 hover:text-neutral-900"
            >
              Close
            </button>
          </div>

          <div className="grid grid-cols-2 gap-4 mb-4">
            <div>
              <span className="text-xs text-neutral-500">Candidate A</span>
              <p className="font-mono text-sm text-neutral-900 mt-1">{selectedCase.candidateA}</p>
            </div>
            <div>
              <span className="text-xs text-neutral-500">Candidate B</span>
              <p className="font-mono text-sm text-neutral-900 mt-1">{selectedCase.candidateB}</p>
            </div>
          </div>

          {scoreLoading ? (
            <p className="text-sm text-neutral-500">Loading score breakdown...</p>
          ) : scoreResult ? (
            <div className="mb-4">
              <div className="flex items-center gap-4 mb-3">
                <div>
                  <span className="text-xs text-neutral-500">Overall Score</span>
                  <p className="text-lg font-semibold text-neutral-900">
                    {(scoreResult.score * 100).toFixed(1)}%
                  </p>
                </div>
                <div>
                  <span className="text-xs text-neutral-500">Disposition</span>
                  <p className="text-sm font-medium text-neutral-900">{scoreResult.disposition}</p>
                </div>
              </div>
              <div>
                <span className="text-xs text-neutral-500">Field Scores</span>
                <pre className="mt-1 text-xs font-mono bg-neutral-50 p-3 rounded-[8px] border border-neutral-100 overflow-x-auto">
                  {scoreResult.fieldScores}
                </pre>
              </div>
            </div>
          ) : (
            <p className="text-sm text-neutral-500 mb-4">Score breakdown unavailable</p>
          )}

          {activeStatus === "PENDING" && (
            <div className="flex gap-2 pt-4 border-t border-neutral-100">
              <button
                onClick={handleMerge}
                disabled={actionLoading}
                className="px-4 py-2 text-sm font-medium text-white bg-brand-primary rounded-[8px] hover:bg-brand-primary/90 disabled:opacity-50"
              >
                {actionLoading ? "Processing..." : "Merge Records"}
              </button>
              <button
                onClick={handleReject}
                disabled={actionLoading}
                className="px-4 py-2 text-sm font-medium text-danger bg-danger/10 rounded-[8px] hover:bg-danger/20 disabled:opacity-50"
              >
                {actionLoading ? "Processing..." : "Reject (Not Duplicate)"}
              </button>
            </div>
          )}
        </div>
      )}

      {/* Cases table */}
      <div className="bg-card rounded-[12px] shadow-subtle border border-neutral-100 overflow-hidden">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-neutral-100 bg-neutral-50">
              <th className="px-4 py-3 text-left font-medium text-neutral-500">Case ID</th>
              <th className="px-4 py-3 text-left font-medium text-neutral-500">Candidate A</th>
              <th className="px-4 py-3 text-left font-medium text-neutral-500">Candidate B</th>
              <th className="px-4 py-3 text-left font-medium text-neutral-500">Score</th>
              <th className="px-4 py-3 text-left font-medium text-neutral-500">Risk</th>
              <th className="px-4 py-3 text-left font-medium text-neutral-500">Assigned To</th>
              <th className="px-4 py-3 text-left font-medium text-neutral-500">Created At</th>
              <th className="px-4 py-3 text-right font-medium text-neutral-500">Actions</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td colSpan={8} className="px-4 py-8 text-center text-neutral-500">Loading...</td>
              </tr>
            ) : cases.length === 0 ? (
              <tr>
                <td colSpan={8} className="px-4 py-8 text-center text-neutral-500">
                  No {activeStatus.toLowerCase()} dedup cases found
                </td>
              </tr>
            ) : (
              cases.map((dedupCase) => (
                <tr key={dedupCase.id} className="border-b border-neutral-50 hover:bg-neutral-50">
                  <td className="px-4 py-3 font-mono text-xs">{dedupCase.id}</td>
                  <td className="px-4 py-3 font-mono text-xs">{dedupCase.candidateA.substring(0, 8)}...</td>
                  <td className="px-4 py-3 font-mono text-xs">{dedupCase.candidateB.substring(0, 8)}...</td>
                  <td className="px-4 py-3">
                    <span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${
                      dedupCase.matchScore >= 0.9
                        ? "bg-success/10 text-success"
                        : dedupCase.matchScore >= 0.8
                        ? "bg-warning/10 text-warning"
                        : "bg-neutral-100 text-neutral-900"
                    }`}>
                      {(dedupCase.matchScore * 100).toFixed(1)}%
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    {dedupCase.risk ? (
                      <span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${riskBadge(dedupCase.risk)}`}>
                        {dedupCase.risk}
                      </span>
                    ) : (
                      <span className="text-neutral-400">—</span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-neutral-500">{dedupCase.assignedTo ?? "—"}</td>
                  <td className="px-4 py-3 text-neutral-500">
                    {new Date(dedupCase.createdAt).toLocaleDateString()}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <button
                      onClick={() => openReview(dedupCase)}
                      className="px-3 py-1 text-xs font-medium text-white bg-brand-primary rounded-[8px] hover:bg-brand-primary/90"
                    >
                      Review
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
