package zw.gov.mohcc.impilo.tuso.persistence.entity;

public enum FacilityRegulatoryStatus {
    DRAFT,
    APPLICATION_IN_PROGRESS,
    UNDER_INITIAL_REVIEW,
    PENDING_INSPECTION,
    INSPECTION_IN_PROGRESS,
    PENDING_RECTIFICATION,
    PENDING_COMMITTEE_REVIEW,
    APPROVED_FOR_REGISTRATION,
    REGISTERED_ACTIVE,
    RENEWAL_DUE,
    RENEWAL_IN_PROGRESS,
    RESTRICTED,
    SUSPENDED,
    PENDING_CLOSURE,
    CLOSED,
    VOLUNTARILY_CLOSED
}
