package zw.gov.mohcc.impilo.costa.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.Ordered;
import zw.gov.mohcc.impilo.security.ratelimit.RateLimitGuard;
import zw.gov.mohcc.impilo.security.secrets.EnvSecretProvider;
import zw.gov.mohcc.impilo.security.secrets.SecretProvider;
import zw.gov.mohcc.impilo.shared.security.RateLimitFilter;
import zw.gov.mohcc.impilo.shared.security.SecurityBaselineExceptionHandler;

/** Wave 14 security baseline (rate limit; v1.1 domain outbox handles audit events). Generated by emit-security-baseline-config.mjs */
@Configuration
public class SecurityBaselineConfig {

    // Capacity and refill are properties so a test profile can widen the bucket: it is
    // in-memory and keyed by actor, and every MockMvc request in a Spring test context
    // presents the same actor, so a suite of more than 100 requests throttles itself.
    // Defaults are this service's own previous values -- runtime behaviour is unchanged.
    @Bean
    public RateLimitGuard rateLimitGuard(
            @Value("${impilo.security.rate-limit.max-tokens:100}") long maxTokens,
            @Value("${impilo.security.rate-limit.refill-per-second:2}") long refillPerSecond) {
        return new RateLimitGuard(maxTokens, refillPerSecond);
    }

    @Bean
    public FilterRegistrationBean<RateLimitFilter> rateLimitFilter(RateLimitGuard guard) {
        FilterRegistrationBean<RateLimitFilter> registration = new FilterRegistrationBean<>();
        registration.setFilter(new RateLimitFilter(guard));
        registration.addUrlPatterns("/v1/*", "/internal/v1/*");
        registration.setOrder(Ordered.HIGHEST_PRECEDENCE + 5);
        return registration;
    }

    @Bean
    public SecretProvider secretProvider() {
        return new EnvSecretProvider("IMPILO_COSTINGENGINE_");
    }

    @Bean
    public SecurityBaselineExceptionHandler securityBaselineExceptionHandler() {
        return new SecurityBaselineExceptionHandler();
    }
}
