-- Appointment / booking two-way comms templates (citizen + provider)

INSERT INTO ns_templates (id, tenant_id, pod_id, key, channel, name, subject, content, enabled, status, current_version, created_at, updated_at)
VALUES
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_REQUESTED', 'IN_APP',
 'Appointment request received', 'Booking request received',
 'Your {{appointmentType}} request at {{facilityName}} for {{scheduledAt}} is pending confirmation. Ref {{bookingNumber}}.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_REQUESTED_SMS', 'SMS',
 'Appointment request SMS', 'Impilo booking request',
 'Impilo: your appointment request for {{scheduledAt}} at {{facilityName}} is pending. Ref {{bookingNumber}}.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_CONFIRMED', 'IN_APP',
 'Appointment confirmed', 'Appointment confirmed',
 'Your {{appointmentType}} with {{providerName}} at {{facilityName}} is confirmed for {{scheduledAt}}.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_CONFIRMED_SMS', 'SMS',
 'Appointment confirmed SMS', 'Impilo appointment confirmed',
 'Impilo: appointment confirmed {{scheduledAt}} at {{facilityName}} with {{providerName}}.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_CANCELLED', 'IN_APP',
 'Appointment cancelled', 'Appointment cancelled',
 'Your appointment on {{scheduledAt}} at {{facilityName}} was cancelled. {{reason}}',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_RESCHEDULED', 'IN_APP',
 'Appointment rescheduled', 'Appointment rescheduled',
 'Your appointment was rescheduled to {{scheduledAt}} at {{facilityName}} with {{providerName}}.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_RESCHEDULED_SMS', 'SMS',
 'Appointment rescheduled SMS', 'Impilo rescheduled',
 'Impilo: appointment rescheduled to {{scheduledAt}} at {{facilityName}}.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_REMINDER', 'IN_APP',
 'Appointment reminder', 'Appointment reminder',
 'Reminder: {{appointmentType}} tomorrow at {{scheduledAt}} — {{facilityName}}. Open Impilo to check in.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_REMINDER_SMS', 'SMS',
 'Appointment reminder SMS', 'Impilo appointment reminder',
 'Impilo reminder: appointment {{scheduledAt}} at {{facilityName}}. Arrive early to check in.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_CHECKED_IN', 'IN_APP',
 'Checked in', 'You are checked in',
 'You are checked in for your appointment at {{facilityName}}. Please proceed to the queue.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_MESSAGE', 'IN_APP',
 'Message from provider', 'Provider message',
 '{{providerName}}: {{message}}',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_CITIZEN_MESSAGE_SMS', 'SMS',
 'Provider message SMS', 'Impilo provider message',
 '{{providerName}}: {{message}}',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_PROVIDER_NEW_REQUEST', 'PUSH',
 'New booking request', 'New booking request',
 'New {{appointmentType}} request from {{patientCpid}} for {{scheduledAt}} at {{facilityName}}. Ref {{bookingNumber}}.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_PROVIDER_CANCELLED', 'PUSH',
 'Appointment cancelled by patient', 'Patient cancelled',
 'Patient {{patientCpid}} cancelled appointment {{scheduledAt}}. Reason: {{reason}}',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_PROVIDER_CHECKED_IN', 'PUSH',
 'Patient checked in', 'Patient checked in',
 '{{patientCpid}} checked in for {{scheduledAt}} appointment at {{facilityName}}.',
 true, 'PUBLISHED', 1, NOW(), NOW()),
(gen_random_uuid()::text, 'tenant-moh-zw', 'national', 'APPOINTMENT_PROVIDER_MESSAGE', 'PUSH',
 'Patient message', 'Patient message',
 'Message from {{patientCpid}} about appointment {{scheduledAt}}: {{message}}',
 true, 'PUBLISHED', 1, NOW(), NOW())
ON CONFLICT DO NOTHING;
