import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { NextRequest } from "next/server";
import { isPublicPath, middleware, PUBLIC_PREFIXES } from "./middleware";

describe("isPublicPath (G-CZO-02 public L0 entry)", () => {
  it("treats the public welcome surface as reachable without a session", () => {
    expect(isPublicPath("/welcome")).toBe(true);
    expect(isPublicPath("/welcome/find-care")).toBe(true);
    expect(isPublicPath("/welcome/emergency")).toBe(true);
    expect(isPublicPath("/welcome/accessibility")).toBe(true);
  });

  it("lets the root through so it can decide welcome-vs-home by session", () => {
    expect(isPublicPath("/")).toBe(true);
  });

  it("keeps unified public information, participation and professional entry open", () => {
    for (const path of [
      "/about",
      "/contact",
      "/get-involved",
      "/download",
      "/provider/get-access",
      "/services",
      "/technical",
      "/.well-known/assetlinks.json",
    ]) {
      expect(isPublicPath(path)).toBe(true);
    }
  });

  it("keeps authenticated surfaces gated", () => {
    expect(isPublicPath("/home")).toBe(false);
    expect(isPublicPath("/citizen/health-id/request")).toBe(false);
    expect(isPublicPath("/settings/privacy")).toBe(false);
  });

  it("preserves the pre-existing public prefixes", () => {
    for (const prefix of ["/auth", "/verify", "/share", "/privacy", "/terms", "/consent"]) {
      expect(PUBLIC_PREFIXES).toContain(prefix);
      expect(isPublicPath(prefix + "/anything")).toBe(true);
    }
  });
});

describe("middleware double-slash normalization", () => {
  it("redirects duplicate-slash paths to the collapsed path", () => {
    const req = new NextRequest("https://impilo.mohcc.gov.zw//telemedicine/session/abc");
    const res = middleware(req);
    expect(res.status).toBe(307);
    expect(new URL(res.headers.get("location")!).pathname).toBe("/telemedicine/session/abc");
  });

  it("collapses runs of slashes anywhere in the path", () => {
    const req = new NextRequest("https://impilo.mohcc.gov.zw/telemedicine//session///abc");
    const res = middleware(req);
    expect(res.status).toBe(307);
    expect(new URL(res.headers.get("location")!).pathname).toBe("/telemedicine/session/abc");
  });

  it("leaves clean paths alone (session gate still applies)", () => {
    const req = new NextRequest("https://impilo.mohcc.gov.zw/telemedicine/session/abc");
    const res = middleware(req);
    // No session cookie → login redirect, NOT a slash-normalization redirect.
    expect(new URL(res.headers.get("location")!).pathname).toBe("/auth/login");
  });
});

describe("the manifest the app actually declares is publicly reachable", () => {
  // This pair drifted and it cost a login. PUBLIC_FILES listed `/manifest.json`, a file this app
  // has never served, while `layout.tsx` declares `/manifest.webmanifest` (generated by
  // src/app/manifest.ts). The real manifest was therefore gated, the guard redirected it to
  // `/auth/login?returnTo=/manifest.webmanifest`, and the post-login destination became a JSON
  // document. The user saw "signed in but went nowhere" -- a symptom with no manifest in it.
  //
  // Asserted against layout.tsx rather than a hardcoded string: a test that repeated the literal
  // would have passed against the broken version, which is exactly what the previous suite did.
  it("PUBLIC_FILES contains whatever layout.tsx declares as the manifest", () => {
    const layout = readFileSync(
      join(__dirname, "app", "layout.tsx"),
      "utf8",
    );
    const declared = layout.match(/manifest:\s*"([^"]+)"/)?.[1];
    expect(declared, "layout.tsx no longer declares a manifest - update this test").toBeTruthy();

    const middlewareSrc = readFileSync(join(__dirname, "middleware.ts"), "utf8");
    // No `/s` flag: dotAll only changes what `.` matches, and this pattern has no `.`.
    // `[^\]]*` already spans newlines by itself, so the flag was doing nothing — while
    // costing a compile error under the repo's `target: es2017` (TS1501: dotAll requires
    // es2018+). Removing it is behaviour-identical; verified by capturing the same bytes.
    const publicFiles = middlewareSrc.match(/const PUBLIC_FILES = \[([^\]]*)\]/)?.[1] ?? "";
    expect(publicFiles, "PUBLIC_FILES not found - the constant was renamed").not.toEqual("");

    expect(
      publicFiles.includes(`"${declared}"`),
      `layout.tsx declares ${declared} but PUBLIC_FILES does not exempt it, so the browser's ` +
        `own manifest fetch is auth-gated and poisons returnTo`,
    ).toBe(true);
  });
});
