apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: execution-cell-policy
  namespace: impilo-execution
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: impilo-gateway
    - namespaceSelector:
        matchLabels:
          plane: registry-spine
    - podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: impilo-infra
    - namespaceSelector:
        matchLabels:
          plane: registry-spine
    - podSelector: {}
