apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: integration-ops-policy
  namespace: impilo-ops
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: impilo-gateway
    - namespaceSelector:
        matchLabels:
          plane: trust-governance
    - namespaceSelector:
        matchLabels:
          plane: registry-spine
    - namespaceSelector:
        matchLabels:
          plane: clinical-execution
    - namespaceSelector:
        matchLabels:
          plane: finance
    - podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: impilo-infra
    - namespaceSelector:
        matchLabels:
          plane: trust-governance
    - namespaceSelector:
        matchLabels:
          plane: registry-spine
    - namespaceSelector:
        matchLabels:
          plane: clinical-execution
    - podSelector: {}
