apiVersion: v1
kind: Service
metadata:
  name: {{ include "share-slip.fullname" . }}
  labels:
    {{- include "share-slip.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "share-slip.selectorLabels" . | nindent 4 }}
