package zw.gov.mohcc.impilo.telemonitoring.events;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Profile;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import zw.gov.mohcc.impilo.shared.auth.TrustContext;
import zw.gov.mohcc.impilo.shared.auth.TrustContextHolder;
import zw.gov.mohcc.impilo.telemonitoring.core.MonitoringPlanService;
import zw.gov.mohcc.impilo.telemonitoring.persistence.repository.MonitoringPlanRepository;

import java.util.Locale;
import java.util.UUID;

/**
 * OROS enrolment seam (§14.2): consumes {@code oros.order.placed} and creates a DRAFT
 * monitoring plan for MONITORING enrolment orders.
 *
 * <h3>Discriminator (OD-16 interim, config-driven)</h3>
 * <p>The {@code oros.order.placed} payload is the serialized OROS OrderEntity — its shape
 * is frozen and {@code OrderType} has no MONITORING value yet (OD-16 pending). The
 * discriminator therefore is: {@code orderType == OTHER} AND the order's
 * {@code ziboOrderCode} — or, failing that, any {@code items[].code} — starts with the
 * configured prefix ({@code telemonitoring.enrolment.order-code-prefix}, default
 * {@code TM-MON}). The programme code is the remainder after the prefix and a separator,
 * e.g. {@code TM-MON-HYPERTENSION -> HYPERTENSION}. When OD-16 lands a dedicated
 * OrderType, only this class changes.</p>
 *
 * <p>Idempotent on {@code orosOrderId} (repository check + partial unique index).
 * The created plan is DRAFT only — activation always requires clinician approval, and no
 * patient notification is generated by this seam.</p>
 */
@Service
@Profile("!test")
public class OrosEnrolmentConsumer {

    private static final Logger log = LoggerFactory.getLogger(OrosEnrolmentConsumer.class);

    private final MonitoringPlanService planService;
    private final MonitoringPlanRepository planRepository;
    private final ObjectMapper objectMapper;
    private final String orderCodePrefix;

    public OrosEnrolmentConsumer(MonitoringPlanService planService,
                                 MonitoringPlanRepository planRepository,
                                 ObjectMapper objectMapper,
                                 @Value("${telemonitoring.enrolment.order-code-prefix:TM-MON}") String orderCodePrefix) {
        this.planService = planService;
        this.planRepository = planRepository;
        this.objectMapper = objectMapper;
        this.orderCodePrefix = orderCodePrefix;
    }

    @KafkaListener(topics = "oros.order.placed", groupId = "telemonitoring-service")
    @Transactional
    public void consumeOrosOrder(String message) {
        try {
            JsonNode event = objectMapper.readTree(message);

            // Filter 1: OrderType OTHER (MONITORING pending OD-16).
            String orderType = text(event, "orderType");
            if (!"OTHER".equalsIgnoreCase(orderType)) {
                log.debug("Skipping non-OTHER order: type={}", orderType);
                return;
            }

            // Filter 2: MONITORING order-code discriminator.
            String monitoringCode = extractMonitoringCode(event);
            if (monitoringCode == null) {
                log.debug("Skipping OTHER order without monitoring order-code prefix '{}'", orderCodePrefix);
                return;
            }

            String orosOrderId = text(event, "orderId");
            if (orosOrderId == null) {
                log.warn("OROS order event missing orderId, skipping");
                return;
            }

            // Idempotency: at most one plan per enrolment order.
            if (planRepository.findByOrosOrderId(orosOrderId).isPresent()) {
                log.debug("OROS enrolment order {} already processed, skipping", orosOrderId);
                return;
            }

            String tenantId = text(event, "tenantId");
            String patientCpid = text(event, "patientCpid");
            if (tenantId == null || patientCpid == null) {
                log.warn("OROS enrolment order {} missing tenantId or patientCpid, skipping", orosOrderId);
                return;
            }

            String facilityId = text(event, "facilityId");
            TrustContext ctx = new TrustContext(
                    UUID.fromString(tenantId),
                    "OROS-SYSTEM",
                    "SYSTEM",
                    "TELEMONITORING_ENROLMENT",
                    null,
                    UUID.randomUUID(),
                    facilityId != null ? UUID.fromString(facilityId) : null,
                    null,
                    null,
                    null);
            TrustContextHolder.set(ctx);
            try {
                String programmeCode = deriveProgrammeCode(monitoringCode);
                planService.createDraft(new MonitoringPlanService.CreatePlanCommand(
                        UUID.fromString(tenantId),
                        patientCpid,
                        programmeCode,
                        orosOrderId,
                        text(event, "clinicalNotes"),
                        null,
                        null,
                        null,
                        null,
                        suggestedBy(event),
                        suggestedSystemVersion(event),
                        text(event, "placedBy")), false);
                log.info("DRAFT monitoring plan created from OROS enrolment order {} (programme={}, patient={})",
                        orosOrderId, programmeCode, patientCpid);
            } finally {
                TrustContextHolder.clear();
            }
        } catch (JsonProcessingException e) {
            log.error("Failed to parse OROS order event: {}", e.getMessage(), e);
        }
    }

    /**
     * Returns the matched monitoring order code (the ziboOrderCode or item code carrying
     * the prefix), or null when the order is not a monitoring enrolment.
     */
    String extractMonitoringCode(JsonNode event) {
        String zibo = text(event, "ziboOrderCode");
        if (matches(zibo)) {
            return zibo;
        }
        JsonNode items = event.get("items");
        if (items != null && items.isArray()) {
            for (JsonNode item : items) {
                String code = text(item, "code");
                if (matches(code)) {
                    return code;
                }
            }
        }
        return null;
    }

    private boolean matches(String code) {
        return code != null && code.toUpperCase(Locale.ROOT).startsWith(orderCodePrefix.toUpperCase(Locale.ROOT));
    }

    /** {@code TM-MON-HYPERTENSION -> HYPERTENSION}; a bare {@code TM-MON} yields {@code UNSPECIFIED}. */
    String deriveProgrammeCode(String monitoringCode) {
        String remainder = monitoringCode.substring(orderCodePrefix.length());
        while (remainder.startsWith("-") || remainder.startsWith("_") || remainder.startsWith(":")) {
            remainder = remainder.substring(1);
        }
        return remainder.isBlank() ? "UNSPECIFIED" : remainder.toUpperCase(Locale.ROOT);
    }

    /** Automated-suggestion provenance rides externalRefs (same carriage as prescriptionClaimId, OF-B12). */
    private String suggestedBy(JsonNode event) {
        return externalRef(event, "suggestedBy");
    }

    private String suggestedSystemVersion(JsonNode event) {
        return externalRef(event, "suggestedSystemVersion");
    }

    private String externalRef(JsonNode event, String key) {
        String externalRefs = text(event, "externalRefs");
        if (externalRefs == null || externalRefs.isBlank()) {
            return null;
        }
        try {
            JsonNode refs = objectMapper.readTree(externalRefs);
            return text(refs, key);
        } catch (JsonProcessingException e) {
            log.warn("Unparseable externalRefs on OROS order {}: {}", text(event, "orderId"), e.getMessage());
            return null;
        }
    }

    private static String text(JsonNode node, String fieldName) {
        JsonNode field = node.get(fieldName);
        return (field != null && !field.isNull()) ? field.asText() : null;
    }
}
