replicaCount: 1

image:
  repository: ghcr.io/mohcc/impilo/product-registry
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8097

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
