package zw.gov.mohcc.impilo.experience.controller;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.HttpStatusCodeException;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.web.bind.annotation.*;
import zw.gov.mohcc.impilo.companion.context.CompanionHeaders;
import zw.gov.mohcc.impilo.experience.client.MsikaFlowServiceClient;
import zw.gov.mohcc.impilo.experience.client.MsikaServiceClient;

import java.util.*;

/**
 * Marketplace endpoints. Delegates to MsikaFlowServiceClient.
 * GET  /internal/v1/marketplace/orders — list marketplace orders with facility_id filter, pagination.
 * GET  /internal/v1/marketplace/orders/{id} — get single order.
 * POST /internal/v1/marketplace/orders — create order.
 */
@RestController
@RequestMapping("/internal/v1/marketplace")
public class MarketplaceController {

    private static final Logger log = LoggerFactory.getLogger(MarketplaceController.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private final MsikaFlowServiceClient msikaFlowClient;
    private final MsikaServiceClient msikaServiceClient;

    public MarketplaceController(MsikaFlowServiceClient msikaFlowClient, MsikaServiceClient msikaServiceClient) {
        this.msikaFlowClient = msikaFlowClient;
        this.msikaServiceClient = msikaServiceClient;
    }

    /**
     * Order identity (order number) is server-generated by msika-flow — clients
     * must not fabricate it. {@code order_type} defaults to OTC_PRODUCT_ORDER.
     * Unknown fields are ignored so older clients (e.g. ones still sending
     * order_number) degrade gracefully instead of 500ing.
     */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    public record CreateOrderRequest(
            @NotBlank String facility_id,
            String order_type,
            JsonNode items,
            String ordered_by
    ) {}

    private static final Set<String> ALLOWED_ORDER_TYPES = Set.of(
            "OTC_PRODUCT_ORDER", "RX_FULFILLMENT_ORDER", "SERVICE_BOOKING_ORDER", "BUNDLE_ORDER");

    @GetMapping("/orders")
    public ResponseEntity<Map<String, Object>> listOrders(
            @RequestHeader(CompanionHeaders.TENANT_ID) String tenantId,
            @RequestHeader(CompanionHeaders.REQUEST_ID) String requestId,
            @RequestHeader(CompanionHeaders.CORRELATION_ID) String correlationId,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(required = false, name = "facility_id") String facilityId) {
        try {
            ResponseEntity<String> result = msikaFlowClient.listOrders(page, size, facilityId);
            JsonNode data = unwrapUpstreamData(result.getBody());
            List<Map<String, Object>> resources = new ArrayList<>();
            if (data != null && data.has("items") && data.get("items").isArray()) {
                data.get("items").forEach(item -> resources.add(orderResource(item)));
            }
            return ResponseEntity.status(result.getStatusCode()).body(Map.of(
                    "data", resources,
                    "meta", Map.of("request_id", requestId, "correlation_id", correlationId)));
        } catch (HttpStatusCodeException e) {
            return envelope(e, requestId, correlationId);
        } catch (Exception e) {
            log.warn("MSIKA Flow unavailable for order list: {}", e.getMessage());
            return unavailable502(
                    "MSIKA_FLOW_UNAVAILABLE",
                    "Unable to list marketplace orders while msika-flow-service is unavailable",
                    requestId, correlationId);
        }
    }

    @GetMapping("/catalog")
    public ResponseEntity<Map<String, Object>> listCatalog(
            @RequestHeader(CompanionHeaders.TENANT_ID) String tenantId,
            @RequestHeader(CompanionHeaders.REQUEST_ID) String requestId,
            @RequestHeader(CompanionHeaders.CORRELATION_ID) String correlationId,
            @RequestParam(required = false) String category,
            @RequestParam(required = false) String search) {

        LinkedMultiValueMap<String, String> params = new LinkedMultiValueMap<>();
        if (search != null && !search.isBlank()) {
            params.add("q", search);
        }
        if (category != null && !category.isBlank()) {
            params.add("kind", category);
        }
        params.add("page", "0");
        params.add("size", "50");

        try {
            ResponseEntity<String> result = msikaServiceClient.search(params);
            return envelope(result, requestId, correlationId);
        } catch (HttpStatusCodeException e) {
            return envelope(e, requestId, correlationId);
        } catch (Exception e) {
            return unavailable502(
                    "MSIKA_SERVICE_UNAVAILABLE",
                    "Unable to load marketplace catalog while msika-service is unavailable",
                    requestId, correlationId);
        }
    }

    @GetMapping("/vendors")
    public ResponseEntity<Map<String, Object>> listPartners(
            @RequestHeader(CompanionHeaders.TENANT_ID) String tenantId,
            @RequestHeader(CompanionHeaders.REQUEST_ID) String requestId,
            @RequestHeader(CompanionHeaders.CORRELATION_ID) String correlationId) {

        try {
            ResponseEntity<String> result = msikaFlowClient.listVendors(null);
            return envelope(result, requestId, correlationId);
        } catch (HttpStatusCodeException e) {
            return envelope(e, requestId, correlationId);
        } catch (Exception e) {
            return unavailable502(
                    "MSIKA_FLOW_UNAVAILABLE",
                    "Unable to load marketplace vendors while msika-flow-service is unavailable",
                    requestId, correlationId);
        }
    }

    @GetMapping("/bookings")
    public ResponseEntity<Map<String, Object>> listBookings(
            @RequestHeader(CompanionHeaders.TENANT_ID) String tenantId,
            @RequestHeader(CompanionHeaders.REQUEST_ID) String requestId,
            @RequestHeader(CompanionHeaders.CORRELATION_ID) String correlationId,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size) {
        try {
            ResponseEntity<String> result = msikaFlowClient.listBookings(page, size);
            return envelope(result, requestId, correlationId);
        } catch (HttpStatusCodeException e) {
            return envelope(e, requestId, correlationId);
        } catch (Exception e) {
            return unavailable502(
                    "MSIKA_FLOW_UNAVAILABLE",
                    "Unable to load marketplace bookings while msika-flow-service is unavailable",
                    requestId, correlationId);
        }
    }

    @GetMapping("/orders/{id}")
    public ResponseEntity<Map<String, Object>> getOrder(
            @PathVariable String id,
            @RequestHeader(CompanionHeaders.TENANT_ID) String tenantId,
            @RequestHeader(CompanionHeaders.REQUEST_ID) String requestId,
            @RequestHeader(CompanionHeaders.CORRELATION_ID) String correlationId) {

        try {
            ResponseEntity<String> result = msikaFlowClient.getOrder(id);
            JsonNode data = unwrapUpstreamData(result.getBody());
            return ResponseEntity.status(result.getStatusCode()).body(Map.of(
                    "data", data != null ? orderResource(data) : Map.of(),
                    "meta", Map.of("request_id", requestId, "correlation_id", correlationId)));
        } catch (HttpStatusCodeException e) {
            return envelope(e, requestId, correlationId);
        } catch (Exception e) {
            return unavailable502(
                    "MSIKA_FLOW_UNAVAILABLE",
                    "Unable to fetch marketplace order while msika-flow-service is unavailable",
                    requestId, correlationId);
        }
    }

    @PostMapping("/orders")
    public ResponseEntity<Map<String, Object>> createOrder(
            @RequestHeader(CompanionHeaders.TENANT_ID) String tenantId,
            @RequestHeader(CompanionHeaders.POD_ID) String podId,
            @RequestHeader(CompanionHeaders.REQUEST_ID) String requestId,
            @RequestHeader(CompanionHeaders.CORRELATION_ID) String correlationId,
            @RequestHeader(value = CompanionHeaders.IDEMPOTENCY_KEY, required = false) String idempotencyKey,
            @Valid @RequestBody CreateOrderRequest request) {

        String orderType = request.order_type() != null && !request.order_type().isBlank()
                ? request.order_type() : "OTC_PRODUCT_ORDER";
        if (!ALLOWED_ORDER_TYPES.contains(orderType)) {
            return ResponseEntity.badRequest().body(Map.of(
                    "error", Map.of("code", "INVALID_ORDER_TYPE",
                            "message", "order_type must be one of " + ALLOWED_ORDER_TYPES),
                    "meta", Map.of("request_id", requestId, "correlation_id", correlationId)));
        }

        ObjectNode orderBody = MAPPER.createObjectNode();
        orderBody.put("orderType", orderType);
        orderBody.put("facilityId", request.facility_id());
        if (idempotencyKey != null && !idempotencyKey.isBlank()) {
            orderBody.put("idempotencyKey", idempotencyKey);
        }
        ArrayNode lines = orderBody.putArray("lines");
        if (request.items() != null && request.items().isArray()) {
            request.items().forEach(item -> {
                ObjectNode line = lines.addObject();
                line.put("msikaCoreCode", item.path("productId").asText(""));
                line.put("qty", Math.max(item.path("quantity").asInt(1), 1));
                if (item.hasNonNull("unitPrice")) {
                    line.put("unitPrice", item.get("unitPrice").decimalValue());
                }
                if (item.hasNonNull("description")) {
                    // mf_order_lines.metadata is a Postgres json column — a bare
                    // string is rejected ("invalid input syntax for type json").
                    line.put("metadata", MAPPER.createObjectNode()
                            .put("description", item.get("description").asText()).toString());
                }
            });
        }

        try {
            ResponseEntity<String> result = msikaFlowClient.createOrder(orderBody.toString());
            JsonNode data = unwrapUpstreamData(result.getBody());
            return ResponseEntity.status(result.getStatusCode()).body(Map.of(
                    "data", data != null ? orderResource(data) : Map.of(),
                    "meta", Map.of("request_id", requestId, "correlation_id", correlationId)));
        } catch (HttpStatusCodeException e) {
            return envelope(e, requestId, correlationId);
        } catch (Exception e) {
            log.warn("MSIKA Flow unavailable for order create: {}", e.getMessage());
            return unavailable502(
                    "MSIKA_FLOW_UNAVAILABLE",
                    "Unable to create marketplace order while msika-flow-service is unavailable",
                    requestId, correlationId);
        }
    }

    /** Line metadata may be a JSON object string ({"description":...}) or legacy plain text. */
    private static String lineDescription(JsonNode metadata) {
        if (metadata == null || metadata.isMissingNode() || metadata.isNull()) {
            return "";
        }
        String raw = metadata.asText("");
        if (raw.startsWith("{")) {
            try {
                JsonNode parsed = MAPPER.readTree(raw);
                if (parsed.hasNonNull("description")) {
                    return parsed.get("description").asText();
                }
            } catch (Exception ignored) {
                // fall through to raw text
            }
        }
        return raw;
    }

    /** msika-flow wraps payloads as {success, data, error, correlationId}; returns the data node. */
    private JsonNode unwrapUpstreamData(String body) {
        if (body == null || body.isBlank()) {
            return null;
        }
        try {
            JsonNode root = MAPPER.readTree(body);
            return root.hasNonNull("data") ? root.get("data") : root;
        } catch (Exception e) {
            log.warn("Unparseable msika-flow response: {}", e.getMessage());
            return null;
        }
    }

    /** Shape one msika-flow OrderView into the experience order resource. */
    private Map<String, Object> orderResource(JsonNode view) {
        String orderId = view.path("orderId").asText("");
        List<Map<String, Object>> items = new ArrayList<>();
        if (view.has("lines") && view.get("lines").isArray()) {
            view.get("lines").forEach(line -> {
                Map<String, Object> item = new LinkedHashMap<>();
                item.put("productId", line.path("msikaCoreCode").asText(""));
                item.put("description", lineDescription(line.path("metadata")));
                item.put("quantity", line.path("qty").asInt(0));
                item.put("unitPrice", line.path("unitPrice").isNumber() ? line.get("unitPrice").decimalValue() : 0);
                items.add(item);
            });
        }

        Map<String, Object> attributes = new LinkedHashMap<>();
        attributes.put("facility_id", view.path("facilityId").asText(null));
        attributes.put("vendor_id", view.hasNonNull("vendorId") ? view.get("vendorId").asText() : null);
        // Server-generated order identity — the orderId doubles as the order number.
        attributes.put("order_number", orderId);
        attributes.put("status", view.path("status").asText(""));
        attributes.put("total_amount", view.path("amountTotal").isNumber() ? view.get("amountTotal").decimalValue() : 0);
        attributes.put("currency", view.hasNonNull("currency") ? view.get("currency").asText() : "USD");
        attributes.put("items", items);
        attributes.put("ordered_by", view.path("actorId").asText(""));
        attributes.put("ordered_at", view.hasNonNull("createdAt") ? view.get("createdAt").asText() : null);
        attributes.put("delivered_at", null);
        attributes.put("created_at", view.hasNonNull("createdAt") ? view.get("createdAt").asText() : null);
        attributes.put("updated_at", view.hasNonNull("updatedAt") ? view.get("updatedAt").asText() : null);

        Map<String, Object> resource = new LinkedHashMap<>();
        resource.put("id", orderId);
        resource.put("type", "marketplace-order");
        resource.put("attributes", attributes);
        return resource;
    }

    private ResponseEntity<Map<String, Object>> envelope(ResponseEntity<String> upstream, String requestId, String correlationId) {
        Map<String, Object> response = new LinkedHashMap<>();
        response.put("data", upstream.getBody());
        response.put("meta", Map.of("request_id", requestId, "correlation_id", correlationId));
        return ResponseEntity.status(upstream.getStatusCode()).body(response);
    }

    private ResponseEntity<Map<String, Object>> envelope(HttpStatusCodeException upstream, String requestId, String correlationId) {
        Map<String, Object> response = new LinkedHashMap<>();
        response.put("data", upstream.getResponseBodyAsString());
        response.put("meta", Map.of("request_id", requestId, "correlation_id", correlationId));
        return ResponseEntity.status(upstream.getStatusCode()).body(response);
    }

    private ResponseEntity<Map<String, Object>> unavailable502(String code, String message, String requestId, String correlationId) {
        return ResponseEntity.status(HttpStatus.BAD_GATEWAY).body(Map.of(
                "error", Map.of("code", code, "message", message),
                "meta", Map.of("request_id", requestId, "correlation_id", correlationId)));
    }

    private ResponseEntity<Map<String, Object>> unavailable501(String code, String message, String requestId, String correlationId) {
        return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).body(Map.of(
                "error", Map.of("code", code, "message", message),
                "meta", Map.of("request_id", requestId, "correlation_id", correlationId)));
    }
}
