package zw.gov.mohcc.impilo.datagovernance.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.Ordered;
import zw.gov.mohcc.impilo.security.ratelimit.RateLimitGuard;
import zw.gov.mohcc.impilo.security.secrets.EnvSecretProvider;
import zw.gov.mohcc.impilo.security.secrets.SecretProvider;
import zw.gov.mohcc.impilo.shared.security.RateLimitFilter;
import zw.gov.mohcc.impilo.shared.security.SecurityBaselineExceptionHandler;

/** Wave 14 security baseline (rate limit; v1.1 domain outbox handles audit events). Generated by emit-security-baseline-config.mjs */
@Configuration
public class SecurityBaselineConfig {

    /**
     * Capacity and refill are properties defaulting to the baseline 100 tokens / 2 per second, so
     * runtime behaviour is unchanged where nothing sets them.
     *
     * <p>They have to be settable because the bucket is in-memory and keyed by actor — and MockMvc
     * gives every request in a Spring test context the same actor. A suite that makes more than 100
     * requests therefore starts 429ing itself partway through, which is what happened here once
     * DataGovernanceGoldenContractTest joined DeidPipelineMockMvcTest in the same context. The
     * failure lands on whichever test runs after the hundredth request, so it reads as an unrelated
     * assertion failure. The filter stays in the chain under test; only the bucket is widened.
     */
    @Bean
    public RateLimitGuard rateLimitGuard(
            @Value("${impilo.security.rate-limit.max-tokens:100}") long maxTokens,
            @Value("${impilo.security.rate-limit.refill-per-second:2}") long refillPerSecond) {
        return new RateLimitGuard(maxTokens, refillPerSecond);
    }

    @Bean
    public FilterRegistrationBean<RateLimitFilter> rateLimitFilter(RateLimitGuard guard) {
        FilterRegistrationBean<RateLimitFilter> registration = new FilterRegistrationBean<>();
        registration.setFilter(new RateLimitFilter(guard));
        registration.addUrlPatterns("/v1/*", "/internal/v1/*");
        registration.setOrder(Ordered.HIGHEST_PRECEDENCE + 5);
        return registration;
    }

    @Bean
    public SecretProvider secretProvider() {
        return new EnvSecretProvider("IMPILO_DATAGOVERNANCE_");
    }

    @Bean
    public SecurityBaselineExceptionHandler securityBaselineExceptionHandler() {
        return new SecurityBaselineExceptionHandler();
    }
}
