#!/usr/bin/env bash
# =============================================================================
# IATG e2e — seed-output → seed.env bridge.
#
# iatg-e2e-seed.sh prints a machine-parseable block delimited by
#   ----- IATG_E2E_SEED_OUTPUT_BEGIN -----
#   KEY=VALUE
#   ...
#   ----- IATG_E2E_SEED_OUTPUT_END -----
# but does NOT itself write reports/iatg-e2e/seed.env. This bridge reads that
# block from stdin (or a file) and writes an `export KEY="VALUE"` env file that
# iatg-end-to-end-runtime.sh sources via IATG_SEED_ENV.
#
# Only KEY=VALUE lines strictly between the BEGIN/END markers are emitted; any
# surrounding log noise (==> …) is ignored. Exits non-zero if the markers are
# absent or no KEY=VALUE pairs are found, so a broken seed never yields a
# silently-empty env file.
#
# USAGE:
#   bash scripts/seed/iatg-e2e-seed.sh | bash scripts/seed/iatg-seed-to-env.sh
#   bash scripts/seed/iatg-seed-to-env.sh seed-stdout.txt reports/iatg-e2e/seed.env
#
# ARGS:
#   $1  input file (default: stdin)
#   $2  output env file (default: reports/iatg-e2e/seed.env)
# =============================================================================
set -euo pipefail

BEGIN_MARKER='----- IATG_E2E_SEED_OUTPUT_BEGIN -----'
END_MARKER='----- IATG_E2E_SEED_OUTPUT_END -----'

IN_FILE="${1:--}"
OUT_FILE="${2:-reports/iatg-e2e/seed.env}"

if [[ "$IN_FILE" == "-" ]]; then
  input="$(cat)"
else
  [[ -r "$IN_FILE" ]] || { printf 'FAIL: input file not readable: %s\n' "$IN_FILE" >&2; exit 1; }
  input="$(cat "$IN_FILE")"
fi

# Extract KEY=VALUE lines strictly inside the marker block.
block="$(printf '%s\n' "$input" | awk -v b="$BEGIN_MARKER" -v e="$END_MARKER" '
  $0 == b { inblock = 1; next }
  $0 == e { inblock = 0; next }
  inblock && /^[A-Za-z_][A-Za-z0-9_]*=/ { print }
')"

if [[ -z "$block" ]]; then
  printf 'FAIL: no IATG_E2E_SEED_OUTPUT block found (or it was empty) — seed did not complete honestly.\n' >&2
  exit 1
fi

out_dir="$(dirname "$OUT_FILE")"
mkdir -p "$out_dir"

{
  printf '# Generated by iatg-seed-to-env.sh — source via IATG_SEED_ENV.\n'
  while IFS= read -r line; do
    key="${line%%=*}"
    value="${line#*=}"
    printf 'export %s="%s"\n' "$key" "$value"
  done <<< "$block"
} > "$OUT_FILE"

count="$(printf '%s\n' "$block" | wc -l | tr -d ' ')"
printf '==> wrote %s exports to %s\n' "$count" "$OUT_FILE" >&2
