#!/usr/bin/env bash
# Adult Medicine — the ten §23 demonstrations, as far as the record can carry them.
#
# WHAT THIS PROVES, PRECISELY
#
# brief.md §23 asks for ten clinical journeys. A journey has three layers: the RECORD can carry it,
# the SERVICES can execute it, and a CLINICIAN can walk it in the product. This rig proves the FIRST
# layer only, on real Postgres, on a clean database, in migration order.
#
# That is a smaller claim than "the demonstration passes", and saying so is the point. A rig that
# reported ten green journeys because ten rows inserted would be exactly the kind of evidence this
# pack exists to refuse. Each journey below therefore ends with an explicit CANNOT-YET line naming
# what the record cannot express, so the register of what is missing is generated by running the
# thing rather than maintained by hand next to it.
#
# The value of the first layer on its own: a journey the record cannot carry is a journey no amount
# of service or UI work will make possible. Every CANNOT-YET here is a real, ordered dependency.
#
# Usage:  bash scripts/runtime-proof/medicine-demonstrations.sh
#         KEEP_RIG=1 ... to leave the container up for inspection.
set -uo pipefail

REPO_PATH="${REPO_PATH:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "$REPO_PATH"

PG_NAME="medicine-demo-pg-$$"
PG_PORT="${MEDICINE_DEMO_PG_PORT:-25449}"
TENANT="00000000-0000-4000-8000-000000000001"
MIG_DIR="services/pct-service/src/main/resources/db/migration"
EVIDENCE="reports/journeys/medicine-demonstrations-$(date +%Y%m%d-%H%M%S)"

PASS=0; FAIL=0; CANNOT=0
cleanup() {
  if [[ "${KEEP_RIG:-0}" == "1" ]]; then
    echo "KEEP_RIG=1 — leaving $PG_NAME up on port $PG_PORT"
  else
    docker rm -f "$PG_NAME" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

q() { docker exec "$PG_NAME" psql -U impilo -d pct -tAc "$1" 2>&1; }

# psql -tAc on INSERT ... RETURNING prints the returned value AND the command tag ("INSERT 0 1"),
# so a naive capture yields "<uuid> INSERT 0 1" and every later query using it fails on a syntax
# error that looks like a schema problem. Take the UUID and nothing else.
uuid_of() { echo "$1" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1; }

chk() {
  local name="$1" out="$2" expect="$3"
  if echo "$out" | grep -qi -- "$expect"; then
    echo "  PASS    $name"; PASS=$((PASS+1))
  else
    echo "  FAIL    $name"; echo "          expected /$expect/, got: $(echo "$out" | tr '\n' ' ' | cut -c1-200)"
    FAIL=$((FAIL+1))
  fi
}

# Not a failure — a stated, ordered dependency. Counted separately so the summary cannot be read as
# ten passing demonstrations.
cannot() {
  echo "  CANNOT  $1"
  CANNOT=$((CANNOT+1))
}

journey() { echo; echo "── §23.$1  $2"; }

# One patient throughout, because that is the brief's whole argument: one person, one record.
CPID="cpid-demo-1"
JOURNEY_ID="90000000-0000-4000-8000-000000000001"

problem() { # code display -> uuid
  uuid_of "$(q "INSERT INTO pct.pct_problems (problem_id, tenant_id, subject_cpid, code, code_system, display, clinical_status, category, recorded_by)
      VALUES (gen_random_uuid(),'$TENANT','$CPID','$1','ICD-10','$2','ACTIVE','DIAGNOSIS','clin-1') RETURNING problem_id;")"
}

enrol() { # programme problem_id -> uuid
  q "INSERT INTO pct.pct_programme_enrolments (enrolment_id, tenant_id, subject_cpid, programme, status, anchor_problem_id, enrolled_on, managing_facility_id, created_by)
     VALUES (gen_random_uuid(),'$TENANT','$CPID','$1','ON_TREATMENT','$2', now(), 'fac-1','clin-1') RETURNING enrolment_id;"
}

echo "=== Adult Medicine — the ten §23 demonstrations (record layer) ==="
mkdir -p "$EVIDENCE"

docker rm -f "$PG_NAME" >/dev/null 2>&1 || true
docker run -d --name "$PG_NAME" \
  -e POSTGRES_USER=impilo -e POSTGRES_PASSWORD=impilo -e POSTGRES_DB=pct \
  -p "$PG_PORT":5432 postgres:16-alpine >/dev/null

printf 'waiting for postgres'
for _ in $(seq 1 60); do
  docker exec "$PG_NAME" pg_isready -U impilo -d pct >/dev/null 2>&1 && break
  printf '.'; sleep 1
done
echo

q "CREATE SCHEMA IF NOT EXISTS pct; CREATE EXTENSION IF NOT EXISTS pgcrypto;" >/dev/null
q "SET search_path TO pct;" >/dev/null

echo "--- applying pct migrations in version order ---"
APPLIED=0
while IFS= read -r f; do
  out="$(docker exec -i "$PG_NAME" psql -U impilo -d pct -v ON_ERROR_STOP=1 -c "SET search_path TO pct,public;" -f - < "$f" 2>&1)"
  if echo "$out" | grep -qi "^ERROR"; then
    echo "MIGRATION FAILED: $(basename "$f")"; echo "$out" | head -5; FAIL=$((FAIL+1)); break
  fi
  APPLIED=$((APPLIED+1))
done < <(find "$MIG_DIR" -name 'V*.sql' | sort -t V -k2 -n)
echo "applied $APPLIED migration file(s) cleanly"

# ───────────────────────────────────────────────────────────────────────────────────────────────
journey 1 "Newly detected hypertension and diabetes into an integrated care plan"
HTN="$(problem 'I10' 'Essential hypertension')"
DM="$(problem 'E11' 'Type 2 diabetes mellitus')"
chk "both diagnoses live on ONE problem list" \
    "$(q "SELECT count(*) FROM pct.pct_problems WHERE subject_cpid='$CPID' AND code IN ('I10','E11');")" "2"
enrol 'HYPERTENSION' "$HTN" >/dev/null; enrol 'DIABETES' "$DM" >/dev/null
chk "each enters its own register, anchored to its own diagnosis" \
    "$(q "SELECT count(*) FROM pct.pct_programme_enrolments
           WHERE subject_cpid='$CPID' AND programme IN ('HYPERTENSION','DIABETES');")" "2"
EPISODE="$(uuid_of "$(q "INSERT INTO pct.pct_medical_episodes (episode_id, tenant_id, subject_cpid, episode_type, status, title, started_on, created_by)
   VALUES (gen_random_uuid(),'$TENANT','$CPID','MULTIMORBIDITY','ACTIVE','Consolidated plan: hypertension and diabetes', now(),'clin-1') RETURNING episode_id;")")"
chk "ONE consolidated plan spans both, rather than two parallel plans" \
    "$(q "INSERT INTO pct.pct_medical_episode_problems (episode_id, problem_id, role)
          VALUES ('$EPISODE','$HTN','PRIMARY'), ('$EPISODE','$DM','PRIMARY');
          SELECT count(*) FROM pct.pct_medical_episode_problems WHERE episode_id='$EPISODE';")" "2"

# ───────────────────────────────────────────────────────────────────────────────────────────────
journey 2 "HIV, TB and diabetes managed without three disconnected records"
HIV="$(problem 'B20' 'HIV disease')"
TB="$(problem 'A15' 'Respiratory tuberculosis')"
chk "all three conditions are on the SAME person's problem list" \
    "$(q "SELECT count(DISTINCT subject_cpid) FROM pct.pct_problems WHERE subject_cpid='$CPID';")" "1"
enrol 'HIV_CARE' "$HIV" >/dev/null; enrol 'TB_TREATMENT' "$TB" >/dev/null
chk "HIV and TB are programme VIEWS over that list, not separate records" \
    "$(q "SELECT count(*) FROM pct.pct_programme_enrolments
           WHERE subject_cpid='$CPID' AND programme IN ('HIV_CARE','TB_TREATMENT');")" "2"
chk "every enrolment resolves back to a diagnosis on the one list" \
    "$(q "SELECT count(*) FROM pct.pct_programme_enrolments e
           JOIN pct.pct_problems p ON p.problem_id = e.anchor_problem_id
          WHERE e.subject_cpid='$CPID' AND p.subject_cpid='$CPID';")" "4"
cannot "confidentiality is derived but NOT enforced — SPECIALLY_PROTECTED ships inert, so the HIV view carries a label that restricts nothing"

# ───────────────────────────────────────────────────────────────────────────────────────────────
journey 3 "Heart failure: Emergency to inpatient, titration, follow-up"
HF="$(problem 'I50' 'Congestive heart failure')"
chk "the medical episode can name the emergency episode it came from" \
    "$(q "SELECT count(*) FROM information_schema.columns
           WHERE table_schema='pct' AND table_name='pct_medical_episodes' AND column_name='emergency_episode_id';")" "1"
chk "the problem persists across settings rather than being re-entered" \
    "$(q "SELECT count(*) FROM pct.pct_problems WHERE problem_id='$HF';")" "1"
cannot "medicine TITRATION has no record — there is no dose-change history, so what the ward changed and why is not carried into the clinic"

# ───────────────────────────────────────────────────────────────────────────────────────────────
journey 4 "CKD into dialysis preparation and the Procedures Pipeline"
CKD="$(problem 'N18.4' 'Chronic kidney disease stage 4')"
enrol 'CHRONIC_KIDNEY_DISEASE' "$CKD" >/dev/null
chk "CKD enters its register anchored to the diagnosis" \
    "$(q "SELECT count(*) FROM pct.pct_programme_enrolments
           WHERE subject_cpid='$CPID' AND programme='CHRONIC_KIDNEY_DISEASE' AND anchor_problem_id='$CKD';")" "1"
chk "the register can say how the condition is running, and when that was judged" \
    "$(q "UPDATE pct.pct_programme_enrolments SET control_status='NOT_CONTROLLED', control_assessed_on=now()
           WHERE subject_cpid='$CPID' AND programme='CHRONIC_KIDNEY_DISEASE' RETURNING control_status;")" "NOT_CONTROLLED"
cannot "dialysis preparation, modality choice and vascular access have no record; the procedure itself executes in procedures-service, which this rig does not cover"

# ───────────────────────────────────────────────────────────────────────────────────────────────
journey 5 "Stroke: Emergency to medical admission, rehabilitation, secondary prevention"
STROKE="$(problem 'I63' 'Cerebral infarction')"
chk "the stroke is a problem with a resolvable anchor, not a note" \
    "$(q "SELECT clinical_status FROM pct.pct_problems WHERE problem_id='$STROKE';")" "ACTIVE"
chk "a structured neurological examination can be recorded against the journey" \
    "$(q "INSERT INTO pct.pct_examinations (examination_id, tenant_id, subject_cpid, journey_id, examined_at, examined_by)
          VALUES (gen_random_uuid(),'$TENANT','$CPID','$JOURNEY_ID', now(),'clin-1') RETURNING examination_id;" | grep -c '-')" "1"
cannot "rehabilitation goals and the secondary-prevention plan have no record — the commonest real failure in this pathway is a prevention plan never made or never followed up, and nothing here would show it"

# ───────────────────────────────────────────────────────────────────────────────────────────────
journey 6 "Decompensated liver disease undergoing paracentesis"
CIRR="$(problem 'K74' 'Cirrhosis of liver')"
chk "the liver disease is on the one problem list" \
    "$(q "SELECT display FROM pct.pct_problems WHERE problem_id='$CIRR';")" "Cirrhosis"
chk "the ascites finding can be recorded as an abdominal examination that MUST say what was found" \
    "$(q "INSERT INTO pct.pct_examination_findings (finding_id, tenant_id, examination_id, region, state, detail)
          SELECT gen_random_uuid(),'$TENANT', examination_id,'ABDOMEN','ABNORMAL','shifting dullness, tense ascites'
            FROM pct.pct_examinations WHERE subject_cpid='$CPID' LIMIT 1
          RETURNING state;")" "ABNORMAL"
cannot "the procedure and its RESULT RETURNING to the problem list is the untested half — §25's 'results are reviewed and actioned' has no record here"

# ───────────────────────────────────────────────────────────────────────────────────────────────
journey 7 "Suspected cancer through diagnosis, MDT, oncology and palliative care"
CA="$(uuid_of "$(q "INSERT INTO pct.pct_problems (problem_id, tenant_id, subject_cpid, code, code_system, display, clinical_status, category, diagnostic_certainty, recorded_by)
    VALUES (gen_random_uuid(),'$TENANT','$CPID','C34','ICD-10','Malignant neoplasm of bronchus and lung','ACTIVE','DIAGNOSIS','SUSPECTED','clin-1') RETURNING problem_id;")")"
chk "a suspicion is recordable AS a suspicion, not as a diagnosis" \
    "$(q "SELECT diagnostic_certainty FROM pct.pct_problems WHERE problem_id='$CA';")" "SUSPECTED"
chk "it can be promoted to CONFIRMED without losing that it began as a suspicion" \
    "$(q "UPDATE pct.pct_problems SET diagnostic_certainty='CONFIRMED' WHERE problem_id='$CA' RETURNING diagnostic_certainty;")" "CONFIRMED"
cannot "MDT has NO record at all (§14 is not built), so the decision that sets treatment intent has no author, no date and no attribution"
cannot "staging, systemic therapy, cycle planning, toxicity and response have no record"

# ───────────────────────────────────────────────────────────────────────────────────────────────
journey 8 "Older person: ICOPE assessment into a consolidated multimorbidity plan"
FRAIL="$(problem 'R54' 'Frailty')"
chk "frailty is a first-class problem, not a note" \
    "$(q "SELECT display FROM pct.pct_problems WHERE problem_id='$FRAIL';")" "Frailty"
chk "frailty, cognition and function are examinable regions in their own right" \
    "$(q "SELECT count(*) FROM (VALUES ('FRAILTY'),('COGNITION'),('FUNCTIONAL_STATUS')) v(r)
          WHERE pg_get_constraintdef((SELECT oid FROM pg_constraint WHERE conname='pct_examination_findings_region_check')) LIKE '%'||v.r||'%';")" "3"
chk "a MULTIMORBIDITY episode is the governed home for the consolidated plan" \
    "$(q "SELECT episode_type FROM pct.pct_medical_episodes WHERE episode_id='$EPISODE';")" "MULTIMORBIDITY"
cannot "the patient's own priorities have no record — §9 requires a person-centred prioritised plan, and it cannot be person-centred while nobody has asked"

# ───────────────────────────────────────────────────────────────────────────────────────────────
journey 9 "A pregnant patient whose medical treatment is coordinated with Maternity"
chk "an enrolment can point at an RMNP pregnancy episode (V111 soft link)" \
    "$(q "SELECT count(*) FROM information_schema.columns
           WHERE table_schema='pct' AND table_name='pct_programme_enrolments' AND column_name='pregnancy_episode_id';")" "1"
chk "and the link is a REAL foreign key, so it cannot dangle" \
    "$(q "SELECT convalidated FROM pg_constraint WHERE conname='pct_programme_enrolments_pregnancy_episode_fk';")" "t"
cannot "the link is one-directional and read-only by RMNP ruling: the medical view can see the pregnancy, and pregnancy-aware medicine review is not built, so an unsafe-in-pregnancy medicine would not be flagged from this side"

# ───────────────────────────────────────────────────────────────────────────────────────────────
journey 10 "A complex medical patient needing surgical consultation without loss of ownership"
chk "the medical episode stays open and keeps its own owner" \
    "$(q "SELECT status FROM pct.pct_medical_episodes WHERE episode_id='$EPISODE';")" "ACTIVE"
chk "the clerking already recorded is not re-entered — one problem list, read by both teams" \
    "$(q "SELECT count(DISTINCT subject_cpid) FROM pct.pct_problems WHERE subject_cpid='$CPID';")" "1"
cannot "consultation itself has NO record (§14) — there is no request, no response and no statement of who retains the patient, which is exactly the loss of ownership §23.10 asks us to demonstrate against"

# ───────────────────────────────────────────────────────────────────────────────────────────────
echo
q "DELETE FROM pct.pct_examination_findings WHERE tenant_id='$TENANT';
   DELETE FROM pct.pct_examinations WHERE subject_cpid='$CPID';
   DELETE FROM pct.pct_medical_episode_problems WHERE episode_id='$EPISODE';
   DELETE FROM pct.pct_medical_episodes WHERE subject_cpid='$CPID';
   DELETE FROM pct.pct_programme_enrolments WHERE subject_cpid='$CPID';
   DELETE FROM pct.pct_problems WHERE subject_cpid='$CPID';" >/dev/null
LEFT="$(q "SELECT count(*) FROM pct.pct_problems WHERE subject_cpid='$CPID';")"
echo "probe rows left: ${LEFT}"

echo
echo "=== record layer: PASS=$PASS FAIL=$FAIL ==="
echo "=== $CANNOT stated gaps — the record cannot yet carry these parts, and no service or UI work ==="
echo "=== changes that. This is NOT ten passing demonstrations and must not be reported as such. ==="
{
  echo "medicine §23 demonstrations — record layer only"
  echo "applied=$APPLIED PASS=$PASS FAIL=$FAIL cannot_yet=$CANNOT probe_rows_left=$LEFT"
  echo
  echo "Proves: the record can carry these journeys."
  echo "Does NOT prove: that the services execute them, or that a clinician can walk them in the product."
} > "$EVIDENCE/summary.txt"
[[ $FAIL -eq 0 ]] || exit 1
