replicaCount: 1

image:
  repository: ghcr.io/mohcc/impilo/vito
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 2Gi
