---
apiVersion: v1
kind: Namespace
metadata:
  name: impilo-trust
  labels:
    plane: trust
    part-of: impilo-vnext
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: impilo-registry
  labels:
    plane: registry
    part-of: impilo-vnext
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: impilo-clinical
  labels:
    plane: clinical
    part-of: impilo-vnext
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: impilo-finance
  labels:
    plane: enterprise
    part-of: impilo-vnext
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: impilo-ops
  labels:
    plane: integration
    part-of: impilo-vnext
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: impilo-ui
  labels:
    plane: experience
    part-of: impilo-vnext
---
apiVersion: v1
kind: Namespace
metadata:
  name: impilo-data
  labels:
    plane: data
    part-of: impilo-vnext
---
apiVersion: v1
kind: Namespace
metadata:
  name: impilo-monitoring
  labels:
    plane: integration
    part-of: impilo-vnext
