package zw.gov.mohcc.impilo.learning.core.ai;

import java.time.OffsetDateTime;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Component;

@Component
public class LearningAiStubProvider implements LearningAiProvider {

    @Override
    public String providerName() {
        return "STUB_SAFE_LOCAL";
    }

    @Override
    public Map<String, Object> generateCourseOutline(Map<String, Object> request) {
        String title = stringOr(request.get("title"), "AI Draft Course");
        return Map.of(
                "title", title,
                "durationHours", numberOr(request.get("durationHours"), 2),
                "modules", List.of(
                        Map.of("title", "Introduction", "outcomes", List.of("Understand context", "Set expectations")),
                        Map.of("title", "Core Practice", "outcomes", List.of("Apply workflow", "Avoid common errors")),
                        Map.of("title", "Quality and Safety", "outcomes", List.of("Use governance checks", "Escalate correctly"))),
                "generatedAt", OffsetDateTime.now().toString(),
                "draft", true);
    }

    @Override
    public Map<String, Object> generateLessonContent(Map<String, Object> request) {
        String topic = stringOr(request.get("topic"), "Lesson topic");
        return Map.of(
                "title", topic,
                "blocks", List.of(
                        Map.of("type", "heading", "text", topic),
                        Map.of("type", "text", "text", "Draft generated content. Human review required before publish."),
                        Map.of("type", "checklist", "items", List.of("Key step 1", "Key step 2", "Key step 3"))),
                "draft", true);
    }

    @Override
    public Map<String, Object> generateQuiz(Map<String, Object> request) {
        return Map.of(
                "assessmentType", "QUIZ",
                "questions", List.of(
                        Map.of(
                                "type", "MULTIPLE_CHOICE",
                                "prompt", "Which purpose-of-use is expected for routine clinical care?",
                                "choices", List.of("TREATMENT", "BILLING_ONLY", "MARKETING"),
                                "correct", "TREATMENT"),
                        Map.of(
                                "type", "TRUE_FALSE",
                                "prompt", "AI generated items must be reviewed before publishing.",
                                "correct", true)),
                "draft", true);
    }

    @Override
    public Map<String, Object> generateSummary(Map<String, Object> request) {
        return Map.of(
                "summary", "Draft summary generated by safe local provider. Review and edit before publishing.",
                "keyPoints", List.of("Point 1", "Point 2", "Point 3"),
                "draft", true);
    }

    @Override
    public Map<String, Object> generateSurvey(Map<String, Object> request) {
        return Map.of(
                "assessmentType", "SURVEY",
                "questions", List.of(
                        Map.of("type", "RATING", "prompt", "How relevant was this learning?", "scale", "1-5"),
                        Map.of("type", "TEXT", "prompt", "What should improve?")),
                "draft", true);
    }

    @Override
    public Map<String, Object> generateFacilitatorGuide(Map<String, Object> request) {
        Map<String, Object> guide = new LinkedHashMap<>();
        guide.put("openingScript", "Welcome learners and align objectives.");
        guide.put("discussionPrompts", List.of("What worked?", "What was difficult?", "How do we improve?"));
        guide.put("wrapUp", "Summarize takeaways and next actions.");
        guide.put("draft", true);
        return guide;
    }

    @Override
    public Map<String, Object> generateVoiceoverScript(Map<String, Object> request) {
        String topic = stringOr(request.get("topic"), "Learning segment");
        return Map.of(
                "title", topic + " voiceover",
                "script", "Draft narration for " + topic + ". Please validate terminology and policy alignment.",
                "estimatedSeconds", 90,
                "draft", true);
    }

    private static String stringOr(Object value, String fallback) {
        if (value == null) return fallback;
        String out = value.toString().trim();
        return out.isEmpty() ? fallback : out;
    }

    private static int numberOr(Object value, int fallback) {
        if (value instanceof Number n) return n.intValue();
        try {
            return value == null ? fallback : Integer.parseInt(value.toString());
        } catch (Exception ex) {
            return fallback;
        }
    }
}
