#!/usr/bin/env bash
# Phase 0 ext_authz cutover readiness (§22 Phase 0, §21.3).
#
# Enabling envoy.extAuthz renders a filter with failure_mode_allow: false in front of a
# single catch-all route. From that moment every request the PDP cannot resolve to an
# allowing rule becomes a 403 — there is no partial mode and no fail-open. This script
# measures whether that is survivable BEFORE the flag moves, because the estate gives no
# second chance to find out.
#
# It answers four questions, and refuses to certify readiness on any it could not measure:
#
#   C1  Does the rendered config delete any header it strips? (the §21.3 asymmetry)
#   C2  Do the nine operating-context headers survive? (the §21.3 strip-order trap)
#   C3  Does any real route hit NO_MATCHING_RULES — i.e. no candidate rule at all?
#   C4  Are the service-side ordering preconditions met?
#
# Checker discipline (§38C.4): every check declares its scope and FAILS if that scope came
# back empty. A check that scanned nothing must never report OK — that is the failure mode
# this whole gate exists to prevent, so it must not be the gate's own failure mode.

set -uo pipefail

NS="${IMPILO_NAMESPACE:-impilo-full-preview}"
CHART="${CHART_DIR:-deploy/helm/impilo-vnext}"
VALUES="${VALUES_FILE:-$CHART/values-full-preview.yaml}"
# Minimum share of routes that must resolve to an allowing rule before the flag may move.
# Not a tuning knob: below this, enabling ext_authz is an outage, not an enforcement change.
THRESHOLD="${COVERAGE_THRESHOLD:-95}"

WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
PASS=0; FAIL=0; UNKNOWN=0
declare -a RESULTS=()

record() { # record <state> <id> <message>
  case "$1" in
    PASS) PASS=$((PASS+1));;
    FAIL) FAIL=$((FAIL+1));;
    *)    UNKNOWN=$((UNKNOWN+1));;
  esac
  RESULTS+=("$1|$2|$3")
  printf '  [%-7s] %-4s %s\n' "$1" "$2" "$3"
}

echo "=== Phase 0 ext_authz cutover readiness — namespace ${NS}"
echo

# ── Render the config the flag would actually produce ────────────────────────────────
if ! command -v helm >/dev/null 2>&1; then
  record UNKNOWN C1 "helm absent — cannot render the config the flag would produce"
  record UNKNOWN C2 "helm absent — cannot inspect the strip list"
else
  if helm template impilo "$CHART" -f "$VALUES" --set envoy.extAuthz.enabled=true \
       --show-only templates/envoy.yaml >"$WORK/on.yaml" 2>"$WORK/render.err"; then
    python3 - "$WORK/on.yaml" >"$WORK/hdr.txt" 2>&1 <<'PY'
import sys, yaml
cfg=None
for d in yaml.safe_load_all(open(sys.argv[1])):
    if d and d.get("kind")=="ConfigMap" and "envoy.yaml" in d.get("data",{}):
        cfg=yaml.safe_load(d["data"]["envoy.yaml"])
if cfg is None: print("SCOPE_EMPTY"); sys.exit(0)
hcm=cfg["static_resources"]["listeners"][0]["filter_chains"][0]["filters"][0]["typed_config"]
routes=hcm["route_config"]["virtual_hosts"][0]["routes"]
catch=[r for r in routes if r["match"].get("prefix")=="/"]
ext=[f for f in hcm["http_filters"] if f["name"]=="envoy.filters.http.ext_authz"]
if not catch or not ext: print("SCOPE_EMPTY"); sys.exit(0)
strip=set(catch[0].get("request_headers_to_remove",[]))
# authorization_response is a field of HttpService, NOT of ExtAuthz. This script originally
# read it one level up — the same mistake the template made — so it happily validated an
# invalid config. Fail loudly if it is not where the proto says it lives.
tc=ext[0]["typed_config"]
if "authorization_response" in tc:
    print("SCOPE_EMPTY"); sys.exit(0)   # misplaced: Envoy would reject this outright
up={p["exact"] for p in tc["http_service"]["authorization_response"]["allowed_upstream_headers"]["patterns"]}
# :method and :path are regenerated by Envoy's own headers_to_add, so dropping the client
# copies is the control working, not a loss.
EXPECTED_DROPS={"x-original-method","x-original-path"}
print("STRIP_COUNT", len(strip))
print("ORPHANS", ",".join(sorted(strip-up-EXPECTED_DROPS)) or "-")
NINE=["x-facility-id","x-workspace-id","x-department-id","x-ward-id","x-programme-id",
      "x-shift-id","x-work-context-token","x-purpose-of-use","x-workflow-state"]
print("LOST_CONTEXT", ",".join(sorted(h for h in NINE if h in strip and h not in up)) or "-")
PY
    if grep -q SCOPE_EMPTY "$WORK/hdr.txt"; then
      record FAIL C1 "rendered config had no ext_authz filter or no catch-all route — nothing was inspected"
      record FAIL C2 "scope empty; the strip list could not be located"
    else
      strip_count=$(awk '/^STRIP_COUNT/{print $2}' "$WORK/hdr.txt")
      orphans=$(awk '/^ORPHANS/{print $2}' "$WORK/hdr.txt")
      lost=$(awk '/^LOST_CONTEXT/{print $2}' "$WORK/hdr.txt")
      # Scope non-emptiness: a strip list of zero would make C1 vacuously green.
      if [ "${strip_count:-0}" -lt 5 ]; then
        record FAIL C1 "strip list holds only ${strip_count:-0} headers — too few to be the real list; check the template"
      elif [ "$orphans" = "-" ]; then
        record PASS C1 "every stripped header is re-added by the PDP (${strip_count} stripped)"
      else
        record FAIL C1 "stripped but never re-added — DELETED on cutover: ${orphans}"
      fi
      if [ "$lost" = "-" ]; then
        record PASS C2 "the nine operating-context headers survive the cutover"
      else
        record FAIL C2 "strip-order trap ARMED — operating context would be deleted: ${lost}"
      fi
    fi
  else
    record UNKNOWN C1 "helm render failed: $(tail -1 "$WORK/render.err")"
    record UNKNOWN C2 "helm render failed"
  fi
fi

# ── C3: does any real route have NO candidate rule at all? ───────────────────────────
# This check used to compute a static set-difference between route-derived resource types
# and policy_rule.resource_type, and reported "16% coverage, 2385 routes would 403". That
# number was wrong three ways: 141 active rules carry resource_type IS NULL and are
# candidates for EVERY resource; PolicyCacheService also matches by prefix; and having a
# candidate rule is not the same as being allowed by one. Measured against the live PDP,
# NO_MATCHING_RULES never fires for the seeded tenant.
#
# So the question worth asking is the narrow one: is there any route for which the engine
# finds NO candidate rule? That is the only condition that means a rule is genuinely
# missing. NO_ALLOW_RULE is a policy decision — an actor without the required role SHOULD
# be denied — and counting it as a gap would be counting correct enforcement as a defect.
#
# THE TENANT MUST COME FROM REAL TRAFFIC, NEVER A DEFAULT.
# This check previously swept a hardcoded 00000000-0000-0000-0000-000000000001 — the tenant
# the migrations seed — and passed. Real signed-in requests carry
# 00000000-0000-4000-8000-000000000001, which has ZERO rules, so every authenticated call
# answered NO_MATCHING_RULES. The gate read 6/6, the cutover proceeded, and every shell
# endpoint 403'd. A green check against a tenant no request uses is worse than no check.
#
# The runtime tenant is read from policy_decision_log — what real requests were evaluated
# under — EXCLUDING this script's own probe actor. Without that exclusion the sweep's own
# rows dominate the table and the check reads back the tenant it just used: a tautology,
# not a measurement.
PROBE_ACTOR="c0000000-0000-4000-8000-000000000001"
AUTHZ=$(kubectl get pods -n "$NS" -l app=tshepo-authz-service --no-headers 2>/dev/null \
        | awk '$3=="Running"{print $1;exit}')
PGPOD=$(kubectl get pods -n "$NS" --no-headers 2>/dev/null | awk '/postgres/ && $3=="Running"{print $1;exit}')
RUNTIME_TENANT=""
if [ -n "${PGPOD:-}" ]; then
  # Order by RECENCY, not frequency. Frequency picks whichever tenant has the most history,
  # and history is exactly what changed: the seeded tenant holds 77 decisions but none since
  # 2026-08-02, while the tenant real sessions actually carry holds 7, all from today.
  # Ranking by count returned the stale one and produced a second false PASS.
  RUNTIME_TENANT=$(kubectl exec -n "$NS" "$PGPOD" -- psql -U impilo -d tshepo_authz -qtAc \
    "select tenant_id from tshepo_authz.policy_decision_log
      where actor_id is distinct from '${PROBE_ACTOR}'
      group by tenant_id order by max(evaluated_at) desc limit 1;" 2>/dev/null | tr -d '\r ')
  # A tenant learned from week-old traffic is a guess about what the runtime does now.
  # Report the age so a stale reading cannot pass as a current measurement.
  TENANT_AGE_H=$(kubectl exec -n "$NS" "$PGPOD" -- psql -U impilo -d tshepo_authz -qtAc \
    "select floor(extract(epoch from (now() - max(evaluated_at)))/3600)::int
       from tshepo_authz.policy_decision_log
      where actor_id is distinct from '${PROBE_ACTOR}';" 2>/dev/null | tr -d '\r ')
fi
# The override exists only so this check can be red-proved against a rule-less tenant.
# It must never be the silent default.
TENANT="${POLICY_TENANT:-$RUNTIME_TENANT}"
# The PDP merges the governance tenant's rules into every tenant (tshepo.authz.
# governance-tenant-id), because rules live on the registry plane while requests present the
# care plane. So "the runtime tenant owns no rows" stopped being evidence of anything — it is
# the normal, correct state. Counting rows on the runtime tenant alone would fail a healthy
# estate; the sweep below remains the authority, and this only fails when NEITHER side can
# supply a rule.
GOVERNANCE_TENANT=$(kubectl get deploy tshepo-authz-service -n "$NS" \
  -o jsonpath='{.spec.template.spec.containers[0].env[?(@.name=="TSHEPO_AUTHZ_GOVERNANCE_TENANT_ID")].value}' 2>/dev/null)
GOVERNANCE_TENANT="${GOVERNANCE_TENANT:-00000000-0000-0000-0000-000000000001}"
GOVERNANCE_RULE_COUNT=0
if [ -n "${PGPOD:-}" ] && [ -n "$GOVERNANCE_TENANT" ]; then
  GOVERNANCE_RULE_COUNT=$(kubectl exec -n "$NS" "$PGPOD" -- psql -U impilo -d tshepo_authz -qtAc \
    "select count(*) from tshepo_authz.policy_rule where active and tenant_id='${GOVERNANCE_TENANT}';" \
    2>/dev/null | tr -d '\r ')
fi
RULE_COUNT=0
if [ -n "${PGPOD:-}" ] && [ -n "$TENANT" ]; then
  RULE_COUNT=$(kubectl exec -n "$NS" "$PGPOD" -- psql -U impilo -d tshepo_authz -qtAc \
    "select count(*) from tshepo_authz.policy_rule where active and tenant_id='${TENANT}';" \
    2>/dev/null | tr -d '\r ')
fi

if [ -z "${AUTHZ:-}" ]; then
  record UNKNOWN C3 "tshepo-authz-service not running in ${NS} — rule coverage unmeasured"
elif [ -z "$TENANT" ]; then
  record UNKNOWN C3 "no non-probe decision in policy_decision_log — the runtime tenant is unknown and this cannot be measured; drive one real signed-in request first"
elif [ -z "${POLICY_TENANT:-}" ] && [ "${TENANT_AGE_H:-9999}" -gt 24 ]; then
  record UNKNOWN C3 "newest non-probe decision is ${TENANT_AGE_H}h old — tenant ${TENANT} is inferred from stale traffic, not current behaviour; drive a real signed-in request and re-run"
elif [ "${RULE_COUNT:-0}" -eq 0 ] && [ "${GOVERNANCE_RULE_COUNT:-0}" -eq 0 ]; then
  seeded=$(kubectl exec -n "$NS" "$PGPOD" -- psql -U impilo -d tshepo_authz -qtAc \
    "select string_agg(distinct tenant_id::text, ', ') from tshepo_authz.policy_rule where active;" \
    2>/dev/null | tr -d '\r')
  record FAIL C3 "runtime tenant ${TENANT} has ZERO active rules and the governance tenant supplies none — every authenticated request denies NO_MATCHING_RULES. Rules are seeded under: ${seeded:-<none>}"
else
  python3 - >"$WORK/paths.txt" <<'PYEOF'
import re, glob, random
out=set()
for f in glob.glob("services/experience-bff/**/*.java", recursive=True):
    src=open(f, encoding="utf-8", errors="ignore").read()
    if "@RestController" not in src and "@Controller" not in src: continue
    m=re.search(r'@RequestMapping\(\s*(?:value\s*=\s*)?\{?\s*"([^"]+)"', src)
    cls=m.group(1) if m else ""
    for mm in re.finditer(r'@(?:Get|Post|Put|Patch|Delete)Mapping'
                          r'(?:\(\s*(?:value\s*=\s*)?(?:\{\s*)?"([^"]*)"|\(\s*\)|\s*\n)', src):
        p=(cls+"/"+(mm.group(1) or "")).replace("//","/").rstrip("/") or cls
        if p.startswith("/"):
            out.add(re.sub(r"\{[^}]+\}", "11111111-1111-4111-8111-111111111111", p))
random.seed(11)
s=sorted(out)
print("\n".join(random.sample(s, min(60, len(s)))))
PYEOF
  n_paths=$(grep -cv '^$' "$WORK/paths.txt" || echo 0)
  if [ "$n_paths" -lt 30 ]; then
    record FAIL C3 "route scan produced only ${n_paths} paths — the scanner is broken, not the estate clean"
  else
    # Stay under the PDP's request ceiling: a 429 is not a verdict, and a sweep that
    # silently collects them reports a policy result that was never evaluated.
    #
    # The verdict REASON cannot be read from the response body here: busybox wget writes
    # nothing to stdout for a 403, and NO_MATCHING_RULES and NO_ALLOW_RULE are both 403.
    # The PDP's own log is the authoritative source for which of the two fired, so the
    # sweep drives the requests and the log supplies the reasons.
    sweep_start=$(date -u +%s)
    kubectl exec -i -n "$NS" "$AUTHZ" -- sh -c '
      while read p; do
        [ -z "$p" ] && continue
        wget -S -O /dev/null -T 5 \
          --header="x-tenant-id: '"${TENANT}"'" \
          --header="x-actor-id: c0000000-0000-4000-8000-000000000001" \
          --header="x-actor-type: PROVIDER" \
          --header="x-purpose-of-use: TREATMENT" \
          "http://localhost:8081/v1/authorize$p" 2>&1 \
          | grep -oE "HTTP/1\.[01] [0-9]{3}" | tail -1 | cut -d" " -f2
      done' <"$WORK/paths.txt" >"$WORK/codes.txt" 2>/dev/null
    swept=$(grep -cE '^[0-9]{3}$' "$WORK/codes.txt" || echo 0)
    throttled=$(grep -c '^429$' "$WORK/codes.txt" || echo 0)
    permitted=$(grep -c '^200$' "$WORK/codes.txt" || echo 0)
    elapsed=$(( $(date -u +%s) - sweep_start + 15 ))
    kubectl logs -n "$NS" "$AUTHZ" --since="${elapsed}s" 2>/dev/null \
      | grep -oE 'reason=[A-Z_]+' | sort | uniq -c >"$WORK/reasons.txt"
    missing=$(awk '/NO_MATCHING_RULES/{print $1}' "$WORK/reasons.txt"); missing=${missing:-0}
    if [ "$swept" -lt 30 ]; then
      record FAIL C3 "sweep returned only ${swept} status codes for ${n_paths} paths — the probe, not the estate"
    elif [ "$throttled" -gt 0 ]; then
      record FAIL C3 "${throttled}/${swept} responses were rate-limited — a 429 is not a verdict; re-run slower"
    elif [ ! -s "$WORK/reasons.txt" ] && [ "$permitted" -lt "$swept" ]; then
      record FAIL C3 "denials occurred but the PDP log yielded no reason= lines — reasons unmeasured, not absent"
    elif [ "$missing" -gt 0 ]; then
      record FAIL C3 "${missing} decisions hit NO_MATCHING_RULES across ${swept} sampled routes — those have no candidate rule at all"
    else
      record PASS C3 "no route hit NO_MATCHING_RULES across ${swept} routes on the RUNTIME tenant ${TENANT} (${RULE_COUNT} own + ${GOVERNANCE_RULE_COUNT} governance rules; ${permitted} permitted for this unauthenticated probe actor — the rest are NO_ALLOW_RULE, a policy decision not a gap)"
    fi
  fi
fi

# ── C4: service-side ordering preconditions ──────────────────────────────────────────
AUTHZ=$(kubectl get pods -n "$NS" -l app=tshepo-authz-service --no-headers 2>/dev/null \
        | awk '$3=="Running"{print $1;exit}')
if [ -z "${AUTHZ:-}" ]; then
  record UNKNOWN C4 "tshepo-authz-service not running in ${NS} — modes unmeasured"
else
  env_out=$(kubectl exec -n "$NS" "$AUTHZ" -- env 2>/dev/null | grep -E 'CONTEXT_HEADER_MODE|WORK_CONTEXT_MODE')
  chm=$(sed -n 's/^TSHEPO_AUTHZ_CONTEXT_HEADER_MODE=//p' <<<"$env_out"); chm=${chm:-PASSTHROUGH}
  wcm=$(sed -n 's/^TSHEPO_WORK_CONTEXT_MODE=//p' <<<"$env_out"); wcm=${wcm:-SHADOW}
  if [ "$chm" = "AUTHORITATIVE" ] && [ "$wcm" = "ENFORCE" ]; then
    record PASS C4 "context-header-mode=${chm}, work-context-mode=${wcm} — ordering satisfied"
  else
    unmet=""
    [ "$chm" = "AUTHORITATIVE" ] || unmet="context-header-mode=${chm} (need AUTHORITATIVE)"
    if [ "$wcm" != "ENFORCE" ]; then
      [ -n "$unmet" ] && unmet="${unmet}; "
      unmet="${unmet}work-context-mode=${wcm} (need ENFORCE)"
    fi
    # Name only what is actually unmet — listing a satisfied condition as a failure reason
    # trains the reader to skim the check instead of acting on it.
    record FAIL C4 "ordering unmet: ${unmet}"
  fi
fi

# ── C5: Envoy must accept the config, and the PDP must answer where Envoy will call ──
# Both of these were learned the hard way: the rendered config was invalid in three places
# and nothing parsed it, because a template branch that is never rendered is never checked.
# Reading YAML is not validation — only Envoy can say whether Envoy will start.
if [ ! -s "$WORK/on.yaml" ]; then
  record UNKNOWN C5 "no rendered config — Envoy validation not attempted"
  record UNKNOWN C6 "no rendered config — PDP reachability not attempted"
else
  python3 - "$WORK/on.yaml" "$WORK/cm.yaml" <<'PY'
import sys, yaml
for d in yaml.safe_load_all(open(sys.argv[1])):
    if d and d.get("kind")=="ConfigMap" and "envoy.yaml" in d.get("data",{}):
        yaml.safe_dump({"apiVersion":"v1","kind":"ConfigMap",
                        "metadata":{"name":"envoy-config-validate"},
                        "data":{"envoy.yaml":d["data"]["envoy.yaml"]}},
                       open(sys.argv[2],"w"), default_flow_style=False, width=100000)
        break
PY
  IMG=$(kubectl get deploy envoy -n "$NS" -o jsonpath='{.spec.template.spec.containers[0].image}' 2>/dev/null)
  if [ -z "${IMG:-}" ]; then
    record UNKNOWN C5 "envoy deployment not found in ${NS} — cannot validate with the real binary"
  else
    kubectl delete pod envoy-validate -n "$NS" --ignore-not-found >/dev/null 2>&1
    kubectl apply -n "$NS" -f "$WORK/cm.yaml" >/dev/null 2>&1
    cat >"$WORK/vp.yaml" <<EOF
apiVersion: v1
kind: Pod
metadata: { name: envoy-validate, namespace: ${NS} }
spec:
  restartPolicy: Never
  containers:
    - name: envoy
      image: ${IMG}
      command: ["envoy","--mode","validate","-c","/etc/envoy/envoy.yaml"]
      volumeMounts: [{ name: cfg, mountPath: /etc/envoy }]
  volumes:
    - name: cfg
      configMap: { name: envoy-config-validate }
EOF
    kubectl apply -f "$WORK/vp.yaml" >/dev/null 2>&1
    phase=""
    for _ in $(seq 1 30); do
      phase=$(kubectl get pod envoy-validate -n "$NS" -o jsonpath='{.status.phase}' 2>/dev/null)
      [ "$phase" = "Succeeded" ] || [ "$phase" = "Failed" ] && break
      sleep 2
    done
    vlog=$(kubectl logs envoy-validate -n "$NS" 2>/dev/null | grep -iE "critical|configuration .* OK" | tail -1)
    if [ "$phase" = "Succeeded" ]; then
      record PASS C5 "Envoy's own validator accepts the rendered config"
    else
      record FAIL C5 "Envoy REJECTS the rendered config: ${vlog:-no log captured}"
    fi
    kubectl delete pod envoy-validate -n "$NS" --ignore-not-found >/dev/null 2>&1
    kubectl delete cm envoy-config-validate -n "$NS" --ignore-not-found >/dev/null 2>&1
  fi

  # C6: Envoy calls the PDP at path_prefix + the ORIGINAL path. If the PDP answers 401/404
  # there, failure_mode_allow:false turns every single request into a denial — a total
  # outage, not a coverage gap. A bare-endpoint probe would pass and prove nothing.
  PREFIX=$(python3 - "$WORK/on.yaml" <<'PY'
import sys, yaml
for d in yaml.safe_load_all(open(sys.argv[1])):
    if d and d.get("kind")=="ConfigMap" and "envoy.yaml" in d.get("data",{}):
        c=yaml.safe_load(d["data"]["envoy.yaml"])
        hcm=c["static_resources"]["listeners"][0]["filter_chains"][0]["filters"][0]["typed_config"]
        for f in hcm["http_filters"]:
            if f["name"]=="envoy.filters.http.ext_authz":
                print(f["typed_config"]["http_service"].get("path_prefix",""))
PY
)
  if [ -z "${AUTHZ:-}" ]; then
    record UNKNOWN C6 "tshepo-authz-service not running — PDP reachability unmeasured"
  else
    # Do not assume a service image ships any particular HTTP client. It shipped curl until a
    # rebuild dropped it, and the missing binary silently read as "no answer" — a broken
    # instrument reporting as a broken estate, which is the exact confusion this gate exists
    # to remove. Detect what is there; if nothing is, say so rather than inventing a verdict.
    URL="http://localhost:8081${PREFIX}/api/v1/patients/search"
    HDRS='-H "x-tenant-id: 00000000-0000-4000-8000-000000000001" -H "x-actor-id: c0000000-0000-4000-8000-000000000001" -H "x-actor-type: PROVIDER" -H "x-purpose-of-use: TREATMENT"'
    client=$(kubectl exec -n "$NS" "$AUTHZ" -- sh -c \
      'command -v curl >/dev/null && echo curl || { command -v wget >/dev/null && echo wget || echo none; }' 2>/dev/null)
    case "$client" in
      curl) code=$(kubectl exec -n "$NS" "$AUTHZ" -- sh -c \
              "curl -s -o /dev/null -w '%{http_code}' -m 6 $HDRS '$URL'" 2>/dev/null);;
      wget) code=$(kubectl exec -n "$NS" "$AUTHZ" -- sh -c \
              "wget -S -O /dev/null -T 6 \
                 --header='x-tenant-id: 00000000-0000-4000-8000-000000000001' \
                 --header='x-actor-id: c0000000-0000-4000-8000-000000000001' \
                 --header='x-actor-type: PROVIDER' \
                 --header='x-purpose-of-use: TREATMENT' '$URL' 2>&1 \
               | grep -oE 'HTTP/1\.[01] [0-9]{3}' | tail -1 | cut -d' ' -f2" 2>/dev/null);;
      *)    code="";;
    esac
    if [ -z "$code" ]; then
      record UNKNOWN C6 "no usable HTTP client in the tshepo-authz image (found: ${client:-none}) — reachability NOT measured"
      code="__skip__"
    fi
    case "$code" in
      __skip__) ;;
      401|404)
        record FAIL C6 "PDP answers ${code} at ${PREFIX}/<original path> — EVERY request would be denied, not just uncovered ones";;
      200|403)
        record PASS C6 "PDP reaches its decision logic at ${PREFIX}/<original path> (HTTP ${code})";;
      *)
        record FAIL C6 "PDP answered unexpected ${code:-<none>} at ${PREFIX}/<original path>";;
    esac
  fi
fi

echo
echo "=== ${PASS} passed, ${FAIL} failed, ${UNKNOWN} unmeasured"
if [ "$FAIL" -eq 0 ] && [ "$UNKNOWN" -eq 0 ]; then
  echo "=== READY: envoy.extAuthz.enabled may be set to true"
  exit 0
fi
echo "=== NOT READY — do not set envoy.extAuthz.enabled=true"
[ "$UNKNOWN" -gt 0 ] && echo "    (${UNKNOWN} check(s) could not be measured; unmeasured is not a pass)"
exit 1
