#!/usr/bin/env bash
# Phase 0 ext_authz cutover readiness (§22 Phase 0, §21.3).
#
# Enabling envoy.extAuthz renders a filter with failure_mode_allow: false in front of a
# single catch-all route. From that moment every request the PDP cannot resolve to an
# allowing rule becomes a 403 — there is no partial mode and no fail-open. This script
# measures whether that is survivable BEFORE the flag moves, because the estate gives no
# second chance to find out.
#
# It answers four questions, and refuses to certify readiness on any it could not measure:
#
#   C1  Does the rendered config delete any header it strips? (the §21.3 asymmetry)
#   C2  Do the nine operating-context headers survive? (the §21.3 strip-order trap)
#   C3  What share of the real route surface has an allowing policy rule?
#   C4  Are the service-side ordering preconditions met?
#
# Checker discipline (§38C.4): every check declares its scope and FAILS if that scope came
# back empty. A check that scanned nothing must never report OK — that is the failure mode
# this whole gate exists to prevent, so it must not be the gate's own failure mode.

set -uo pipefail

NS="${IMPILO_NAMESPACE:-impilo-full-preview}"
CHART="${CHART_DIR:-deploy/helm/impilo-vnext}"
VALUES="${VALUES_FILE:-$CHART/values-full-preview.yaml}"
# Minimum share of routes that must resolve to an allowing rule before the flag may move.
# Not a tuning knob: below this, enabling ext_authz is an outage, not an enforcement change.
THRESHOLD="${COVERAGE_THRESHOLD:-95}"

WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
PASS=0; FAIL=0; UNKNOWN=0
declare -a RESULTS=()

record() { # record <state> <id> <message>
  case "$1" in
    PASS) PASS=$((PASS+1));;
    FAIL) FAIL=$((FAIL+1));;
    *)    UNKNOWN=$((UNKNOWN+1));;
  esac
  RESULTS+=("$1|$2|$3")
  printf '  [%-7s] %-4s %s\n' "$1" "$2" "$3"
}

echo "=== Phase 0 ext_authz cutover readiness — namespace ${NS}"
echo

# ── Render the config the flag would actually produce ────────────────────────────────
if ! command -v helm >/dev/null 2>&1; then
  record UNKNOWN C1 "helm absent — cannot render the config the flag would produce"
  record UNKNOWN C2 "helm absent — cannot inspect the strip list"
else
  if helm template impilo "$CHART" -f "$VALUES" --set envoy.extAuthz.enabled=true \
       --show-only templates/envoy.yaml >"$WORK/on.yaml" 2>"$WORK/render.err"; then
    python3 - "$WORK/on.yaml" >"$WORK/hdr.txt" 2>&1 <<'PY'
import sys, yaml
cfg=None
for d in yaml.safe_load_all(open(sys.argv[1])):
    if d and d.get("kind")=="ConfigMap" and "envoy.yaml" in d.get("data",{}):
        cfg=yaml.safe_load(d["data"]["envoy.yaml"])
if cfg is None: print("SCOPE_EMPTY"); sys.exit(0)
hcm=cfg["static_resources"]["listeners"][0]["filter_chains"][0]["filters"][0]["typed_config"]
routes=hcm["route_config"]["virtual_hosts"][0]["routes"]
catch=[r for r in routes if r["match"].get("prefix")=="/"]
ext=[f for f in hcm["http_filters"] if f["name"]=="envoy.filters.http.ext_authz"]
if not catch or not ext: print("SCOPE_EMPTY"); sys.exit(0)
strip=set(catch[0].get("request_headers_to_remove",[]))
up={p["exact"] for p in ext[0]["typed_config"]["authorization_response"]["allowed_upstream_headers"]["patterns"]}
# :method and :path are regenerated by Envoy's own headers_to_add, so dropping the client
# copies is the control working, not a loss.
EXPECTED_DROPS={"x-original-method","x-original-path"}
print("STRIP_COUNT", len(strip))
print("ORPHANS", ",".join(sorted(strip-up-EXPECTED_DROPS)) or "-")
NINE=["x-facility-id","x-workspace-id","x-department-id","x-ward-id","x-programme-id",
      "x-shift-id","x-work-context-token","x-purpose-of-use","x-workflow-state"]
print("LOST_CONTEXT", ",".join(sorted(h for h in NINE if h in strip and h not in up)) or "-")
PY
    if grep -q SCOPE_EMPTY "$WORK/hdr.txt"; then
      record FAIL C1 "rendered config had no ext_authz filter or no catch-all route — nothing was inspected"
      record FAIL C2 "scope empty; the strip list could not be located"
    else
      strip_count=$(awk '/^STRIP_COUNT/{print $2}' "$WORK/hdr.txt")
      orphans=$(awk '/^ORPHANS/{print $2}' "$WORK/hdr.txt")
      lost=$(awk '/^LOST_CONTEXT/{print $2}' "$WORK/hdr.txt")
      # Scope non-emptiness: a strip list of zero would make C1 vacuously green.
      if [ "${strip_count:-0}" -lt 5 ]; then
        record FAIL C1 "strip list holds only ${strip_count:-0} headers — too few to be the real list; check the template"
      elif [ "$orphans" = "-" ]; then
        record PASS C1 "every stripped header is re-added by the PDP (${strip_count} stripped)"
      else
        record FAIL C1 "stripped but never re-added — DELETED on cutover: ${orphans}"
      fi
      if [ "$lost" = "-" ]; then
        record PASS C2 "the nine operating-context headers survive the cutover"
      else
        record FAIL C2 "strip-order trap ARMED — operating context would be deleted: ${lost}"
      fi
    fi
  else
    record UNKNOWN C1 "helm render failed: $(tail -1 "$WORK/render.err")"
    record UNKNOWN C2 "helm render failed"
  fi
fi

# ── C3: policy coverage over the real route surface ──────────────────────────────────
PG=$(kubectl get pods -n "$NS" --no-headers 2>/dev/null | awk '/postgres/ && $3=="Running"{print $1;exit}')
if [ -z "${PG:-}" ]; then
  record UNKNOWN C3 "no running postgres in ${NS} — policy coverage unmeasured"
else
  kubectl exec -n "$NS" "$PG" -- psql -U impilo -d tshepo_authz -qtAc \
    "select distinct resource_type from tshepo_authz.policy_rule where active;" 2>/dev/null \
    | tr -d '\r' | grep -v '^$' >"$WORK/covered.txt"
  python3 - >"$WORK/routes.txt" <<'PY'
import re, glob
out=set()
for f in glob.glob("services/experience-bff/**/*.java", recursive=True):
    src=open(f, encoding="utf-8", errors="ignore").read()
    if "@RestController" not in src and "@Controller" not in src: continue
    m=re.search(r'@RequestMapping\(\s*(?:value\s*=\s*)?\{?\s*"([^"]+)"', src)
    cls=m.group(1) if m else ""
    for mm in re.finditer(r'@(?:Get|Post|Put|Patch|Delete)Mapping'
                          r'(?:\(\s*(?:value\s*=\s*)?(?:\{\s*)?"([^"]*)"|\(\s*\)|\s*\n)', src):
        p=(cls+"/"+(mm.group(1) or "")).replace("//","/").rstrip("/") or cls
        if p: out.add(p)
print("\n".join(sorted(out)))
PY
  n_routes=$(grep -cv '^$' "$WORK/routes.txt" || echo 0)
  n_cov=$(grep -cv '^$' "$WORK/covered.txt" || echo 0)
  # Both scopes must be non-empty or the percentage is meaningless in the safe direction.
  if [ "$n_routes" -lt 100 ]; then
    record FAIL C3 "route scan found only ${n_routes} routes — the scanner is broken, not the estate clean"
  elif [ "$n_cov" -eq 0 ]; then
    record FAIL C3 "policy_rule returned zero active resource types — query or schema wrong"
  else
    pct=$(python3 - "$WORK/routes.txt" "$WORK/covered.txt" <<'PY'
import re, sys
covered={l.strip() for l in open(sys.argv[2]) if l.strip()}
def derive(path):                      # port of AuthzInternalRequest.deriveResourceType
    if not path or len(path)<2: return "UNKNOWN"
    for seg in reversed(path.split("/")):
        if not seg.strip(): continue
        if re.fullmatch(r"[0-9a-fA-F-]{36}", seg): continue
        if seg in ("v1","api"): continue
        return seg
    return "UNKNOWN"
rs=[l.strip() for l in open(sys.argv[1]) if l.strip()]
# Optimistic: assume every path variable is a UUID and is skipped. Real non-UUID ids
# (codes, keys, slugs) derive to their own literal value and cover even less.
hit=sum(1 for p in rs if derive(re.sub(r"\{[^}]+\}","0"*8+"-0000-4000-8000-"+"0"*12,p)) in covered)
print(f"{hit*100//len(rs)} {hit} {len(rs)}")
PY
)
    read -r pc hit tot <<<"$pct"
    if [ "$pc" -ge "$THRESHOLD" ]; then
      record PASS C3 "policy covers ${pc}% of routes (${hit}/${tot}, ${n_cov} resource types)"
    else
      record FAIL C3 "policy covers only ${pc}% of routes (${hit}/${tot}) — $((tot-hit)) would 403 on cutover; need ≥${THRESHOLD}%"
    fi
  fi
fi

# ── C4: service-side ordering preconditions ──────────────────────────────────────────
AUTHZ=$(kubectl get pods -n "$NS" -l app=tshepo-authz-service --no-headers 2>/dev/null \
        | awk '$3=="Running"{print $1;exit}')
if [ -z "${AUTHZ:-}" ]; then
  record UNKNOWN C4 "tshepo-authz-service not running in ${NS} — modes unmeasured"
else
  env_out=$(kubectl exec -n "$NS" "$AUTHZ" -- env 2>/dev/null | grep -E 'CONTEXT_HEADER_MODE|WORK_CONTEXT_MODE')
  chm=$(sed -n 's/^TSHEPO_AUTHZ_CONTEXT_HEADER_MODE=//p' <<<"$env_out"); chm=${chm:-PASSTHROUGH}
  wcm=$(sed -n 's/^TSHEPO_WORK_CONTEXT_MODE=//p' <<<"$env_out"); wcm=${wcm:-SHADOW}
  if [ "$chm" = "AUTHORITATIVE" ] && [ "$wcm" = "ENFORCE" ]; then
    record PASS C4 "context-header-mode=${chm}, work-context-mode=${wcm} — ordering satisfied"
  else
    record FAIL C4 "ordering unmet: context-header-mode=${chm} (need AUTHORITATIVE), work-context-mode=${wcm} (need ENFORCE)"
  fi
fi

echo
echo "=== ${PASS} passed, ${FAIL} failed, ${UNKNOWN} unmeasured"
if [ "$FAIL" -eq 0 ] && [ "$UNKNOWN" -eq 0 ]; then
  echo "=== READY: envoy.extAuthz.enabled may be set to true"
  exit 0
fi
echo "=== NOT READY — do not set envoy.extAuthz.enabled=true"
[ "$UNKNOWN" -gt 0 ] && echo "    (${UNKNOWN} check(s) could not be measured; unmeasured is not a pass)"
exit 1
