import type { CanonicalServiceSlug, MobileSovereignService, MobileSurface } from "./types";

/** Canonical sovereign services aligned with One UI shell serviceBranding.ts */
export const MOBILE_SOVEREIGN_SERVICES: Record<CanonicalServiceSlug, MobileSovereignService> = {
  vito: {
    slug: "vito",
    name: "Vito",
    domain: "Registry",
    description: "Client Registry / Health ID",
    icon: "people-outline",
    logoPath: "/brand/services/vito-logo.png",
    aliases: ["health-id", "client-registry", "mpi"],
    surfaces: ["citizen", "admin"],
    mobileStatus: "native",
    requiredAuthContext: ["client"],
  },
  varapi: {
    slug: "varapi",
    name: "Varapi",
    domain: "Registry",
    description: "Provider Registry / Provider ID",
    icon: "medkit-outline",
    logoPath: "/brand/services/varapi-logo.png",
    aliases: ["provider-registry", "provider-id"],
    surfaces: ["provider", "admin"],
    mobileStatus: "native",
    requiredAuthContext: ["provider"],
  },
  tuso: {
    slug: "tuso",
    name: "Tuso",
    domain: "Registry",
    description: "Facility Registry",
    icon: "business-outline",
    logoPath: "/brand/services/tuso-logo.png",
    aliases: ["facility-registry", "facilities"],
    surfaces: ["provider", "facility", "citizen"],
    mobileStatus: "native",
    requiredAuthContext: ["provider", "facility"],
  },
  tshepo: {
    slug: "tshepo",
    name: "Tshepo",
    domain: "Trust",
    description: "Trust / Authorization / Policy / Context",
    icon: "shield-checkmark-outline",
    logoPath: "/brand/services/tshepo-logo.png",
    aliases: ["trust", "authz", "policy"],
    surfaces: ["citizen", "provider", "admin"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  butano: {
    slug: "butano",
    name: "Butano",
    domain: "Clinical",
    description: "Shared Health Record / FHIR",
    icon: "document-text-outline",
    logoPath: "/brand/services/butano-logo.png",
    aliases: ["shr", "fhir", "shared-health-record"],
    surfaces: ["citizen", "provider"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  ubomi: {
    slug: "ubomi",
    name: "Ubomi",
    domain: "Registry",
    description: "CRVS / Births / Deaths / Vital Events",
    icon: "heart-circle-outline",
    logoPath: "/brand/services/ubomi-logo.png",
    aliases: ["crvs", "vital-events"],
    surfaces: ["citizen"],
    mobileStatus: "native",
    requiredAuthContext: ["client"],
  },
  zibo: {
    slug: "zibo",
    name: "Zibo",
    domain: "Registry",
    description: "Terminology Service",
    icon: "book-outline",
    logoPath: "/brand/services/zibo-logo.png",
    aliases: ["terminology", "code-systems"],
    surfaces: ["provider", "admin"],
    mobileStatus: "native",
    requiredAuthContext: ["provider", "admin"],
  },
  msika: {
    slug: "msika",
    name: "Msika",
    domain: "Enterprise & Commerce",
    description: "Products / Services / Marketplace",
    icon: "storefront-outline",
    logoPath: "/brand/services/msika-logo.png",
    aliases: ["marketplace", "commerce"],
    surfaces: ["citizen", "provider", "enterprise"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  indawo: {
    slug: "indawo",
    name: "Indawo",
    domain: "Public Health",
    description: "Public Health Sites / Places",
    icon: "location-outline",
    logoPath: "/brand/services/indawo-logo.png",
    aliases: ["site-registry", "public-health-sites"],
    surfaces: ["citizen", "provider", "publicHealth"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider", "publicHealth"],
  },
  pct: {
    slug: "pct",
    name: "PCT",
    domain: "Clinical",
    description: "Patient Care Tracker / Clinical Care",
    icon: "pulse-outline",
    logoPath: undefined,
    aliases: ["patient-care-tracker", "clinical-care", "telemedicine"],
    surfaces: ["citizen", "provider"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  costa: {
    slug: "costa",
    name: "Costa",
    domain: "Finance",
    description: "Costing / Billing / Tariffs",
    icon: "receipt-outline",
    logoPath: undefined,
    aliases: ["billing", "tariffs", "charges"],
    surfaces: ["citizen", "provider"],
    mobileStatus: "blocked",
    requiredAuthContext: ["client", "provider"],
  },
  mushex: {
    slug: "mushex",
    name: "MusheX",
    domain: "Finance",
    description: "Payments / Claims / Wallets",
    icon: "wallet-outline",
    logoPath: "/brand/services/mushex-logo.png",
    aliases: ["payments", "wallet", "claims"],
    surfaces: ["citizen", "provider"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  oros: {
    slug: "oros",
    name: "Oros",
    domain: "Clinical",
    description: "Orders (lab, radiology, pharmacy, service)",
    icon: "clipboard-outline",
    logoPath: undefined,
    aliases: ["orders", "lab-orders"],
    surfaces: ["provider"],
    mobileStatus: "native",
    requiredAuthContext: ["provider"],
  },
  simba: {
    slug: "simba",
    name: "Simba",
    domain: "Wellness & Prevention",
    description: "Wellness journeys and preventive care (citizen); commodity visibility via inventory plane (provider)",
    icon: "fitness-outline",
    logoPath: "/brand/services/simba-logo.png",
    aliases: ["wellness", "wellness-service", "inventory"],
    surfaces: ["citizen", "provider"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  ndila: {
    slug: "ndila",
    name: "Ndila",
    domain: "Data & Intelligence",
    description: "Maps / Geospatial",
    icon: "map-outline",
    logoPath: "/brand/services/ndila-logo.png",
    aliases: ["maps", "geospatial"],
    surfaces: ["citizen", "provider", "publicHealth"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  nhume: {
    slug: "nhume",
    name: "Nhume",
    domain: "Enterprise & Logistics",
    description: "Dispatch / Delivery",
    icon: "cube-outline",
    logoPath: "/brand/services/nhume-logo.png",
    aliases: ["dispatch", "courier", "logistics"],
    surfaces: ["citizen", "provider", "enterprise"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  fundo: {
    slug: "fundo",
    name: "Fundo",
    domain: "Learning & Workforce",
    description: "LMS / Academy / CPD / Training",
    icon: "school-outline",
    logoPath: "/brand/services/fundo-logo.png",
    aliases: ["learning", "lms", "cpd", "training"],
    surfaces: ["citizen", "provider"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  nompilo: {
    slug: "nompilo",
    name: "Nompilo",
    domain: "Experience",
    description: "AI assistant / command / help / search layer",
    icon: "sparkles-outline",
    logoPath: "/brand/services/nompilo-logo.png",
    aliases: ["assistant", "ask", "guidance"],
    surfaces: ["citizen", "provider"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  madi: {
    slug: "madi",
    name: "Madi",
    domain: "Clinical",
    description: "Blood Transfusion / Blood Bank",
    icon: "water-outline",
    logoPath: "/brand/services/madi-logo.png",
    aliases: ["blood", "transfusion", "donor"],
    surfaces: ["citizen", "provider"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  pacs: {
    slug: "pacs",
    name: "PACS",
    domain: "Clinical",
    description: "Imaging / Radiology",
    icon: "scan-outline",
    logoPath: undefined,
    aliases: ["imaging", "radiology"],
    surfaces: ["citizen", "provider"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
  live: {
    slug: "live",
    name: "Impilo Live",
    domain: "Experience",
    description: "Webinars / telemedicine broadcasts / VOD",
    icon: "radio-outline",
    logoPath: undefined,
    aliases: ["impilo-live", "broadcasts", "webinars"],
    surfaces: ["citizen", "provider", "publicHealth"],
    mobileStatus: "native",
    requiredAuthContext: ["client", "provider"],
  },
};

export const CANONICAL_SERVICE_SLUGS: CanonicalServiceSlug[] = Object.keys(
  MOBILE_SOVEREIGN_SERVICES
) as CanonicalServiceSlug[];

export function getSovereignService(slug: CanonicalServiceSlug): MobileSovereignService {
  return MOBILE_SOVEREIGN_SERVICES[slug];
}

export function listServicesForSurface(surface: MobileSurface): MobileSovereignService[] {
  return CANONICAL_SERVICE_SLUGS.map((slug) => MOBILE_SOVEREIGN_SERVICES[slug]).filter((s) =>
    s.surfaces.includes(surface)
  );
}
